ovis-hpc/ldms

ldms/src/core/ldms_core.h

This will allow new features to be added to OVIS 4
without breaking compatability.

Add reserved field to the metric meta data

---

ldms/src/contrib/sampler/tutorial/Makefile.am
ldms/src/sampler/filesingle/Makefile.am

Fix EXTRA_DIST  in filesingle and sampler tutorial for autogen warnings

FIX EXTRA_DIST autogen warnings

---

ldms/src/core/ldms_core.h

Reserve an area in the set hdr to accomodate changes
that may affect this structure but still support backward
compatability.

Add area to ldms_set_hdr for compatible updates

---

ldms/src/ldmsd/ldmsd.c

`ldmsd -V` shows all the version numbers that we need, but `ldms-test`
has a use case that needs to determine the version of the binary in the
environment that could not execute that binary. This patch will make
"LDMSD_VERSION #.#.#" presents in `ldmsd` and could be check with
`strings /opt/ovis/sbin/ldmsd | grep LDMSD_VERSION`.

Add version string in ldmsd for binary string dump check

---

ldms/src/sampler/Makefile.am
ldms/src/sampler/appinfo_lib/Makefile.am
ldms/src/sampler/aries_mmr/Makefile.am
ldms/src/sampler/cray_system_sampler/Makefile.am
ldms/src/sampler/dstat/Makefile.am
ldms/src/sampler/examples/array_example/Makefile.am
ldms/src/sampler/examples/synthetic/Makefile.am
ldms/src/sampler/examples/test_sampler/Makefile.am
ldms/src/sampler/filesingle/Makefile.am
ldms/src/sampler/kgnilnd/Makefile.am
ldms/src/sampler/llnl/Makefile.am
ldms/src/sampler/lustre/Makefile.am
ldms/src/sampler/meminfo/Makefile.am
ldms/src/sampler/procinterrupts/Makefile.am
ldms/src/sampler/procstat/Makefile.am
ldms/src/sampler/vmstat/Makefile.am

Rename libsampler_base to libldmsd_sampler_base to reduce installed namespace polution.
Part of issue #71.

Rename libsampler_base to libldmsd_sampler_base

---

ldms/src/sampler/examples/test_sampler/test_sampler.c

The `test_sampler` stores the latest value of the metric in `schema`
structure, which is shared among sets. Hence, when there are more than
one sets, the value of the metrics got increment by the number of sets
instead of 1. This patch modifies the increment logic to use the metric
value from the sets.

Fix test_sampler metric increment logic

---

lib/src/zap/rdma/zap_rdma.c

This is driven by an issue at LANL and adds log info for listen failures.

add diagnostic info to failed rdma listen.

---

ldms/src/ldmsd/Makefile.am
ldms/src/store/Makefile.am
ldms/src/store/store_flatfile/Makefile.am

This removes incorrect use of libjson_parser (-> libjson_util)
and reverted libldmsd_plugattr name libplugattr appearances.
The occurred in the one_configure change.

fix reversion of ldmsd lib prefix and merge induced naming

---

ldms/src/sampler/filesingle/filesingle.c

fixes potential filesingle config parser array overrun.

fix missing ptr deref in string operation.

---

util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/ClusterSecrets/Makefile.am

the build is broken for genders install in some scenarios and this fixes it.

fix missing destdir in install rule of ldmsauth.conf

---

ldms/README.md
ldms/doc/Doxyfile.in
ldms/doc/mdlinkfilter.py
ldms/doc/mdtest.md
ldms/src/ldmsd/ldmsd-aggregator.md
ldms/src/ldmsd/ldmsd-sampler-dev.md
ldms/src/ldmsd/ldmsd-sampler.md
ldms/src/ldmsd/ldmsd-store-dev.md

TLDR; Make internal hyper links in Markdown files work on GitHub, GitLab
and in Doxygen-genarated HTML.
Historically, Doxygen does not understand relative document location in
the Markdown source file. It understands only a path relative to the
doxygen program working directory (which is the top-dir of the project).
GitLab on the other hand understands both document relative paths and
top-dir relative paths. As such, all internal document links in the
Markdown files are relative to the top-dir.
Unfortunately, GitHub only understands relative paths, but not top-dir
relative paths. This breaks document browsing from `README.md` and
`ldms/README.md` on GitHub.
This patch address the problem as follows:
- Change all internal hyperlink references to be relative to its
current file.
- Apply a …

Markdown link fix

---

lib/etc/ovis/set-ovis-variables.sh.in

`ZAP_LIBPATH` now should point to `<LIB>/ovis-ldms`, not
`<LIB>/ovis-lib`.

Fix wrong `ZAP_LIBPATH`

---

ldms/src/ldmsd-samplers/syspapi/syspapi_sampler.c
ldms/src/ldmsd-stores/store_papi/store_papi.c
ldms/src/ldmsd-stores/store_slurm/store_slurm.c

Fix wrong `json_attr_find()` usage that should be `json_value_find()`
instead.

Fix `json_attr_find()` misused in LDMSD samplers and stores

---

ldms/man/ldms_authentication.man
ldms/man/ldmsd.man
ldms/man/ldmsd_controller.man
ldms/src/core/ldms_xprt_auth.c
ldms/src/ldmsd/Makefile.am
ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_auth.c
ldms/src/ldmsd/ldmsd_cfgobj.c
ldms/src/ldmsd/ldmsd_config.c
ldms/src/ldmsd/ldmsd_failover.c
ldms/src/ldmsd/ldmsd_prdcr.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_request.h
ldms/src/ldmsd/ldmsd_request_util.c

This is the multi-domain authentication feature from the master branch. It brought in `auth_add` and `listen` configuration commands. `auth_add` allows users to define authentication domain that will later be used in `prdcr_add` or `listen`. `listen` command allows users to instruct `ldmsd` to listen to a port from a configuration file (instead of CLI).

Multi-domain authentication from master branch

---

ldms/src/ldmsd-stores/store_csv/store_csv_common.c
lib/src/ev/ev.h

When `-O3` is given, `-fstrict-aliasing` is assumed.

Fix type-punning/strict-aliasing gcc warning

---

lib/src/zap/rdma/zap_rdma.c

The `share` field was forgotten to set as `1` in the rendezvous
message -- making it looks like `unshare` rendezvous message.

Fix RDMA Zap Share message initialization

---

ldms/src/ldmsd-samplers/slurm/slurm_sampler.c

Remove the copy-paste residue that causes incorrect component_id's.

Fix component_id bug in slurm_sampler

---

ldms/src/ldmsd-samplers/app_sampler/app_sampler.c

The `stream` attribute was incorrectly assumed to be given in the
configuration file (JSON).

Fix app_sampler cfg file handling

---

ldms/src/store/Makefile.am

the -l form of lib flag on a directory local peer library breaks the dependency calculations of automake required for parallel build. Using the .la form works.

fix missing dependency in store makefile.am

---

lib/src/zap/ugni/zap_ugni.c

zap_ugni: two arguments instead of one given to a _set_sockbuf_sz call

---

lib/src/zap/ugni/zap_ugni.c

zap_ugni: two arguments instead of one given to a __set_sockbuf_sz call

---

ldms/src/ldmsd/ldmsd_sampler.c

The `job_set` handle was not properly put down when the sampler instance
is deleted.

Put `job_set` reference when deleting the sampler

---

ldms/src/ldmsd-samplers/app_sampler/app_sampler.c
ldms/src/ldmsd-samplers/test-samplers/test_sampler.c
ldms/src/ldmsd/ldmsd_sampler.c
ldms/src/ldmsd/ldmsd_sampler.h

The sole real use case of `samp->delete_set()` is in `app_sampler`.
The way it did before the patch was that when it received a task exit
event, it constructed a set name associated with the task and obtained
the `ldms_set_t` handle by `ldms_set_by_name()` (as `samp->delete_set()`
requires a handle to delete). Since this handle is different than the
one in the `samp->set_list` (created by `samp->create_set()`),
`samp->delete_set()` already has to iteratively compare the name of the
given `ldms_set_t` against those in the `samp->set_list` (please see
commit-id: 0f9f9dcb4). So, `samp->delete_set()` with set name makes more
sense from this use case.
Also, with -D_REF_TRACK_ compilation flag to track the correct reference
usage, we found out that all `ldms_set_t` were automatically removed …

Change the `samp->delete_set()` interface to use set name.

---

ldms/src/ldmsd/ldmsd_prdcr.c

On the delivery of LDMS_XPRT_EVENT_DISCONNECTED event,
`prdcr_connect_cb()` resets `prdcr->prd_sets`. The prd_set resetting
procedure only set `start_n_stop` flag to 0 to notify the updtr worker
to not further schedule future updates. After resetting all prd_sets,
`prdcr_connect_cb()` set `prdcr->xprt` to NULL. Because the state of the
prd_set has not changed, the update events that were scheduled before
the disconnected then tried to update (or lookup) on the prd_set which
direcly uses prdcr->xprt (NULL), leading to SIGSEGV. By changing the
state of the prd_set to ERROR before setting `prdcr->xprt` to NULL, the
update events will just wakes up, do nothing, and put the prd_set
reference back. Note that the update event will just get a synchronous
error when it tries to issue update/lookup …

Fix aggregator crash due to null `prdcr->xprt`

---

ldms/src/ldmsd/ldmsd_strgp.c

A reference has taken on `prd_set` before notifying stores that the set
is ready for storage. The store actor however forgot to put down the
reference, making the set persistent in the aggregator with storage.

Fix set-not-removed issue on aggregator with store

---

ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd_config.c

The default authentication object was set up after the configuration
file has done processing, but `prdcr_add` in the config file that did
not specify `auth` needed the default auth object to create the `prdcr`.
Hence, the default auth object (and its attributes) should be set up
during config file processing, when we knew that `set CLI` options are
done. If no config file is given, the default auth is set up in the
`ldmsd_init()` as usual.

Fix ldmsd default auth processing

---

ldms/src/core/ldms_xprt.c

`process_dir_request()` called `__ldms_find_local_set()` which took
`set->ref` reference. However, the `set->ref` was not put back when the
set was not in use, resulting in leaked resources. This patch adds the
missing `ref_put(&set->ref, "__ldms_find_local_set")` where needed in
`process_dir_request()`.

Add missing set ref put in process dir req path

---

ldms/src/core/ldms_xprt.c

Remove `ldms_rbd_get/put` residue

---

ldms/src/core/ldms_xprt.c

The reference was taken in `__ldms_alloc_rbd()` when inserting the rbd
into the rbd list in the set. When the rbd was removed from the list,
the reference was not dropped.

Add the missing rbd ref_put (set_rbd_list)

---

ldms/src/ldmsd/ldmsd_prdcr.c

When prdcr connect got synchronous error, it did not re-schedule the
connect event and hence broke the prdcr connect-retry event loop.

Fix prdcr connect synchronous error handling

---

ldms/src/core/ldms.c
ldms/src/core/ldms_xprt.c
ldms/src/ldmsd/ldmsd_updtr.c

- add `__ldms_set_delete(struct ldms_set *)` for deleting the newly
recorded set that does not have rbd yet (requires to unwind the set
create in `handle_rendezvous_lookup()` in the case of an error).
- correct error path in `handle_rendezvous_lookup()`. Previously, when
multiple-source lookup is allowed (e.g. agg2 lookup `node1/meminfo`
from both agg11 and agg12), a synchronous read on agg12 would delete
the set along with all the rbds, including the good rbd from agg11.
The prd_set associated with agg11 will hold on a stale rbd.
- Multiple-source lookup will now result in `EEXIST`.
- Update `ldmsd_prdcr` to also handle and report `EEXIST` lookup error.

Fix error path in `handle_rendezvous_lookup()`

---

ldms/src/core/ldms.h

LDMSDPORT is defined in `build/ldms/config.h`, and the file did not get
installed. Instead, the alternate version of the file
`build/ldms/src/ovis-ldms-config.h` is installed to avoid header file
collision. Hence, LDMSDPORT macro won't be resolved when compiling a
plugin outside of the ovis tree.
This patch change the use of LDMSDPORT to OVIS_LDMS_LDMSDPORT varient
that is defined in the installed header file ovis-ldms-config.h.

Fix no reference to LDMSDPORT

---

ldms/src/sampler/meminfo/Makefile.am
m4/options.m4

The previous `--disable-rpath` build issue fix replaced `-L` with
`-Wl,-rpath-link` in OVIS_LIB flag building in `options.m4`. As a
result, the `-l<LIB>` (e.g. `-lldms`) style in `*_LDADD` (vs
`$(top_builddir)/ldms/src/core/libldms.la` style) will get a library not
found error.
This patch added back the `-L` option when building the OVIS_LIB flag in
`options.m4` to support internal library `-l<LIB>` in LDADD. The
`meminfo` Makefile.am was added in this patch as a showcase.
NOTE: This patch has been tested both with and without
`--disable-rpath`.

Fix `-l<LIB>` build issue for internal libraries

---

ldms/src/sampler/sampler_base.c
ldms/src/sampler/sampler_base.h

This appends a warnings field to the base sampler structure and uses it to suppress repeated spew of 5 warnings to the log related to jobinfo insufficiency. A warning is issued once and then not issued again unless it is first resolved and then reappears.

fix redundant job set warnings cluttering the logs

---

ldms/scripts/ldms-static-test.sh.in
ldms/scripts/pll-ldms-static-test.sh.in

a hardcode version slipped into [pll-]ldms-static-test.sh. This replaces it with @VERSION@
the same branch exists in ovis-hpc/ovis directly but should not.

fix hardcoded version number that sneaked into test scripts.

---

configure.ac
ldms/scripts/envldms.sh.in
ldms/scripts/ldms-l2_test.sh.in
ldms/scripts/ldms-plugins.sh.in
ldms/scripts/ldms-static-test.sh.in
ldms/scripts/ldms-wrapper.in
ldms/scripts/pll-ldms-static-test.sh.in
ldms/src/ovis-ldms-configvars.sh.in
m4/options.m4

This adds the plugins_rpath (a generalization of the configure.ac soslibdir variable) to configure and environment scripts. Plugins_rpath can be added to the runtime LD_LIBRARY_PATH to allow resolution of any off-path libraries used by ldms plugins, such as libpapi and libsos.

add plugins_rpath

---

ldms/src/sampler/papi/Makefile.am

makefile missing variable added

fix missing link variable for papi-sampler.

---

lib/src/json/json_parser.y

`json_parser` was broken by the `json_entity_new()` API change.

Fix `json_entity_new()` call in json_parser

---

ldms/src/core/ldms_xprt.c

In `__ldms_xprt_zap_new()`, the zap driver is obtained and is cached
by `__ldms_zap_get(); zap_get();` call chain. But, in the error path of
`__ldms_xprt_zap_new()`, the cached `zap` driver is freed, leading to
use-after-free for the next call of the same transport type. This patch
modify the error path to not free the cached zap driver.

zap must not be freed by ldms (potential use-after-free)

---

ldms/src/sampler/Makefile.am

Adding link flags needed when papi and pfm are not in system paths.

fix missing papi linkages

---

ldms/src/ldmsd/ldmsd_updtr.c

uninit variable use in schedule_set_updates
uninit variable use in cancel_prdcr_updates
thread unsafe use after free in __updtr_task_tree_cleanup
null pointer use due to brace mis-style in prdcr_ref_new

fix bugs in v4 updater

---

ldms/src/sampler/lustre/lustre_sampler.c
ldms/src/sampler/lustre/lustre_sampler.h

lustre_sampler.h: add unused attribute to stats_key sometimes needed.
lustre_sampler.c: missing oom checks, err path memory leaks, buffer overruns/magic numbers

fix v4 lustre_sampler bugs

---

NOTE-ZAP-TEST-SHARED-MAP.md
ldms/examples/multiple-xprt/ldmsd.cfg
ldms/src/core/ldms.c
ldms/src/core/ldms.h
ldms/src/core/ldms_private.h
ldms/src/core/ldms_xprt.c
ldms/src/core/ldms_xprt.h
ldms/src/ldmsd/ldmsd_config.c
ldms/src/test/test_ldms_notify.c
ldms/src/test/test_ldms_push.c
ldms/src/test/test_ldms_set_info.c
lib/src/zap/fabric/zap_fabric.c
lib/src/zap/fabric/zap_fabric.h
lib/src/zap/rdma/zap_rdma.c
lib/src/zap/rdma/zap_rdma.h
lib/src/zap/sock/zap_sock.c
lib/src/zap/sock/zap_sock.h
lib/src/zap/test/Makefile.am
lib/src/zap/test/zap_test.c
lib/src/zap/test/zap_test_big.c
lib/src/zap/test/zap_test_shared_map.c
lib/src/zap/ugni/zap_ugni.c
lib/src/zap/ugni/zap_ugni.h
lib/src/zap/zap.c
lib/src/zap/zap.h
lib/src/zap/zap_priv.h

[x] zap_sock
[x] zap_rdma
[x] zap_ugni
- 2 samp
- 1 agg1
- 1 agg2 -> sos
- also tried killing 1 samp ... the set went away
- resurrecting the sampler and the set was aggregated and stored
again.
[x] fabric
[x] add a way to select fabric provider/domain in
[x] zap API
[x] ldms xprt name (format: fabric.PROVIDER@DOM)
[x] test zap sock with:
[x] fabric.sockets@eth0
[x] fabric.verbs
[x] fabric.ugni - not supported due to lack of WAIT_FD and
fi_poll in gni provider.
[x] zaptest
[x] ldms/ldmsd
[x] modify ldms to use shared map.
[x] getting rid of rbd
[x] Pass ldms-test/agg_test
[x] Pass test_ldms_push
[x] Pass test_ldms_notify
[x] Pass all test cases in ldms-test repo (sock xprt)
[x] manually tested with the following use case:
- 1 sampler (meminfo) listening on sock, fabric.sockets and …

shared zap map and ldms rbd removal

---

ldms/src/sampler/sampler_base.c
ldms/src/sampler/sampler_base.h

Parsing and checking uid/gid/perm is complicated enough that every
sampler should be able to use it without cloning code or being forced to use the
base schema jobid/compid/appid logic. This factors out the security
config parsing into a function and then calls it from the base_config
function.
I have a network sampler coming that needs this.

add base_auth_parse to allow samplers to use standard uid/gid/perm

---

lib/src/zap/rdma/zap_rdma.c

fix inconsist error typing in __ep_state_check z_rdma_send z_rdma_share z_rdma_write.
fix incorrect return code in __rdma_post_send (use zap instead of errno code) to get correct error message later.

fix error coding in v4 zap_rdma.c

---

ldms/src/ldmsd/ldmsd_request.c

fixes:
buffer overflow in __greeting_path_resp_handler
missed oom chk in Snprintf, __greeting_path_req_handler
mem leaks in __greeting_path_req_handler
fmt err in __prdcr_set_status

fix leak, oom, overflow, and fmt errors in ldmsd_request.c v4

---

ldms/scripts/ldms-csv-export-sos

Fixed ldms-export-csv-sos script to be reflect the compound indices SOS-4 has by default.
Also added the --kind-file option to pass in a user-generated kind file to the script.

Ldms csv export sos fix

---

ldms/src/ldmsd/test/ldmsd_stream_publish.c
ldms/src/ldmsd/test/ldmsd_stream_subscribe.c

need to trap oom so later code doesn't get blamed when testing.

add missing oom checks to v4 stream test/util code.

---

ldms/scripts/examples/procstat.3

Fixed procstat.3 config file for OVIS v4. Used with ldms-static-test.sh test script.

Patch fix to procstat.3

---

ldms/scripts/examples/variable
ldms/scripts/examples/variable.3
ldms/src/sampler/Makefile.am
ldms/src/sampler/variable/Makefile.am
ldms/src/sampler/variable/Plugin_variable.man
ldms/src/sampler/variable/variable.c

This sampler periodically redefines its sets and schemas, reusing names.
This works, but the current aggregation never sees the new definitions of recycled names.
Symptom of this is that the store only gets the first cycle of data in each schema.
Is there something about unpublish needed to convince downstream to drop old definitions?
to run the sampler, do install and then
bin/ldms-static-test.sh variable

Update sampler 'variable' to actually work as planned.

---

ldms/src/ldmsd/ldmsd_request_util.c

fixes:
req_str_id_cmp return unsigned is inconsistent with internal computation and use as bsearch function
(given c casting rules, we may be operating correctly in spite of ourselves)
use of uninitilized value in add_attr_from_attr_str main logic leads to buffer overrun
use of uninitilized value in less expected branch of __ldmsd_parse_auth_add_req logic leads to incorrect return

fix logic bugs in v4 ldmsd_request_util

---

ldms/src/sampler/hello_stream/Makefile.am

The referenced hello_sampler.h file does not exist.

Fix bug in hello_stream build that breaks "make dist"

---

.github/workflows/test-make-dist.yaml

It is not uncommon for changes to the ovis build system to break the "make dist"
target. We introduce a GitHub Actions workflow to automate the test of
the build system up through "make dist" so we will automatically be alerted
of breakage on PRs for OVIS-4 and on the OVIS-4 branch.
The master branch hasn't yet had all of the build system cleanup that OVIS-4
has had, but this testing can easily be expaned to master once that has
happened.

Introduce automated testing of "make dist"

---

ldms/src/sampler/sampler_base.c
lib/src/ovis_util/util.c
lib/src/ovis_util/util.h

report errors from sampler-base when failures occur, often due to out of set memory.

Include error messages in sampler_base ooms.

---

configure.ac
lib/Makefile.am

"ENABLE_LIB_PYMAP" added to control cython check for sos and ldms installation without python plugins/support.

Added new option for python configuration

---

.gitignore
Makefile.am
config/git-version-gen
configure.ac

Implement git-version-gen for ldms versioning. The git-version-gen
script comes from the autoconf git repository at commit 8a09003
in build-aux/git-gersion-gen.
The LDMS project just needs to begin using annotated tags for its
version tags to work with this change. Right now the version will
show as "UNKNOWN" until an annotated tag is created at a previous
version.
The project will also need to decide on a consistent version prefix
Right now this patch assumes that the version prefix is "OVIS-".
For testing purposes, the author made an annotated tag like so:
$ git tag -a OVIS-4.3.3.0test OVIS-4.3.3 -m "Test tag"
With that tag in place, we test that things are working by
running:
$ sh autogen.sh
[...]
$ ./configure --version
ovis-ldms configure 4.3.3.0test.79-6422
generated by GNU Autoconf …

Implement git-version-gen for ldms versioning

---

lib/src/ovis_util/test_util.c
lib/src/ovis_util/util.c

test_util.c:
missing oom check
util:
str_repl_cmd: missing oom check, uninit var use, pipe leak
ovis_pgrep: directory leak, unused var
ovis_get_mem_size: buffer overrun
_scpy: incorrect nul terminator

fix v4 util.c bugs

---

.github/workflows/create-release.yaml

This introduces a new "Create Release" GitHub workflow, which automates
the process of creating a release on GitHub any time a new tag is pushed
to the repo.
The workflow triggers any time a new tag is pushed to the repo that
matches the pattern 'OVIS-4*'.
First the workflow builds the cannonical tarball.
Next the workflow generates a new release on the
https://github.com/ovis-hpc/ovis/releases page. The release notes
are taken from the body of the annotated tag.
Finally, the cannonical tarball is uploaded to the Assets of the
newly created release.

Introduce create-release.yaml GitHub workflow

---

lib/src/ev/evw.c

With the change the worker state is reset back from FLUSHING to RUNNING
after all events have been flushed.

ovis event: the worker state stuck in FLUSHING if ev_flush is called.

---

util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/ldms-functions.in

failing to check asap means gender syntax errors can masquerade as other problems (no genders found for host) later. this fixes that.

check gender file syntax earlier.

---

ldms/src/ldmsd/ldmsd_config.c

more output (xprt options) in ldmsd_config if transport new fails.

add attrs to transport error output.

---

ldms/src/sampler/aries_mmr/aries_mmr_set_configs/Makefile.am
ldms/src/sampler/hello_stream/Makefile.am
ldms/src/sampler/hello_stream/stream_configs/Makefile.am

Re issue #310 
Moved aries_mmr_set_configs and hello_sampler_util from XXX/etc to XXX/share/doc/ovis-ldms-X.Y.Z/examples

move some examples files from /etc to /share

---

ldms/src/auth/ldms_auth_ovis.c

Fix a leaked pointer in auth  ovis handshake

V4 sock auth ovis leak

---

ldms/scripts/examples/setclones
ldms/scripts/examples/setclones.1
ldms/scripts/examples/setclones.2
ldms/src/sampler/examples/synthetic/synthetic.c

This generates many sets from a test sampler, but the names differ only in the numeric suffix, so it may not tease complex tree structures as desired.

add 'extra' option to synthetic, to have N clone sets

---

lib/src/ovis_event/ovis_event.c

This stops numerous valgrind warnings when using sock, at low init code cost.

add code to init entire ovis event structures including holes.

---

configure.ac
ldms/configure.ac
lib/configure.ac

- Modify autoconf configure script (top-level, lib/ and ldms/) to use
/usr/bin/python3 by default.
- Also check that the python is version 3.6 or greater.

python3 configure script

---

ldms/src/store/hello_stream/hello_stream_store.c

fclose does not accept null, which will happen if the plugin is
loaded but never used, as in ldmsd -u.

fix crash on exit in hello_stream_store.c

---

ldms/src/ldmsd-samplers/appinfo/Makefile.am
ldms/src/ldmsd-samplers/dstat/Makefile.am
ldms/src/ldmsd-samplers/filesingle/Makefile.am
ldms/src/ldmsd-samplers/generic_sampler/Makefile.am
ldms/src/ldmsd-samplers/jobinfo/Makefile.am
ldms/src/ldmsd-samplers/jobinfo/jobinfo_slurm/Makefile.am
ldms/src/ldmsd-samplers/papi/Makefile.am
ldms/src/ldmsd-samplers/shm/Makefile.am
ldms/src/ldmsd-samplers/shm/mpi_profiler/Makefile.am
ldms/src/ldmsd-samplers/shm/shm_util/Makefile.am
ldms/src/ldmsd-samplers/slurm/Makefile.am
ldms/src/ldmsd-samplers/syspapi/Makefile.am
ldms/src/ldmsd-stores/store_csv/Makefile.am
ldms/src/ldmsd-stores/store_influx/Makefile.am
lib/src/ev/Makefile.am
lib/src/json/Makefile.am
lib/src/ovis_util/Makefile.am

Replace the linking flags of ovis libraries from -l to *.la. Otherwise, ovis cannot be built on Ubuntu.

Fix linking flags

---

ldms/src/core/ldms_xprt.c

The rc variable wasn't initialized so the function might return a random
number on success.

ldms_xprt: send_req_cancel_push() returns a random value on success

---

lib/src/zap/rdma/zap_rdma.c
lib/src/zap/zap.c

The mlx5 driver now has logic that destroys the verbs
context on exit. This resulted in applications such
as ldms_ls crashing on exit.
Destructor logic has been added to the Zap RDMA
transport driver to cancel and join the threads
that were using these mlx5 resources.

Add pthread_cancel/join logic to the RDMA transport

---

ldms/src/sampler/clock.c
ldms/src/sampler/dstat/dstat.c
ldms/src/sampler/examples/array_example/all_example.c
ldms/src/sampler/loadavg/loadavg.c
ldms/src/sampler/meminfo/meminfo.c
ldms/src/sampler/procinterrupts/procinterrupts.c
ldms/src/sampler/vmstat/vmstat.c

fix spaces missing after sampler names in config usage lines

---

ldms/src/ldmsd-samplers/test-samplers/test_sampler.c

Without the patch, the test_sampler plugin requests multiple 'config'
lines to define a schema and to add a set. This design is incompatible
with the new JSON configuration protocol. Moreover, the test_sampler
plugin was extended many times, and its code has become complicated.
The change simplifies the plugin code and makes it compatible with the
JSON protocol.

Refactor the test_sampler plugin

---

lib/src/third/Makefile.am

The crc-based functions enabled with sse42 on some compilers/platforms are not used when CITYSLIM is defined, so omitting the flag has no effect on ldms use of cityhash.

fix make distcheck fail on aarch64 due to -msse4.2 flag

---

lib/src/zap/sock/zap_sock.c

The optval value was initialized to 0 which results in disabling
KEEP-ALIVE. The patch initlizes the variable to a non-zero value.

Enable KEEP-ALIVE in zap sock.

---

configure.ac
lib/src/Makefile.am
lib/src/ovis_ev/Makefile.am
lib/src/ovis_ev/ev.c
lib/src/ovis_ev/ev.h
lib/src/ovis_ev/ev_priv.h
lib/src/ovis_ev/evw.c
lib/src/ovis_ev/ovis_ev_test.c

This API provides a mechanism to schedule events to worker threads. This
will replace the ldmsd_task paradigm in order to simplify the ldmsd
state machine.

Create a worker/event library

---

configure.ac

Incorrectly using " for quoting in the autoconf flavor of m4 was
resulting in an empty file name "=3.6" created at configure time.
We replace the "" with [].

Repair autoconf quoting in AX_PYTHON_DEVEL calls

---

ldms/src/core/ldms_xprt.c
lib/src/zap/fabric/zap_fabric.c

this fixes information leak to network by initializing raw buffers and fixes insufficiently initialized addr and event data in ldms_xprt.c..

fix V4 fabric xprt mem inits

---

lib/src/ovis_util/util.c

This resets pointer p after the pipe is closed to avoid any double close and initializes p before any possible goto that could lead to closing an random pointer from the stack.

fix invalid pipe pointer usage

---

configure.ac
m4/ax_compare_version.m4

This version packs the cython test into a function.
The major change is that this version looks for variations on the
cython binary name that contain the python version string that
we detected. That way we don't need to hard code various python
version suffixes for cython. Also, we avoid the issue that there
may potentially be multiple different cython's installed for
multiple versions of Python at the same time (e.g. cython3.6 and
cython3.8 at the same time). This patch makes sure that we don't
pick the cython for the wrong version of python.
Also we run the cython version check in the feature check for
each cython that we find, not just the first one. That is minor
improvement as well.

Improve autoconf cython test

---

lib/src/ovis_util/test_util.c
lib/src/ovis_util/util.c
lib/src/ovis_util/util.h

This update allows test_util to run to completion, puts in a test for sleep and other program calls in $( ) popen expansion, and puts in a compiler warning for ovis_join operations which are not null-terminated as required by the header descriptoin.

fix test_util.c nits (add sentinel warning, sleep demo)

---

ldms/src/core/ldms_xprt.c

In some lookup mode, e.g. LOOKUP_RE and LOOKU_BY_SCHEMA, there can be
multiple sets resulting from the lookup operation. The lookup requesting
side shall expect multiple rendezvous messages from this one lookup
request. However, on the requesting side, the lookup request context was
prematurely freed after the first rendezvous message was received, and
the same ctxt was double-freed in the second rendezvous, and so-on.
The `lookup.more` flag in the rendezvous message tells the requesting
side if this is the last rendezvous messgae. It shall be checked, and
the lookup context shall not be freed if more rendezvous messages are
expected.

Fix double-free when LDMS lookup yields multiple sets

---

ldms/python/ldmsd/ldmsd_config.py
ldms/python/ldmsd/ldmsd_controller
ldms/python/ldmsd/ldmsd_request.py
ldms/src/core/ldms_xprt.c
ldms/src/core/ldms_xprt.h
ldms/src/ldmsd/ldmsctl.c
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_config.c
ldms/src/ldmsd/ldmsd_prdcr.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_request.h
ldms/src/ldmsd/ldmsd_request_util.c
ldms/src/ldmsd/ldmsd_stream.c
ldms/src/ldmsd/ldmsd_stream.h

[x] Manages clients of ldmsd stream republishing service in a
red-black-tree with `<PEER_ADDR>:<STREAM_NAME>` keys. The clients
are registered by `LDMSD_STREAM_SUBSCRIBE_REQ`.
- RECALL: The ldmsd-to-ldmsd stream republishing service
subscription is driven by `prdcr_subscribe` config command.
[x] `prdcr_unsubscribe` config command to instruct ldmsd to unsubscribe
the republishing stream from peers.
[x] ldmsctl
[x] ldmsd_controller
[x] Add `LDMSD_STREAM_UNSUBSCRIBE_REQ` request. This is an
ldmsd-to-ldmsd request to stop the stream republishing.
[x] automatically remove clients of stream republishing service
(registered by `LDMSD_STREAM_SUBSCRIBE_REQ`) on connection
termination.
[x] ldms_xprt_sockaddr() caching: cache the remote/local addresses
on the success zap_get_name() so that the …

stream_unsubscribe + prdcr_unsubscribe

---

ldms/man/ldmsctl.man
ldms/man/ldmsd_controller.man
ldms/src/core/ldms.c
ldms/src/core/ldms.h
ldms/src/sampler/app_sampler/app_sampler.c
ldms/src/sampler/examples/synthetic/synthetic.c
ldms/src/sampler/ibnet/ibnet_data.c
ldms/src/sampler/job_info/jobinfo.c
ldms/src/sampler/ldms_jobid.c
ldms/src/sampler/papi/papi_sampler.c
ldms/src/sampler/sampler_base.c
ldms/src/sampler/sampler_base.h
ldms/src/sampler/slurm/slurm_sampler.c

We modify the sampler code to eliminate the many different hard coded
sampler permission defaults, and instead inherit the default consistently
from ldms_set_new().
Also change the the default permissions from the too-permissive default
of 0777 to a more secure 0440.
This consolidation work is useful on its own as refactoring (to eliminate redundant
hard coded defaults), but it also lays the ground work for introducing 
global defaults for sampler uid, gid, and perm that can be set once at the ldmsd
level instead of having to repeat the configuration over and over again for each
smapler plugin in the configuration.
We do still preserve the capability to individually set uid/gid/perm values per
plugins if so desired.

Consolidate sampler default authentication values

---

.github/workflows/create-release.yaml
.github/workflows/test-make-dist.yaml
configure.ac
ldms/python/.gitignore
ldms/python/Makefile.am
m4/cython_check.m4

Make the python & cython autoconf checks optional by default.
Also allow python & cython to be required with --enable-python,
and disabled with --disable-python.
It turns out that the AX_PYTHON_DEVEL macro is dependent on the
AM_PATH_PYTHON macro. While the AX_PYTHON_DEVEL macro does not
have action-if-found/-not-found options, the AM_PATH_PYTHON macro
does. While it this still allows that AM_PATH_PYTHON can succeed
and AX_PYTHON_DEVEL can fail, in most instances this won't be
the case.
The CYTHON_CHECK macro is upgraded to have action-if-found and
action-if-not-found options. Also the macro is moved into its
own file in the m4 directory.
Since the cython check is now conditional, we remove the special
cython handling from the make dist and create release workflows.

Make the python & cython autoconf checks optional by default

---

ldms/src/core/ldms.c
ldms/src/core/ldms.h

`ldms_init()` returned `-1` on error, which is inconsistent to other
ldms interfaces. It shall return `errno` for consistency.

`ldms_init()` returns errno for consistency

---

lib/src/ovis_json/ovis_json.c
lib/src/ovis_json/ovis_json.h
lib/src/ovis_json/ovis_json_parser.y

The following functionalities are added.
* Dump a JSON entity to a string (json_entity_dump)
* Copy a JSON entity (json_entity_copy)
* Create a JSON dictionary entity by giving the list of its
attribute-value pairs (json_dict_build)
* Return the number of dictionary attributes (json_attr_cnt)
* Remove an attribute from a dictionary (json_attr_rem)
* Pop an element of a list (json_item_pop)
* Remove an element of a list (json_item_rem)
For ease of use, the following changes are made.
* To create a JSON ATTR entity, json_entity_new() receives char *
instead of json_entity_t for the attribute key
* json_attr_add() receives char * as key and json_entity_t as attribute
value, instead of a single attribute entity itself

Extend the ovis_json library functionalities

---

.github/workflows/build-test-centos7.yaml
.gitignore

This is a first simple build test for ovis/ldms that uses a CentOS7 container that I created and pushed to Docker Hub.
The test just does autogen, configure, and make. We can expand on this over time, expanding this flow and perhaps adding
other build/test workflows as needed. But this perhaps will server as a good starting point for testing builds.
The logic to employ a container in the github workflow is really simple. We just add the following to the job:
```
container:
image: morrone/centos7-ldms-build:latest
```
This workflow uses an image that I created using the following Dockerfile:
```
FROM centos:7
RUN yum install -y epel-release && yum update -y && yum install -y \
autoconf \
automake \
libtool \
make \
bison \
flex \
gettext-devel \
libevent-devel \
openssl-devel \ …
```

Introduce a build test workflow using a custom CentOS7 container

---

ldms/python/ldms.pyx

This patch changes `TypeError` to `ValueError` per @tom95858 code review
in #428. @narategithub forgot to add `-a` when he did `git --amend`.

Amend LDMS Cython error type

---

.gitignore
Makefile.am
ldms/Makefile.am
ldms/etc/.gitignore
ldms/etc/Makefile.am
ldms/etc/systemd/.gitignore
ldms/etc/systemd/Makefile.am
ldms/man/Makefile.am
ldms/src/.gitignore
ldms/src/Makefile.am
ldms/src/core/Makefile.am
ldms/src/sampler/aries_mmr/aries_mmr_set_configs/Makefile.am
ldms/src/sampler/hello_stream/Makefile.am
ldms/src/sampler/hello_stream/stream_configs/Makefile.am
ldms/src/test/.gitignore
ldms/src/test/Makefile.am
lib/etc/ld.so.conf.d/.gitignore
lib/etc/ld.so.conf.d/Makefile.am
lib/etc/ovis/.gitignore
lib/etc/ovis/Makefile.am
lib/src/.gitignore
lib/src/Makefile.am
lib/src/coll/Makefile.am
lib/src/mmalloc/Makefile.am
lib/src/ovis_auth/Makefile.am
lib/src/ovis_ctrl/Makefile.am
lib/src/ovis_json/Makefile.am
util/sample_init_scripts/genders/systemd/services/.gitignore

Eliminate many unnecessary uses of install-data-local, install-exec-local, clean-local, and related. Replace them with normal automake mechanisms.
Also add more .gitignore entries for build-time files.

Build system cleanup

---

lib/src/zap/ugni/zap_ugni.c

Calling GNI_SubscribeErrors() with NULL nic_handle is restricted for
privileged users. For a non-privileged user, the function call results
in GNI_RC_INVALID_PARAM. Since GNI_SubscribeErrors() is called after
zap_ugni attached to a domain and got a `_dom.nic` handle, the handle is
is used instead of NULL so that non-privileged users can also use
zap_ugni.

Fix zap_ugni GNI_SubscribeErrors error in non-privileged mode

---

ldms/src/ldmsd/ldmsctl.c
ldms/src/sampler/procinterrupts/procinterrupts.c

`-Wall` in GCC 9.3.0 enables `-Wformat` which also enables
`-Wformat-truncation`. The `-Wformat-truncation` warns about possible
formatted output truncationl. For example,
char buff[64];
char s[64];
fgets(s, 63, stdin);
snprintf(buff, sizeof(buff), "s is %s", s);
the length of `s` could be 63, the format "s is %s" could be
larger than 64 which results in a warning that turns in to an error by
`-Werror`.
The two places in the code tree that have format-truncation warnings
have the same kind of usage above, i.e. string printing into another
string with the same size. The printing strings (equivalent to `s` in
example above) were too big for the content they hold. Downsizing
them appropriately cleared the format-truncation warnings.

Address `-Wall -Werror` error (format-truncation)

---

ldms/python/ldms.pyx

The refactoring of the Exception types mistakenly removed a return
from the connect method which resulted in None being returned on
synchronous connect.

Add missing return in connect()

---

ldms/python/ldms.pyx
ldms/python/ldmsd/ldmsd_config.py

Opt for python style error report and handling for Xprt.connect(), i.e.
the error would be raised, not returned. This patch also modify the
application that uses the interface (currently just `ldmsd_config`
module whic is a supporting module for ldmsd_controller).

Xprt.connect() python style error handling

---

.github/workflows/build-test-centos7.yaml
ldms/src/Makefile.am

Add the missing CLEANFILES to ldms/src/Makefile.am to repair
"make distcheck".
The commit:
* 713db19 2020-09-30 General build system cleanup
neglected to add the appropriate CLEANFILES in ldms/src/Makefile.am
when it removed the custom distclean-local.
Also add a "make distcheck" job to the centos7 workflow.

Add missing CLEANFILES

---

lib/src/zap/fabric/zap_fabric.c

zap_fabric `g.log_fn` is used by debugging print in `init_once()`
before it is set -- leading to SIGSEGV due to `g.log_fn` being NULL.
`g.log_fn` is assigned first in this patch.

Fix zap_fabric debug crash due to log_fn

---

lib/src/zap/rdma/zap_rdma.c

`zap_ep_state_str()` call was a typo. It should be
`__zap_ep_state_str()`.

Fix zap_rdma build error with -DDEBUG

---

ldms/src/core/ldms_xprt.c

Zap endpoint `x->zap_ep` in the LDMS transport were set to `NULL` in
`__ldsm_xprt_resource_free()` without calling `zap_free()`. As a
result, the zap endpoint is leaked. The bug is verified in sock, rdma
and fabric-over-verbs transports by running a sampler ldmsd and check
the number of file descriptors before and after `ldms_ls` to the
daemon.
This patch freed the zap endpoint before setting it to `NULL`. The fix
is verified with the file descriptors check described above on sock,
rdma and fabric-over-verbs transports.

Fix zap endpoint leak

---

.github/workflows/create-release.yaml

Add a test that uses git for-each-ref to test if the tag looks like
a annotated tag. If it does not, we print a clear error message,
"does not look like an annotated tag".
Also, github was warning that set-env is deprecated, so we update
to using the "$GITHUB_ENV" file method of setting environment
variables for later steps.
Finally, update to using the ubuntu-20.04 VM from ubuntu-18.04.

Add test for annotated tag to create-release workflow, other cleanup

---

configure.ac
ldms/src/sampler/Makefile.am
ldms/src/sampler/job_info_slurm/Makefile.am
ldms/src/sampler/spank/Makefile.am

Instead of having individual module build options, just build
slurm plugins if their dependecies are met.
The slurm_sampler plugin appears to have no external dependencies,
so it is build unconditionally.
The jobinfo_slurm and slurm_notifier slurm spank plugins are built
it slurm is detected.  They can be required by using "--with-slurm"
and turned off by using "--without-slurm".

Remove SLURM-related configure options

---

ldms/src/core/ldms_xprt.c

When ldms xprt received zap connect error event, it set `xprt->zap_ep`
to `NULL` without releasing the zap endoint. This leads to zap endpoint
leak (and file descriptor leak). The bug can be verified by running an
aggregator with a prdcr that tries to connect to a sampler that is not
running. The prdcr will keep reconnecting, and hence growing
/proc/PID/fd. This patch simply put in the forgotten `zap_free()` to
release the zap endpoint.

Fix zap endpoint leak in connect error event

---

util/sample_init_scripts/genders/man/ldmsd-genders.man
util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/ldmsd.in
util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/ldmsd.local.conf
util/sample_init_scripts/genders/systemd/services/ldmsd.service.in
util/sample_init_scripts/genders/systemd/services/ldmsd@.service.in

also set default key file name for ovis auth only if ovis type is specified.

Fix extra args appearing in ldmsd command when munge used.

---

ldms/src/core/ldms_xprt.c
ldms/src/core/ldms_xprt.h

This change fixes 2 issues in ldms_xprt_sockaddr().
* ldms_xprt_sockaddr() always passes 0 as sa_len to zap_get_name()
instead of the given value by the caller
* ldms_xprt_sockaddr() may cause memory overflow if the given buffers
are smaller than the actual addresses.

Fix ldms_xprt_sockaddr()

---

ldms/src/core/ldms_xprt.c

When `zap_connect()` failed synchronously, zap endpoint were left alone
and the ldms xprt reference that was taken when setting zap ucontext was
not put back. Hence, the LDMS xprt reference would never reached 0 and
the associated resources would not be freed. This patch releases the
zap endpoint and put down the associated LDMS xprt reference.

Fix endpoint leak when zap_connect failed synchronously

---

.github/workflows/build-ddebug-centos7.yaml

This patch adds a github job for a build test with `CFLAGS='-DDEBUG'`
targeting `OVIS-4` branch. This is an effort to keep the DEBUG portion
of the code maintained (at the lesat built).

Add `-DDEBUG` build test github job

---

configure.ac
ldms/src/sampler/Makefile.am
ldms/src/sampler/papi/Makefile.am
ldms/src/sampler/syspapi/Makefile.am

Convert the libpapi/libpfm configuration to the use of more
standard AC_LIB_HAVE_LINKFLAGS() configuration mechanisms. Also
update all modules that are dependant on libpapi/libpfm to
use the LTLIBPAPI and LTLIBPFM variables that are created by
AC_LIB_HAVE_LINKFLAGS. This fixes the broken linkage and rpath
dependencies that currently existed when using custome papi/pfm
install paths.
We also eliminate the unessary extra configure options for each
component that depends on papi, and instead just have one option
for all components that require papi. The new configure option
is --enable-papi/--disable-papi. The three options are:
--enable-papi specified: papi must be found, or configure returns
an error
--disable-papi specified: do not build components that depend on papi
No papi option …

Overhaul the libpapi/libpfm configuration handling

---

ldms/src/sampler/sampler_base.c

The sampler_base parsing of the octal permissions bits allowed parse errors to go through. This could lead to an untrapped configuration error leaving set access security at a level different than the user intended.

fix masking of perm bits definition error on sampler_base

---

ldms/src/ldmsd/ldmsd_request.c

in handling an err case, buff may be freed without prior assignment.

fix free of uninit pointer from ldmsd_request stack.

---

.github/workflows/build-test-centos7.yaml

- add "-Wall -Werror" to the build test.
- use ovishpc container image for the build. This is the same one used
in ldms-test repository.

github action build test update

---

lib/src/zap/fabric/zap_fabric.c

The epoll event parameter for the zap_fabric listening endpoint event
queue was set to `EPOLLIN|EPOLLOUT`. This made `epoll_wait()` returned
right away since the file descriptor was (somehow) ready for "write",
and when we process the event queue (`scrub_cq()`), we got -FI_EAGAIN
since there was nothing yet to read. The CM thread in zap_fabric that
processes the event queus will appear busy. Setting the epoll event
parameter to `EPOLLIN` solved the issue.

Fix zap_fabric busy wait in listening endpoint

---

lib/src/zap/fabric/zap_fabric.c

zap_fabric cq thread uses epoll with fabric WAIT_FD to tell when a
completion is ready to be processed by `fi_cq_read()`. However,
`fi_cq_read()` only reads the completion entry from the cq. It does not
read the notification from the WAIT_FD. As a result, WAIT_FD is always
available for EPOLLIN, and `epoll_wait()` instantly returned, making the
cq thread spin with false notification.
According to `fi_poll(3)` man page, `fi_trywait()` should be called and
get `FI_SUCCESS` before we natively wait the WAIT_FD (e.g.
epoll_wait()) on both cq and eq. And, if `fi_trywait()` returns
`-FI_EAGAIN`, the queue is not empty and shall be processed before
natively wait for new entries.
This patch add the logic in zap_fabric `scrub_cq()` and `scrub_eq()` to
call `fi_trywait()` on the cq and eq, then …

zap_fabric: fix spinning cq/eq thread

---

lib/src/zap/fabric/zap_fabric.c

Since zap does not (yet) have send completion, the operation is
flushed without calling application callback. However, the flush
handling of the `send` request returned from the flush_io_q() function
right away instead of continuing to flush the next work request.
This patch the flush_io_q() to continue flushing the entire io_q.

Fix zap_fabric flush_io_q

---

ldms/scripts/examples/dstat.job
ldms/scripts/examples/dstat.job.1
ldms/scripts/examples/dstat.job.2
ldms/scripts/examples/dstat.job.3
ldms/src/sampler/dstat/Makefile.am
ldms/src/sampler/dstat/Plugin_dstat.man
ldms/src/sampler/dstat/dstat.c
ldms/src/sampler/dstat/ldms_dstat_schema_name.man
ldms/src/sampler/dstat/parse_stat.c
ldms/src/sampler/dstat/parse_stat.h

The dstat sampler can now collect a simple or detailed summary
of /proc/self/fd open file descriptors. option fd=1 collects
just the count and fdtypes=1 also collects file descriptor counts
by type (anon, pipe, dev, /path, socket). fd info collection is
off by default.
this also adds the option auto-schema=1 (off by default)
which changes the default schema name from dstat to dstat_$hash
where hash is 1 or 2 hex digits derived from the option flags
which control the content of the schema. A utility ldms_dstat_schema_name
provides the schema name for storage policy setup.
When running an aggregator, using dstat with fdtypes=1 enabled will help identify leaks of file descriptors.

add file descriptor count option to dstat

---

lib/src/zap/fabric/zap_fabric.c

When building zap_fabric without `-DDEBUG`, the static global variable
`z_fi_op_str` is not used. With `-Wall -Werror`, this resulted in
build error. This patch marks the variable unused with
`__attribute__((unused))`.

Fix zap_fabric build error (w/o DEBUG)

---

lib/src/zap/sock/zap_sock.c

This passed `zap_test` and all test cases in `ldms-test` repository.

zap_sock - only enable EPOLLOUT when necessary

---

.github/workflows/4.3.3-compat-test.yaml

* Change the update offset of the 1st-level aggregator to be 100 ms
ealier than that of the 2nd-level aggregator
* Make the test sleep between starting the sampler daemon and starting
the 1st-level aggregator
* Fix a typo that causes the test to start ldms_ls (>v4.3.3) instead of ldms_ls (v4.3.3)

Make the 4.3.3 compatibility test (4.3.3-compat-test.yaml) more robust

---

.github/workflows/build-test-ubuntu.yaml

The test includes build job and distcheck job. The build uses the
default enable/disable configure options.

Add a build test on Ubuntu-20.04

---

lib/src/zap/zap.c

When an LDMSD starts on Ubuntu20.04 as a daemon, the process stuck after
the demonization process starts. It turns out that it is a deadlock when
glibc is handling the child hook registered in zap.c by calling
pthead_atfork(). In zap.c, cs_init() calls pthread_atfork() and
registers cs_init() itself as the child hook handler.

Fix zap.c so that LDMS processes can run as daemons on Ubuntu20.04

---

ldms/src/core/ldms_xprt.c

fix addresses one of the problems in #453

fix ldms_xprt remote memory leak in send_dir_update

---

lib/src/zap/rdma/zap_rdma.c
lib/src/zap/rdma/zap_rdma.h

omnipath evidently does not deliver all completions. This series of commits contain zap_rdma workaround for omnipath and zap_rdma debug log improvements introduced when debugging zap_rdma over omnipath.

zap_rdma omnipath workaround

---

ldms/src/sampler/ldms_jobid.c

The variables being additionally initialized are actually guarded by corresponding
*_is_set bools, but it would take IPA for gcc to notice and prevent the extraneous warning.

fix uninit var messages so Wall/Werror works for ldms_jobid.c

---

lib/src/zap/sock/zap_sock.c

struct sock_msg_read_resp has an alignment hole after 'status'.
This change fixes the information leak to network of that hole (memset)
and the uninitialized dst_ptr space.

fix information leak in sock plugin

---

ldms/src/ldmsd/ldmsd_strgp.c

The cleanup logic iterates through the storage policy tree to close all
stores. It also puts back a storage policy reference, which is
erroneous. It is unnecessary to put the reference back as we only want
to close the stores and not free the storage policies. Moreover, this
could cause a use-after-free if all producer sets associated with a
storage policy have been deleted. The storage policy will be freed when
the cleanup logic puts back the reference, and then the cleanup logic
reaccesses the storage policy to get the next storage policy.

Fix a possible use-after-freed in the cleanup path

---

ldms/src/core/ldms.c
ldms/src/core/ldms_xprt.c

LDMS takes the share_lookup references on RBDs and sets when it responds to a
lookup request. Without this patch, LDMS puts the references back only when
applications call ldms_set_delete(). Thus, LDMS leaks the RBDs and sets that
have been looked-up. The leak also affects LDMSDs when it respond to an ldms_ls
-l request.

Put back the RBD share_lookup reference when disconnected

---

lib/src/ovis_util/test_util.c
lib/src/ovis_util/util.c
lib/src/ovis_util/util.h

also fix leak in test_util.c.
Fixes the lack of proper buf initialization in ovis_join_buf which could also lead to buffer overflow as well as the behavior mismatch.

fix ovis_join_buf to match ovis_join behavior

---

ldms/scripts/examples/conf_csv.2
ldms/scripts/examples/conf_csv.3
ldms/scripts/examples/conf_file_csv.2
ldms/scripts/examples/conf_file_csv.3
ldms/scripts/examples/many.2
ldms/scripts/examples/many.3
ldms/scripts/examples/rabbitkw.2
ldms/scripts/examples/rabbitkw.3
ldms/scripts/examples/rabbitkwl2.3
ldms/scripts/examples/rabbitl2remote.2
ldms/scripts/examples/rabbitl2remote.3
ldms/scripts/examples/rabbitv3.2
ldms/scripts/examples/rabbitv3.3
ldms/scripts/examples/vg_csv.1
ldms/scripts/examples/vg_csv.2
ldms/scripts/examples/vg_csv.3
ldms/scripts/examples/vg_sos.1
ldms/scripts/examples/vg_sos.2
ldms/scripts/examples/vg_sos.3
ldms/scripts/ldms-meminfo.sh.in
ldms/scripts/ldms-py-rename.sh.in
ldms/scripts/ldms-py-subset_test.sh.in
ldms/scripts/ldms-py-syslog.sh.in
ldms/scripts/ldms-py-varset.sh.in
ldms/scripts/ldms_local_opa2test.sh.in
ldms/scripts/slurm-examples/cluster.2
ldms/scripts/slurm-examples/cluster.3

the udata_default attribute no longer exists in v4,
This patch removes it from all test scripts that tried to apply it.

remove unsupported udata_default argument from tests

---

ldms/src/sampler/hello_stream/Makefile.am

Instead of using sampler_base.c in the sources of libhello_stream,
LIBADD libsampler_base.la. This should eliminate the automake warning
about subdir-objects.
Also update the library paths to consistently reference from
$(top_builddir).
Fix #457

In hello_sampler, use libsampler_base rather than sampler_base.c

---

ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_config.c

the ldmsd_msg_logger function:
is not thread safe
is passed to all the plugins that take a log pointer
contains an easily exploitable buffer overrun
is redundant with ldmsd_log.
This patch removes the function and redirects the only caller to ldmsd_log.
It leaves a #define for any client code that might have used it.

remove buggy ldmsd_msg_logger function

---

lib/src/zap/sock/zap_sock.c

The `shutdown()` calls in zap_sock close implementation were
accidentally checked in, making socket connection stayed connected in
the case of bad authentication test (e.g. mismatched keyes or wrong
munge domain) in `ldmsd_auth_ovis_test` and `ldmsd_auth_test` tests in
`ldms-test` repository. Re-introducing the `shutdown()` calls solved the
issue.

Fix zap_sock close() not shutdown

---

.github/workflows/build-test-centos7.yaml
.github/workflows/build-test-ubuntu.yaml

Add another github action step to test build with rdma but without DEBUG
in both CentOS and Ubuntu build test actions.

Add build-with-rdma github action step

---

configure.ac
lib/src/zap/rdma/zap_rdma.c
m4/verbs_enum_check.m4

This patch checks at configure for enums that exist on TOSS3 infiniband/verbs.h but not some mellanox ib library versions and ifdefs them out if they are not all defined. Affects at least ARM platforms.

add config check for new ibv_wc_t* enums

---

ldms/src/core/ldms.c
ldms/src/core/ldms_private.h
ldms/src/core/ldms_xprt.c

The leak occurs when
* there is a race between the ldms_set_delete() path and the disconnected
path (Note that the disconnected path releases the transport lock, takes
the set lock, releases the set lock, and retakes the transport lock),
*the ldms_set_delete() path removes the leak RBD from the transport’s RBD
tree while the disconnected path handles another RBD, and
* LDMS fails to send the SET_DELETE request to the disconnected client,
i.e., zap_send() synchronously fails due to the disconnected connection.
The SET_DELETE context is freed upon the synchronous error.
LDMS releases the share_lookup RBD references either in the disconnected
path or in the SET_DELETE reply handling path. Since LDMS fails to send
the SET_DELETE request to the client, it will not receive the SET_DELETE
reply. …

Fix a share_lookup RBD reference leak in the ldms_set_delete path

---

ldms/src/store/hello_stream/hello_stream_store.c

Otherwise the store fails if the dir exists, even though the dir can be reused.

reset rc if mkdir failed because already exists

---

.github/workflows/build-test-ubuntu.yaml

The workflow had two jobs with the same name, which hid the fact
that the rdma build on the ubuntu docker container was not working.
Fix the name of the rdma job.

Fix build-test-ubuntu.yaml workflow

---

lib/src/zap/ugni/zap_ugni.c

This can cause the I/O thread to spin when the peer
closes the connection.

Remove EAGAIN check when read returns 0 (EOF)

---

ldms/src/core/ldms_xprt.c
lib/src/zap/sock/zap_sock.c

The passive side CONNECT_ERROR path drops an extra reference
that causes the zap_interpose_cb to crash when it de-references
the endpoint.
Also took the connect reference before the call to zap_accept to ensure
that the reference is taken before the callback provided in zap_accept
is called.
The bug is triggered when the remote peer disconnects before the
zap_accept ACCEPT/ACK sequence is completed resulting in a
CONNECT_ERROR event being delivered to ldms_zap_auto_cb

Fix endpoint ref count issue in CONNECT_ERROR path

---

ldms/src/sampler/papi/papi_sampler.c
ldms/src/sampler/slurm/slurm_sampler.c
ldms/src/sampler/spank/slurm_notifier.c

slurm_notifier Spank plugin changes
* Bind "init"/"exit" events to prolog/epilog spank callbacks
* PrologFlags=Alloc will cause prolog events to be delivered
immediately as opposed to at the 1st job step. This is
particularly useful for ```salloc -N x bash``` jobs. 
* At prolog time NTASKS and NNODES is not available and
therefore before the first job step is launched, the
nnodes and ntasks values are zero
* Add "step_init"/"step_exit" events
* These events contain accurate values for ntasks and nnodes
slurm_sampler changes
* Sampler binds job start/end times to the "init"/"exit"
events
* Job step start/end events do not modify the job start
and end times
* Caveats:
* Job task PID are updated at each job step and overwrite
any previous value
* Job size begins at zero at salloc time and is …

Refactor Slurm notifier and sampler event handling

---

configure.ac
m4/ax_check_openssl.m4

The ovis_auth library has a hard dependency on openssl.  Change the configure
script to throw an error if ovis-auth is enabled, but openssl is not found.
Remove the HAVE_SSL variable, which was unused and would currently serve
little purpose.
Fixes #80

Throw an error if auth enabled but openssl not found

---

ldms/src/sampler/papi/papi_sampler.c
ldms/src/sampler/papi/papi_sampler.h
ldms/src/sampler/spank/slurm_notifier.c

These changes move the SUBSCRIBER_DATA field to the step_init event so that each job step can have it's own SUBSCRIBER_DATA value.
The PAPI sampler is updated to support multi-step jobs. Each step in the job has it's own metric set; the set name is constructed with a suffix of <job_id> "." <step_id>.
Both serial and overlapping job steps are supported.

Support for multi-step jobs in PAPI sampler.

---

ldms/src/ldmsd/ldmsd_updtr.c

A push updater does not take any producer set references when it starts.
Putting a producer set reference back when it stops will cause a
use-after-free issue.

Not put back a prd_set reference when the push updater stops

---

ldms/src/ldmsd/ldmsd_prdcr.c

When a stream is added to a producer, the logic checks
if the stream has already been subscribed. The error
path in this duplicate name case free'd the stream in the list
corrupting the data structure.

prdcr_subscribe crashes on duplicate stream name

---

ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldmsd_request.c

The auto-interval information was not included in the updtr_status comand. This change adds a column for this information.

Add the auto interval config to updtr_status command

---

ldms/src/ldmsd/ldmsd.c

Listening on the same port but different interfaces was not allowed due
to the key construction of the listen config object that used only
"XPRT:PORT". This patch fixes the issue by using "XPRT:PORT:HOST" as the
key instead.
With the following config:
```
auth_add name=dom1 plugin=munge
listen  xprt=sock port=10001 host=node-1 auth=dom1
listen  xprt=sock port=10001 host=localhost
load name=meminfo
config name=meminfo component_id=1 instance=node-1/meminfo producer=node-1 perm=0777
start name=meminfo interval=1000000 offset=0
load name=vmstat
config name=vmstat component_id=1 instance=node-1/vmstat producer=node-1 perm=0700
start name=vmstat interval=1000000 offset=0
```
and the following CLI (on node-1):
```
$ ldmsd -c /etc/ldmsd.conf -l /var/log/ldmsd.log -v INFO
```
The `ldms_ls` shows …

Fix `listen` on the same port, different interface

---

ldms/src/ldmsd/ldmsd.h

Change the default authentication reference to `auth_default` so that
users can explicitly specify it in `listen` and `prdcr_add`
configuration commands.

Change the deafult auth reference to "auth_default"

---

ldms/scripts/ldms-static-test.sh.in

Prevent further used of an invalid string after it's been found bad.

improve handling of missing input file

---

ldms/src/core/ldms_xprt.c

`next_rbd` was not set before jumping to `next_1` label. If the first
`rbd` did not have `xprt`, then the loop stopped prematurely (as
`rbd = next_rbd` being NULL). If the first `rbd` had `xprt`, but one of
the other `rbd` did not have `xprt`, `rbd` value would stay the same
since `next_rbd` value won't change and `rbd = next_rbd`. This resulted
either in an inifinite loop (rbd won't be NULL) or a crash (too many
`ref_put()` on the `rbd`).

Fix rbd leak/infinite loop/crash in `ldms_set_delete()`

---

ldms/src/core/ldms_xprt.c
ldms/src/ldmsd/ldmsctl.c
ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/sampler/dstat/dstat.c
ldms/src/sampler/hello_stream/hello_sampler.c
ldms/src/sampler/hweventpapi.c
ldms/src/sampler/procnetdev.c
ldms/src/sampler/rapl.c
lib/src/ovis_util/util.c
lib/src/zap/sock/zap_sock.c
lib/src/zap/test/zap_test_reconnect.c
lib/src/zap/zap.c

This patch addresses warnings, which become errors, found when building
with `CFLAGS='-O2 -Wall -Werror'` on CLE 7.0.UP02 (SuSE 15.1) system.

Address build warnings (errors) when '-O2' is given

---

ldms/src/core/ldms_xprt_auth.c
lib/src/ovis_util/util.c

Secondary group authentication is broken in 4.3.5+. A fairly innocuous looking deduplication of code revealed a bug in the implementation to which we switch. This fixes the bug and cleans up another function that was made redundant in the original patch.

Fix secondary group authentication

---

ldms/src/core/ldms_xprt.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/sampler/dstat/parse_stat.c
ldms/src/store/papi/store_papi.c
ldms/src/store/slurm/store_slurm.c
ldms/src/store/store_sos.c
lib/src/ovis_util/notification.c
lib/src/ovis_util/util.c
lib/src/zap/zap.c

On Cray Linux Environment (CLE) 7.0.UP02, gcc-9 seems to be the
preferred GNU C compiler. When '-O2' is supplied to the CFLAGS,
`-Werror=stringop-truncation` (which is not present in GCC 4.8.5 on
CentOS 7) is also enabled and gives the following warnings in many
places in our source tree (which results in error by `-Werror`):
```
error: ‘strncpy’ specified bound <NUMBER> equals destination size
```
This patch addresses places where the warnings occur, and provides
length checking if necessary.

Resolve `-O2` warnings on `strncpy`

---

.github/workflows/space-check.yaml

The space-checking github action should be executed against pull
requests only.

Only check space on pull request

---

ldms/src/core/ldms_xprt.c

This security enhancement ensures that a connected peer cannot cause the
ldmsd to undertake any action with elevated privilege.

Set the effective uid/gid to the peer's uid/gid

---

ldms/src/ldmsd/ldmsd_prdcr.c

When creating a new producer, ldmsd_auth_find is called to associate
an authentication domain with the connection to the peer. If the domain
does not exist, the create fails, but errno is not set. This change now
sets errno to ENOENT in that case.

Set errno if auth domain cannot be found

---

ldms/src/core/ldms.c

__record_set() grabs the __set_tree_lock using __ldms_set_tree_lock(),
so the code commend is corrected to say that the caller must NOT
be holding the ldms set tree lock when it is called.
__ldms_create_set() uses __record_set(), so likewise the caller must
not be holding the lock.
The lock messages are also updated to say "ldms set tree lock"
rather than just "set tree lock". This is a small attempt to disambiguate
the ldms __set_tree_lock from the ldmsd set_tree_lock. Granted,
it would be a layering violation for ldms to depend on a lock in ldmsd,
but every little bit of disambiguation helps.

Attempt to correct and improve the ldms comments about the set tree lock

---

ldms/python/ldmsd/ldmsd_controller
ldms/src/core/ldms_xprt.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_stream.c
ldms/src/ldmsd/ldmsd_stream.h
ldms/src/ldmsd/test/ldmsd_stream_publish.c
ldms/src/ldmsd/test/ldmsd_stream_subscribe.c

These changes significantly reduce the overhead of publishing
JSON data if that data is being forwarded and not otherwise consumed
at the subscriber.
The publisher is also acknowledged before delivering the data to the
subscribers. This reduces the latency at the producer waiting
for the ACK.

Stream performance improvements

---

lib/src/zap/ugni/zap_ugni.c

zap_ugni moves the endpoint state to CLOSE before going to the switch
cases that determine whether to shut down the socket or not. The bug
causes zap_ugni not to shut down the socket in any case. This results in
applications cannot actively close Zap ugni transports.

Fix a bug in zap_ugni that prevents active close transports

---

ldms/src/ldmsd/ldmsd_request.h

Update the code comments about the ldmsd message
Standard Record Format, and remove the information about
the no longer used String Record Format.

Improve code comments about ldmsd messages

---

ldms/scripts/examples/.canned
ldms/scripts/examples/auto-interval
ldms/scripts/examples/auto-interval.1
ldms/scripts/examples/auto-interval.2
ldms/scripts/examples/auto-interval.3
ldms/scripts/examples/auto-interval.4
ldms/scripts/examples/auto-interval.5

Include test scripts for the "auto_interval" option when updating the aggregator daemons. 
There are 3 sampler daemons with interval hints of 1sec (fast), 5secs (medium), and 10 secs (slow) and two aggregator daemons that aggregate the data at 1 sec and 10 secs, respectively. 
Test scripts have been checked will Valgrind.

Include auto_interval test scripts

---

ldms/src/test/ldms-static-test-bypass.in
ldms/src/test/ldms-static-test-list.sh.in

Added the "tx2mon" and "auto_interval" test cases to ldms-static-test-list.sh so they are tested during "make check" and "make installcheck". 
Since tx2mon is not default "enabled" and the auto-interval test case is under revision in pull request #635 , I've added them in the ldms-static-test-list-bypass file so automake does not fail (and then stop) during the make check process.

Added test cases to static runs list

---

ldms/python/ldmsd/ldmsd_config.py
ldms/python/ldmsd/ldmsd_controller
ldms/python/ldmsd/ldmsd_request.py
ldms/src/core/ldms.c
ldms/src/core/ldms.h
ldms/src/ldmsd/ldmsctl.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_request.h
ldms/src/ldmsd/ldmsd_request_util.c

Create a new configuration directive "metric_sets_default_authz" and
the associated rpc with ID LDMSD_SET_DEFAULT_AUTHZ_REQ.
This directive/rpc allows the default uid, gid, and perms of
metrics sets to be configured. All subsequently created metric sets
will use these default values unless overridden.

Create the metric_sets_default_authz configuration option and rpc

---

configure.ac
ldms/scripts/examples/tx2mon
ldms/scripts/examples/tx2mon.2
ldms/scripts/examples/tx2mon.3
ldms/scripts/examples/tx2mon.4
ldms/scripts/examples/tx2mon.5
ldms/scripts/examples/tx2mon.6
ldms/src/sampler/Makefile.am
ldms/src/sampler/tx2mon/Makefile.am
ldms/src/sampler/tx2mon/Plugin_tx2mon.man
ldms/src/sampler/tx2mon/README.md
ldms/src/sampler/tx2mon/tx2mon.c
ldms/src/sampler/tx2mon/tx2mon.h
ldms/src/sampler/tx2mon/tx2mon_cli.c

Adding a sampler called tx2mon. This sampler is designed to run on Stria because this machine contains the kernel module "tx2mon_kmod" that produces the decoded sysfs files that are used to map to operating region metrics. 
As with the tx2mon utility, the tx2mon sampler reports cpu and system-on-chip information from the node files located in the /sys/bus/platform/devices/tx2mon/[socinfo, node<i>_raw], decodes and provides the metric values of the SoC management controller (MC) operating region, current temperature from sensors and the frequencies and power measurements that is logged by the MC to host memory. 
The tx2mon sampler reports the same units and variables as the tx2mon command-line utility. 
The sampler contains two options where:
1.) User can enable/disable set system metrics …

Implement tx2mon sampler plugin

---

ldms/src/ldmsd/ldmsd.h

Would prefer to convert to deleting these, but folk need to look first.
These two functions stubs date from 2013/2015 and are nowhere implemented.

remove  dead store api

---

ldms/src/sampler/tx2mon/Plugin_tx2mon.man
ldms/src/sampler/tx2mon/tx2mon.c

This records the socket number (cpu_num) in the data set so it doesn't have to be extracted from the set instance name.
Additional nits fixed:
* It adds return checking so that config fails if a metric add fails.
* It fixes an array overrun that happens and is trapped only when compiled in hardened mode
per ARM/rhel7 RPM build defaults (-Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong).
* It converts a lingering printf into a log call.

add cpu_num metric and more error checking to tx2mon

---

ldms/scripts/examples/.canned
ldms/scripts/examples/prolog.store2_createuid
ldms/scripts/examples/uidgidcsv

In this test, files are born user 99 and closed with change to user 199.
This works on centos 7 local file systems.
It may have issues on some NFS implementations. 
To run the test after a make install, chown privilege is needed.
The invocation is:
allowroot=1 ldms-static-test.sh uidgidcsv
The output should show something like an end of:
sleep 5 ...done
-rw-------. 1 nobody nobody 576 Mar 10 09:54 /scratch1/baallan/ann-ovis/ldmstest/uidgidcsv/store/node/uidgidcsv.1615395250
sleep 5 ...done
-rw-------. 1 199 nobody 2131 Mar 10 09:54 /scratch1/baallan/ann-ovis/ldmstest/uidgidcsv/store/clemens-c7/uidgidcsv.1615395250
sleep 1 ...done
logs and data stored under /scratch1/baallan/ann-ovis/ldmstest/uidgidcsv
done

add test of csv store create-time uid/gid

---

ldms/src/ldmsd/ldmsctl.c

The patch (5195ba3) that unifies the code to gather records into a whole
LDMSD message introduced the bug. The patch does not set the value of
the msglen variable in the __handle_cmd(). Resulting in __handle_cmd
always pass 0 as the response message length. The response handlers of
the status commands, e.g., prdcr_status, updtr_status, and
daemon_status, use the value provided by the __handle_cmd() when they
parse the string into a JSON object.

Fix ldmsctl to provide the correct msg length to response handlers

---

ldms/src/core/ldms.c

A streams plugin that is dlclose'd can crash if the
thread is blocked in sleep when the dlclose occurs.

Make the delete_proc thread cancellable

---

ldms/scripts/examples/rollagain
ldms/scripts/examples/rollagain.3
ldms/scripts/examples/rollagain.4
ldms/src/store/store_csv.c
ldms/src/store/store_csv_common.c

this extends to close the improvement from #655 and fixes the related perms on the typeheader file.

csv: fix typeheader create perms and extra close messages

---

ldms/src/store/store_csv.c
ldms/src/store/store_csv_common.c

When altheader=0, the default setting for the store_csv store:
The store_csv code has a bug that results in chown/chmod error
messages every time a file is renamed. A sanitized version of
the error looks like:
DEBUG: store_csv: rename_output: rename(A, B)
ERROR: store_csv: rename_output: unable to chmod(A,660): No such file or directory.
ERROR: store_csv: rename_output: unable to chown(A, <UID>, <GID>: No such file or directory.
DEBUG: store_csv: rename_output: rename(A, B)
It _appears_ that the second redundant rename of "A" to "B" succeeds, even
though the chmod and chown of "A" fail immediately before. However, this is
not the case. In fact only the first rename succeeds as we would expect, and
the error from the second rename is simply ignored. The code comment
explaining the ignored …

store_csv: Repair constant file rename errors

---

ldms/src/core/ldms.h
ldms/src/ldmsd/ldmsd_request.c

The size provided to the `realloc()` call was not the size of the entire
buffer. Instead, the remaining size (`sz`) was given. This caused a
buffer overrun on `ldmsd` (e.g. when processing `thread_stats` request).
This patch corrects the size of the reallocation to be the size of the
entire buffer (`off + sz`).

Fix buffer reallocation in ldmsd_request

---

ldms/python/ldms.pxd
ldms/python/ldms.pyx
ldms/python/ldmsd/ldmsd_controller

When ldmsd_controller exit, ldms_xprt was closed but the Python main
thread did not wait for the DISCONNECTED event. The segmentation fault
happened when zap_thread delivered DISCONNECTED event which took the
Python GIL in the callback path, but the Python GIL was already
destroyed because the Python main thread was exiting. This was supposed
not to happen because ldmsd_controller used Xprt in a blocking mode and
Xprt.close() shall timed-wait for the DICONNECTED event (like it did for
blocking `Xprt.connect()`).
This patch fixes the Cython `Xprt.close()` to timed-wait in the blocking
mode and adds the missing `do_quit()` call in ldmsd_controller in the
case of EOF (Ctrl-D) command loop exit.

Fix occasional SEGEV when ldmsd_controller exited

---

ldms/src/ldmsd/ldmsd_request_util.c

…egnth
ldmsd_msg_gather does not update the request header object's message
length to include the subsequent records' legnths after the first
record. Therefore, the message length may be shorter than the actual
message length. At this time, the bug is asymptotic because no
ldmsd_msg_gather’s callers use the message length. The fix is to prevent
future pitfalls.

Fix ldmsd_msg_gather to set the msg length to the total msg length

---

ldms/src/ldmsd/ldmsd.c
ldms/src/sampler/sampler_base.c

the bug in ldmsd.c causes wild frees to occur in multi-set samplers (any sampler with per-device sets) during ldmsd_set_deregister.
the bug in sampler_base is a forgotten string free in base_del.

separate patches fix two memory misuse bugs

---

ldms/src/ldmsd/ldmsctl.c
ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd_config.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/sampler/appinfo.c
ldms/src/sampler/appinfo_lib/ldms_appinfo.c
ldms/src/sampler/dstat/dstat.c
ldms/src/sampler/dstat/parse_stat.c
ldms/src/sampler/examples/synthetic/synthetic.c
ldms/src/sampler/ibnet/ibnet_data.c
ldms/src/sampler/ldms_jobid.c
ldms/src/sampler/llnl/edac.c
ldms/src/sampler/opa2.c
ldms/src/sampler/sampler_base.c
ldms/src/sampler/shm/shm_util/ldms_shm_index.c
ldms/src/sampler/shm/shm_util/ldms_shm_obj.c
ldms/src/sampler/tx2mon/tx2mon.c
ldms/src/store/store_csv_common.c
ldms/src/store/store_flatfile/store_flatfile.c
ldms/src/store/store_rabbitkw.c
ldms/src/store/store_rabbitv3.c
ldms/src/store/store_sos.c
lib/src/ovis_auth/auth.c
lib/src/ovis_ctrl/ctrl.c
lib/src/ovis_util/olog.c
lib/src/ovis_util/test_util.c
lib/src/ovis_util/util.c
lib/src/ovis_util/util.h

This solves reported issue #670, by switching everywhere to STRERROR macro defined in ovis_util/util.h.

compensate for gnu libc 2.32 removal of sys_errlist and use alternate strerror thread safely

---

ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_request.h
ldms/src/ldmsd/ldmsd_request_util.c

Check config request len rather than trusting discrim implicitly

Check config request length

---

configure.ac
ldms/scripts/examples/procnet
ldms/scripts/examples/procnet.1
ldms/scripts/examples/procnet.2
ldms/src/sampler/Makefile.am
ldms/src/sampler/procnet/Makefile.am
ldms/src/sampler/procnet/Plugin_procnet.man
ldms/src/sampler/procnet/procnet.c

This sampler reports data from /proc/net/dev with a set per port.
It reports all active ports that are not excluded.
It only reports a new set when some metric actually changes, including an update number so that analysis can tell the difference between missing and unchanging data (a sequence gap in 'update' indicates lost data); this has been a frequently requested feature in the past by admins.

add procnet sampler to report per-device network metrics

---

configure.ac

pkg_check_modules has some m4 foo that requires careful handling per comments in pkg.m4. This adds that care.

fix usage of pkg_check_modules

---

ldms/src/core/ldms_auth.c
ldms/src/core/ldms_auth.h
ldms/src/core/ldms_xprt.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_request.h
ldms/src/ldmsd/ldmsd_request_util.c
lib/src/coll/heap.h
lib/src/coll/libmap.c
lib/src/coll/str_map.c
lib/src/coll/str_map.h
lib/src/mmalloc/mmalloc.c
lib/src/mmalloc/mmalloc.h
lib/src/ovis_event/ovis_event.c
lib/src/ovis_event/ovis_event.h
lib/src/ovis_json/ovis_json.c
lib/src/ovis_util/big_dstring.h
lib/src/ovis_util/dstring.c
lib/src/ovis_util/dstring.h
lib/src/ovis_util/util.h
lib/src/zap/sock/zap_sock.c
lib/src/zap/zap.c
lib/src/zap/zap.h

For headered functions with names containing _free, this patch documents
and in some cases adds, the key semantics of free():
do nothing if given a NULL pointer
release resources if given a valid pointer.
Why?
* This allows us to stop using syntax of the sort: if (x) free_operator(x), making for easier to read and write code.
* This prevents data-corrupting random walks through memory that start by
dereferencing a NULL argument in destructor code.
Special cases:
* where assert is in use, assertions are checked after the NULL check,

Adding/documenting free() semantics for various object free functions.

---

ldms/src/ldmsd/ldmsd_auth.c

fixes #670 
This minimalist change fixes a duplicate global trapped as an error by gcc 10.2.
It now matches the cloned extern declarations in ldmsd_prdcr.c ldmsd_strgp.c ldmsd_updtr.c.
A better solution would be to add an ldmsd_config.h defining cfgobj_trees and include it
everywhere needed.

update cfgobj_trees local redeclaration for ldmsd_auth

---

ldms/src/ldmsd/ldmsd_request.c

When LDMS xprt terminated in ldmsd, ldmsd went through the collection
of stream clients to clean up the stream clients associated with the
transport. The collection of clients used `<remote_addr,stream_name>`
for rbt keys. However, on rdma transport, the remote addresses of two
transports from the same remote host got resolved to the same address.
This resulted in premature stream client cleanup due to the address
mixed-up. In addition, on the socket transport, `ldms_xprt_sockaddr()`
call in `stream_xprt_term()` returned ENOTCONN the
`ldms_xprt_sockaddr()` exited immediately, leaking the stream client
and the associated LDMS xprt.
This patch modifies the key to of the stream collections to use
`xprt` pointer instead.
NOTE: This has been tested on rdma and sock transports with GDB to …

Fix ldmsd_request:stream_xprt_term()

---

ldms/src/ldmsd/ldmsd_failover.c
ldms/src/ldmsd/ldmsd_request.c
lib/src/ovis_util/util.c
lib/src/zap/ugni/zap_ugni.c

These two commits fix a memory leak in the streams publish/subscribe paths
and removes uGNI logic that results in a confusing warning when an application
exits.

Final 4.3.7  Cleanup

---

ldms/src/core/ldms_xprt.c
ldms/src/ldmsd/ldmsd_request.c

For an ldmsd message that has no attributes (e.g.
LDMSD_FAILOVER_PEERCFG_REQ message), the flag of the message was
incorrectly set to only EOM instead of `SOM|EOM`. In addition, the
message length would be exactly 4 bytes. This patch addresses the
message length assertion and the message flags to correctly handle the
message with no attributes.

Fix ldmsd message with no attributes

---

ldms/src/sampler/lustre_client/Plugin_lustre_client.man
ldms/src/sampler/lustre_client/lustre_client.c
ldms/src/sampler/lustre_client/lustre_client_general.c

The producer parameter is now used (instead of ignored) as the
prefix of the instance names generated by appending /$llite_name.
This prevents breakage (redundant instance names) during scale testing
with multiple samplers per node. 
If producer is not specified, default of $hostname remains.
Man page updated accordingly.

fixes missing support for instance in lustre_client

---

ldms/src/ldmsd/ldmsd_request.c

Previously, a missing authentication configuration
object was reported as ENOMEM.

Report authentication not found error

---

ldms/src/ldmsd/ldmsd_stream.c

The ldmsd_stream_client_dump allocated a symbol list that was
not being freed.

Free leaked symbol list

---

ldms/src/core/ldms.h
ldms/src/core/ldms_xprt.c
ldms/src/core/ldms_xprt.h
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_stream.c

A [pointer:msg_no] key was being used to match
requests with responses. However, if an ldms transport
were disconnected, and then reconnected, the pointer
could be reused in a subsequent connection resulting
in matching a response with the wrong request. This
change generates a unique uint64_t identifier
that is used as part of the key instead of a pointer
to the transport instance.

Use unique connection identifier in message keys

---

ldms/src/sampler/papi/Makefile.am
ldms/src/sampler/papi/papi_hook.c
ldms/src/sampler/papi/papi_hook.h
ldms/src/sampler/papi/papi_sampler.c
ldms/src/sampler/syspapi/Makefile.am
ldms/src/sampler/syspapi/syspapi_sampler.c

In the case of multi-tenant slurm, ldmsd may receive multiple job
events concurrently, i.e. `slurm` stream data are being delivered from
multiple threads. papi_sampler uses `ldmsd_stream_deliver()` to
notify syspapi about the task init event to pause syspapi, or
no-more-task event to resume syspapi, and resulted in the following
deadlock (found by `papi_store_test` over singularity in `ldms-test`
repository):
```
thr0:                                 thr1:
ldmsd_stream_deliver("slurm")         ldmsd_stream_deliver("slurm")
__find_stream()                       __find_stream()
take s_tree_lock                      wait s_tree_lock
take s->s_lock                        .
release s_tree_lock                   .
cb()                                    take s_tree_lock …
```

Fix papi_sampler/syspapi deadlock on multi-tenant slurm

---

ldms/src/ldmsd/ldmsd_config.c
ldms/src/ldmsd/ldmsd_failover.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_request.h

Without the patch, an LDMSD’s request context key consists of a message
number and a connection ID. The host generates the message number of
to-be-sent requests. In contrast, the peer generates the message number
of received requests. LDMSD has a single tree that contains the contexts
of both sent requests and received requests. The connection IDs in the
request sent to a peer and in the request received from the same peer
will be the same.
Moreover, the message numbers of the two requests could be the same
because the host and the peer generate them. When this happens, we would
see error messages “Duplicate message number …” or “Cannot find the
original request …”.
The patch adds a flag in request context keys to differentiate between
to-be-sent requests and received requests. It …

Fix a key collision problem between sent requests and received requests

---

lib/src/zap/fabric/zap_fabric.c
lib/src/zap/fabric/zap_fabric.h
lib/src/zap/rdma/zap_rdma.c
lib/src/zap/rdma/zap_rdma.h
lib/src/zap/sock/zap_sock.c
lib/src/zap/sock/zap_sock.h
lib/src/zap/ugni/zap_ugni.c
lib/src/zap/ugni/zap_ugni.h

Modify zap close to wait for empty send queue. This is to ensure
that the send operations requested by the application got submitted
to the underlying socket before the socket get destroyed by close().
This patch has been tested with test cases in `ldms-test` repository.

zap close to wait for empty sq

---

ldms/src/ldmsd/ldmsd_config.c

LDMSD does not set the type of LDMS-endpoint configuration transports,
so the type is the configuration file. As a result, the connection ID is
the configuration transport memory address instead of the LDMS transport
ID.

Fix wrong config transport type

---

ldms/src/ldmsd/ldmsd_request_util.c

Using calloc results in bzero'ing max_msg_size
which is 1M of memory on socket transports.

Change calloc to malloc in LDMSD request logic

---

ldms/src/sampler/papi/papi_config.c
ldms/src/sampler/papi/papi_sampler.c

The set reclamation timeout was the same as the expiry
which resulted in keeping sets twice as long in memory.

Shorten the PAPI set reclamation timeout

---

ldms/src/ldmsd/ldmsd_request.c

The ldmsd request validation logic did not handle attribute values with a
length of zero correctly.

ldmsd request validation fix

---

ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_config.c
ldms/src/ldmsd/ldmsd_prdcr.c
ldms/src/ldmsd/ldmsd_request.c

The message tree maintains configuration requests and replies. If a connection were to reset while there were outstanding configuration requests, these context would remain in the tree forever.
I have added the changes recommended by Nichamon. I have tested this at 3 levels of aggregation, but would appreciate any testing that you have.

Cleanup up contexts in msg_tree on disconnect

---

ldms/src/ldmsd/ldmsd_stream.c

ldmsd_stream_publish_file set the message buffer length greater than the
maximum transport message length, which resulted in zap send error when
publish large enough file. This bug failed `ldmsd_stream_test` in
`ldms-test` repository.
`ldmsd_stream_test` requires this patch to succeed.

Fix ldmsd_stream_publish_file (message length violation)

---

ldms/src/ldmsd/test/ldmsd_stream_subscribe.c

ldmsd_stream_subscribe checked the record length. If the record length
was greater than the transport maximum message length, the record needed
data aggregation from multiple messages. The logic to aggregate data was
there, i.e. the program did support record aggregation, and the record
length check logic was deprecated and must be removed to support big
stream.
This patch is required for `ldmsd_stream_test` to succeed.

Remove deprecated rec_len check in ldmsd_stream_subscribe

---

ldms/src/sampler/spank/slurm_notifier.c
lib/src/ovis_json/ovis_json.c

This patch addressed two things that contributed to the issue of missing
'\0' in stream pulish data sent by slurm_notifier.
1) From vsnprintf(3) "... a return value of size or more means that
the output was truncated." Hence, the buffer must be expanded when
`cnt >= space` (not `cnt > space`).
2) JSON buffer `jb->cursor` is the current lenght of the output
string. Since `vsnprintf()` put '\0' when the output is not
truncated, `jb->jbuf[jb->cursor]` is always '\0', and
`jb->cursor+1` is a valid data length that will include '\0' in the
stream data.
This patch is required for slurm-related tests in `ldms-test` (e.g.
`agg_slurm_test`, and `mt-slurm-test`) to succeed.

Fix slurm_notifier stream publish

---

ldms/src/ldmsd/ldmsd_request.c

reqc->xprt’s content is valid under the ldmsd_recv_msg() stack. It could
be garbage in different paths because reqc->xprt is an address in the
stack. The patch compares reqc->key.conn_id with the disconnected xprt’s
conn_id to clean up the request contexts.

Use LDMS xprt’s conn_id in ldmsd_xprt_term() to cleanup msg_tree

---

ldms/src/ldmsd/ldmsd_request.c

stream_republish_cb() takes an LDMS transport's reference but does not
put back. Sampler daemons would leak LDMS transports when it republishes
stream to the aggregator. ldmsd_req_cmd_new() already takes a reference
when it initializes the configuration transport.

Don't take LDMS transport's reference in stream_republish_cb()

---

ldms/src/sampler/rdc_sampler/rdcinfo.c

amd dropped ecc reporting in 4.1, 4.2 rocm.

remove ecc defaults from rdc_sampler

---

ldms/python/ldms.pyx

The `dir` in `dir_cb()` could be NULL when `status` is non-zero.

Fix NULL pointer access in ldms Python dir_cb

---

ldms/src/ldmsd/ldmsd_cfgobj.c

The function calls pthread_mutex_lock() instead of
pthread_mutex_unlock().

Fix a deadlock in ldmsd_cfgobj_del()

---

m4/options.m4

Without this change extraneous /lib can appear in search paths before the build's libdir, causing older installations of ldms to get mixed with the build and fail immediately on symbols or crash later.

exclude default /lib and /lib64 from extra lib search path computed by OPTION_WITH

---

ldms/scripts/examples/app_sampler
ldms/scripts/examples/app_sampler.1
ldms/scripts/examples/app_sampler.2
ldms/scripts/examples/linux_proc_sampler
ldms/scripts/examples/linux_proc_sampler.1
ldms/scripts/examples/linux_proc_sampler.2
ldms/scripts/examples/linux_proc_sampler.3
ldms/src/sampler/app_sampler/Makefile.am
ldms/src/sampler/app_sampler/Plugin_linux_proc_sampler.man
ldms/src/sampler/app_sampler/README.txt
ldms/src/sampler/app_sampler/get_stat_field.c
ldms/src/sampler/app_sampler/linux_proc_sampler.c

This new sampler consumes pids from a stream compatible with it or the app_sampler and supplied by slurm_notifier or netlink-notifier pending in #758.
It has been tested on CTS-1 hardware/toss-3 and centos.
It provides reference tests for app_sampler and linux_proc_sampler driven by ldms-static-test.sh and man page.
It is partially derived (with attribution) from forkstat.
It is disabled by default; configure with '--enable-app-sampler' to test; changing the default to enabled for app_sampler and this would be a good thing but is separable.
It will not pass a build bot test until #761 is merged for json_value_str_str.

Add linux_proc_sampler and related doc derived from app_sampler.

---

configure.ac
ldms/scripts/examples/.canned
ldms/scripts/examples/blob_writer
ldms/scripts/examples/blob_writer.1
ldms/scripts/examples/blob_writer.2
ldms/src/sampler/Makefile.am
ldms/src/sampler/blob_stream/Makefile.am
ldms/src/sampler/blob_stream/Plugin_blob_stream_writer.man
ldms/src/sampler/blob_stream/blob_stream_writer.c

This plugin subscribes to any number of streams and creates a message-indexed
dump of each stream. There is no parsing of the messages, so this is fast.
Converting blobs to any particular database format is left to other tools.
Test/demo script and man page included

Add a stream blob writing plugin.

---

ldms/src/core/ldms.c
ldms/src/core/ldms.h
ldms/src/core/ldms_xprt.c
ldms/src/core/ldms_xprt.h
ldms/src/ldmsd/ldmsd_prdcr.c

Previously, LDMS advertised the set delete event only to peers that has
successfully looked up the set. In the case of quick set add-delete, the
peer will only get DIR ADD event but won't get LDMS set delete
notification because the lookup process has not completed in time. This
patch modifies LDMS so that it advertises set delete event to downstream
LDMS peers so that the peer can undo what it has done from DIR ADD
event.

Advertise LDMS set delete event to peers

---

ldms/man/Plugin_store_csv.man
ldms/src/store/store_csv.c
ldms/src/store/store_csv_common.c
ldms/src/store/store_csv_common.h

The time format used by LDMS in CSV files can be a bit difficult to use in practice. A great many existing tools use milliseconds-since-epoch as an internal or natively understood time format (Kafka, Cassandra, Elasticsearch, etc.). This PR introduces a store_csv option that keeps the current time format as the default, but allows the use of and alternate time format (time_format=1), where:
A value of 1 chooses an alternate format where the first field (Time_msec) is <milliseconds since epoch>, and the
second field (Time_usec) is just the additional <microseconds> since the epoch in excess of the milliseconds since
epoch. In other words, there is no overlap of the values in the first and seconds fields, which is in contrast to the
repetition employed by format 0.

store_csv: Add time_format option

---

ldms/src/ldmsd/Makefile.am
ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_event.c
ldms/src/ldmsd/ldmsd_event.h
lib/src/ovis_ev/ev.c
lib/src/ovis_ev/ev.h
lib/src/ovis_ev/ev_priv.h
lib/src/ovis_ev/evw.c

Logging to the log file becomes a performance bottleneck when a burst of
errors occur, especially on aggregators. We use event-driven programming
to get rid of the log file's lock. The ldmsd_log() function publishes an
event to a worker exclusively responsible for printing data to
the log file or the syslog. Thus, there is only one thread that accesses the log file.

Get rid of the log file lock

---

lib/src/zap/sock/zap_sock.c

This also stops valgrind whining due to the leaked struct padding
in rmsg. rmsg header is 36 bytes on all platforms.

correct zeroing the header to prevent network leak of data.

---

ldms/src/ldmsd/ldmsd.c

Log level was checked in `ldmsd_log()`. However, the true logging
function was `__ldmsd_log()`, and other convenient logging functions
(e.g. `ldmsd_linfo()`) call `__ldmsd_log()` directly without checking
the log level. This results in convenient functions such as
`ldmsd_linfo()` to be able to log messages even though the log level is
set to be higher (e.g. ERROR). This patch moved the log level checking
into `__ldmsd_log()` to solve the issue.

Fix log level checking bug

---

.github/workflows/4.3.3-compat-test.yaml
ldms/src/auth/ldms_auth_munge.c
ldms/src/core/ldms_xprt.c
ldms/src/core/ldms_xprt.h

Also add compatibility test with munge authentication in github actions since the patch touches `ldms_auth_munge.c`

Fix ldms_xprt_sockaddr() calls to not assume ipv4 addresses

---

ldms/src/core/ldms_xprt.c

When the ldms consumer (e.g. ldms_ls or agg) updated the looked-up set
before the producer (e.g. sampler) sampled a new data since previous
update, the consumer side won't get update complete callback at all.
What happened was that the zap_read completion was delivered but the
logic in ldms xprt detected that the data was old and didn't call update
complete. This patch modified the code to call the update callback in
the case of receiving the old data.

Fix ldms update never completed bug

---

ldms/scripts/examples/conf_csv.1
ldms/scripts/examples/conf_csv.2
ldms/scripts/examples/conf_csv.3

This adds enabling the milli format on some of the existing csv tests and shifts the test sampling offsets so that millis other than 0 are visible.
OVIS-4 with recent changes from @morrone works correctly with this test.

update csv test to include milli format

---

lib/src/zap/ugni/zap_ugni.c

`z_ugni_sock_recv()` did not handle the case that `read()` returns 0
(peer close) when receiving the first message on socket to setup the
GNI connection.

Fix zap_ugni disconnection handling while receiving a socket message

---

lib/src/zap/ugni/zap_ugni.c
lib/src/zap/ugni/zap_ugni.h

NOTE: This passed `ldms-test/scalability` with ugni transport on
voltrino:
- 160 sampler daemons spread among 16 compute nodes
- 16 sets per sampler daemon
- 2560 sets total
- 4 L1 aggregators spread between 2 nodes
- each take 1/4 of the sampler daemons
- 2 L2 aggregators on one compute nodes
- each take 1/2 of the L1 daemons
- 1 L3 aggregator with SOS

zap_ugni - remove endpoint-per-thread limitation

---

ldms/scripts/Makefile.am

The build system rightly complains about a circular build dependency:
make[3]: Circular lsdate <- lsdate dependency dropped.
make[3]: Circular ovis-roll-over.py <- ovis-roll-over.py dependency dropped.
Remove the manually created lsdate and ovis-roll-over.py targets
in favor of the normal listings in bin_SCRIPTS and EXTRA_DIST.

Remove circular build dependency

---

ldms/python/ldmsd/ldmsd_request.py

Fix bug where creation of a python LDMSD_Req_Attr object with "AUTH" attribute will fail

Add AUTH attribute to ID_NAME_MAP dict

---

ldms/examples/cmdline-opts/agg_cmdline_opts.conf
ldms/examples/cmdline-opts/sampler_cmdline_opts.conf
ldms/man/ldmsd.man
ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_config.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_request.h
ldms/src/ldmsd/ldmsd_request_util.c

To specify a cmd-line option in a configuration file, use the command
'option'. For example,
option l=/var/log/ldmsd.log v=INFO
option m=2gb
A configuration file example is at ldms/examples/cmdline-opts/ldmsd_w_cmdline_opts.conf.

Support LDMSD cmd-line options in configuration files

---

ldms/scripts/examples/procinterrupts

newer kernels produce  a huge amount of interrupt information.

expanding memory for procinterrupts sampler test

---

ldms/src/sampler/dcgm_sampler/dcgm_sampler.c
ldms/src/sampler/lustre_client/lustre_client_general.c
ldms/src/sampler/lustre_mdt/lustre_mdt_general.c
ldms/src/sampler/lustre_mdt/lustre_mdt_job_stats.c
ldms/src/sampler/lustre_ost/lustre_ost_general.c
ldms/src/sampler/lustre_ost/lustre_ost_job_stats.c
ldms/src/sampler/papi/papi_sampler.c
ldms/src/sampler/slurm/slurm_sampler.c

Add missing ldmsd_set_deregister() calls to several samplers, as mentioned in issue #860.
Additionally, add the missing ldms_set_unpublish() call to the slurm_sampler and add both ldmsd_set_register() and ldmsd_set_unregister() calls to the dcgm_sampler.

Add missing ldmsd_set_deregister() calls, plus other minor fixes

---

ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_updtr.c

fixes ldmsd_request.c uninit variable that can lead to allocation failure and incomplete input validation that can lead to updtr start failure. The commits are split by topic.
in the updtr case, user can specify an invalid offset while defaulting the interval, so the half-range validation is needed in two places.

fix validations of interval/offset on updtr_start and uninit count leading to arbitrarily large calloc

---

ldms/src/ldmsd/ldmsd_request.c

Without this change, LDMSD skips any ‘env’ commands preceding the priority
commands (option, listen, auth_add, and verbose) in a configuration file, so
name substitution in the priority commands results in an empty string. The
patch that supports the command-line options in configuration files (commit
001fb2 in PR826) introduced the bug.
Fixes #863

Make the 'env' command as a priority command

---

ldms/src/sampler/ibnet/ibnet_data.c

the ibnet sampler developed before register/deregister needs updating.
this patch updates it.

add register/deregister for ibnet sets so hints should populate

---

ldms/src/sampler/dcgm_sampler/dcgm_sampler.c
ldms/src/sampler/ibmad_sampler/ibmad_sampler.c

The new plugin names for ibmad and dcgm are ibmad_sampler
and dcgm_sampler, respectively. Symlinks to the previous
names still exist for the old names to aid transition.
Unfortunately, the API makes it such that only one of these
name (practically speaking) can have working metric
set hints. This can be addressed in the future in a new
plugin API.
We make the plugins report the same name as the new
plugin file name. The plugins probably aren't in too
wide use yet, so we err on the side of making this
work for future users.

Change ibmad and dcgm sampler names to match new file name

---

ldms/src/sampler/app_sampler/linux_proc_sampler.c

good to provide admins a clue about which file failed.

add log message for open failure of config file in linux_proc_sampler.

---

ldms/src/sampler/rdc_sampler/Makefile.am

working on reporting the issue upstream. With this patch, the sampler builds and works.

update build to support rocm 4.5 rdc device headers on gcc4-gcc8

---

util/sample_init_scripts/genders/man/ldms-attributes.man
util/sample_init_scripts/genders/man/ldmsd-genders.man
util/sample_init_scripts/genders/src/ldmsctl_args3.cxx
util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/ldms-functions.in

-A must be included in the command line when an auth_ovis conf or auth_munge socket option is included in the configuration and the default instance name must be overridden if instance is included in the user-defined configuration.

fix bugs in  auth arg  and instance name handling for genders-based configuration

---

ldms/src/core/ldms.c

The commit fbf21b7 made __destroy_set_no_lock() to reset the set handle
in all transport contexts in the transport's list to NULL, including the
contexts that point to other sets. It breaks the link between the
transport and the other sets. A result is that the transport won't put
back the other sets' references when destroying corresponding contexts.

Make __destroy_set_no_lock() only reset contexts related to the set

---

ldms/src/core/ldms.c
ldms/src/core/ldms_xprt.c

When the set update completed with "inconsistent" state, the heap is in
an invalid state and should not be accessed.
In particular, consider the case of `SAMP -> AGG_L1 -> ldms_ls`. SAMP
has a sampler that uses `LDMS_V_LIST`. AGG_L1 has finished looking up
the set from SAMP, and is in the middle of updating it. At this point,
the metadata on AGG_L1 has been populated, but the data+heap parts are
still uninitialized. In the mean time, `ldms_ls` lookup + update the set
and get SIGABRT from `ldms_heap_get()` due to bad heap signature because
of the uninitialized data+heap part on the AGG_L1 that `ldms_ls` copied
the data from.
This patch:
- adds set consistency check before getting the heap in the LDMS set
update path.
- adds heap pointer check in the `ldms_list_first()` list/heap access.

Fix SIGABRT due to invalid heap access

---

util/sample_init_scripts/genders/src/Makefile.am

This fixes makefile.am insufficiency when boost is not installed with prefix /usr. Affects only the c++ genders config file processor.

fix build for boost-dependence when not in /usr

---

.github/workflows/create-release.yaml
.github/workflows/test-make-dist.yaml

Update the create-release.yaml and test-make-dist.yaml workflows
to use the same runs-on (Ubuntu-20.04) and container
(ovishpc/ovis-ubuntu-build) as used elsewhere. Keeping these two
files in sync should help to avoid surprise problems at release
time.

Update workflows to use the current runs-on and containers

---

lib/src/zap/zap.c
lib/src/zap/zap_priv.h

When a passive endpoint was assigned to a thread that has an active
endpoint with high activity, the routine of the passive endpoint (e.g.
accepting a connection) could be starved. The routines of the passive
endpoints are quite light-weighted. So, this patch assigns the passive
endpoints into its own thread to avoid the starvation.

Addressing passive zap endpoint thread starvation

---

ldms/src/ldmsd/ldmsd.c

Fix error where ldmsd hardcodes error to ENOMEM if
ldmsd_listen_new fails to create listen object

Bug fix for ldmsd_listen_new error handling

---

ldms/src/sampler/tx2mon/Plugin_tx2mon.man
ldms/src/sampler/tx2mon/tx2mon.c

This adds support for globally loading tx2mon sampler on mixed node-type systems.
Produces no sets or errors unless hardware type is aarch64.

update tx2mon to run (noop) without errors on non-tx2

---

ldms/scripts/ldms-static-test.sh.in
ldms/scripts/pll-ldms-static-test.sh.in

this fixes two test drivers that reference share/doc/ovis-ldms that were overlooked in fixing the build files to install under ovis-ldms instead of ovis-ldms-version

fix lingering references to share/doc/ovis-ldms-VERSION

---

lib/src/zap/sock/zap_sock.c
lib/src/zap/sock/zap_sock.h

`zap_sock` IO entries were kept in the `free_q` so that it can be used
immediately for the next IO alloc. This patch `free()` the IO entries
instead of keeping it around.

Do not keep unused zap sock IO entries

---

ldms/src/ldmsd/ldmsd_request.c

The `include path=FILE` ldmsd config command was supposed to be in the
priority command list so that it is processed in the first scan.

Fix `include` ldmsd config command

---

ldms/src/sampler/examples/test_sampler/test_sampler.c

Fix the bug that `__strtok()` tokenizer in `test_sampler` did not return
the last token. Also add a note to clarify why we cannot use
`strtok()` or `strtok_r()`.

Fix `test_sampler` string tokenizer

---

ldms/src/store/kokkos_appmon/kokkos_appmon.c

The stream recv handler in kokkos_appmon was taking a
lock in the callback path that could deadlock with the
config downcall path.

Remove the cfg_lock from the callback path

---

ldms/src/ldmsd/ldms_ls.c

This patch addresses 2 issues with `ldms_ls -lu` print format:
1. Missing a " " after udata print, making the udata output globbed
together with the metric data.
2. When metric `udata` is 0, the format `"%#"PRIx64` ("%#lx") does not
print '0x0'. It instead printed just single '0'.
This patch explicitly print the prefix '0x' follows by plain hex print
format without the prefix and a space ( `"0x%" PRIx64 " "` ).

Fix udata formatting in ldms_ls

---

ldms/scripts/examples/.canned
ldms/scripts/examples/ibmad_sampler
ldms/scripts/examples/ibmad_sampler.1
ldms/scripts/examples/ibmad_sampler.2
ldms/scripts/examples/ibmad_sampler.3
ldms/src/sampler/ibmad_sampler/Plugin_ibmad_sampler.man
ldms/src/sampler/ibmad_sampler/ibmad_sampler.c

Updated man page and added check driver.
The include/exclude options allow admins to indicate ports of interest
and prevent queries at every sample which generate nuisance log messages
from mad libraries.
The rate option allows admins to suppress redundant data when desired.
The producer option is now used to set the producer metadata.
The rate computation now returns -1 when the rate computed is
invalid for any reason; this permits plots of the rate metrics
to work with standard tools which may otherwise detect large
spurious values that mis-scale the plot axis.

Add include/exclude/rate options, fix producer and rate computations

---

ldms/src/core/ldms.c

The %lld results in a warning on some systems. Convert to
the portable PRIu64 format specifier.

Fix printf format warning for %lld

---

ldms/src/core/ldms.c

This patch addresses the following issues:
- The flags of records in the array of records were not initialized
properly.
- The flag check condition in `ldms_record_card()` contained a
typological error (the `&&` logical-and operation should be `&`
bitwise-and operation).

Fix ldms record flag bugs

---

ldms/python/ldms.pyx

Return DirSet info dict key:values formatted as strings, rather than byte strings

Format byte strings when returning DirSet info

---

ldms/src/sampler/examples/test_sampler/Makefile.am
ldms/src/sampler/examples/test_sampler/test_sampler.c

With the change, the test_sampler plugin can be configured to publish
stream data periodically from a file to a specific client. The feature
can be used in testing to simulate an LDMSD's component that publishes
stream data to a client.

Extend the test_sampler plugin to be able to publish stream periodically

---

ldms/python/ldmsd/ldmsd_controller

With the patch, users can give a single config command at the command line.
--cmd <cfg> is a new ldmsd_controller's command-line option. For example,
ldmsd_controller -x <xprt> -p <port> -h <host> --cmd 'prdcr_status'
ldmsd_controller -x <xprt> -p <port> -h <host> --cmd 'prdcr_start name=node0001'

Make ldmsd_controller receive a single config command at the cmd-line

---

ldms/src/sampler/lustre_client/lustre_client.c
ldms/src/sampler/lustre_mdt/Makefile.am
ldms/src/sampler/lustre_mdt/Plugin_lustre_mdt.man
ldms/src/sampler/lustre_mdt/lustre_mdt.c
ldms/src/sampler/lustre_mdt/lustre_mdt_general.c
ldms/src/sampler/lustre_mdt/lustre_mdt_general.h
ldms/src/sampler/lustre_ost/Makefile.am
ldms/src/sampler/lustre_ost/Plugin_lustre_ost.man
ldms/src/sampler/lustre_ost/lustre_ost.c
ldms/src/sampler/lustre_ost/lustre_ost_general.c
ldms/src/sampler/lustre_ost/lustre_ost_general.h

reduced log level to 'debug' for checks of the top directory
that will be missing when each lustre service is off (an expected condition
in some deployments).
added component_id and producer option processing from attributes
for consistency with other plugins and updated man pages.
for mdt,ost which do not run on compute nodes, leaving out jobid metric.

fix compid, producer, log level in lustre dynamic plugins

---

ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd_failover.c
ldms/test/failover-simple/agg1.sh
ldms/test/failover-simple/agg2.sh

- Enforce `-n <OUR_NAME>` and `failover_config peer_name=<PEER_NAME>`
- Terminate LDMSD if there is no listening transport

Fix ldmsd name issues & terminate ldmsd if no listening xprt

---

ldms/src/ldmsd/ldmsd_request.c

The patch fixes the attribute length. Without the patch, the client
cannot unpack the set_route response.

Fix the set_route response handler

---

ldms/src/ldmsd/ldms_ls.c

this eliminates the usage dump where it is inappropriate (when error is not usage syntax) and names the offending unknown option character when it is detected.

fix: make ldms_ls error messages more useful & less verbose

---

ldms/src/ldmsd/ldmsd_request.c

calculated by taking the frequency of updater set intervals in seconds
multiplied by the data size of a set
Example Response:
Name                 Count
-------------------- ----------------
active_count                        6
deleting_count                      0
mem_total_kb                      512
mem_free_kb                       478
mem_used_kb                        34
set_load                         3000

add 'set_load' to set_stats response

---

ldms/src/core/ldms_xprt.c

ldms_ls (and maybe agg?) induces a memory leak in the dir reply json management. 
now freeing the unfreed field set_data[i].digest_str

fix process_dir_reply memory leak

---

ldms/src/sampler/dcgm_sampler/dcgm_sampler.c
ldms/src/sampler/ibmad_sampler/ibmad_sampler.c
ldms/src/sampler/jobid_helper.c
ldms/src/sampler/jobid_helper.h
ldms/src/sampler/lustre_client/lustre_client.c

This documents jobid_helper.h and fixes an 'N_samplers -1' string leak in jobid_helper.c, and fixes related call sites.
Also fixes an immmediately adjacent unchecked return code from comp_id_helper_config.

Fix memory leak, missing doc, missing err handling

---

ldms/src/core/ldms.c

This fixes some recent additions/refactorings where
EINVAL returns need negation.

fix missing - on errno values from metric add calls

---

ldms/src/sampler/filesingle/ldms-sensors-config
ldms/src/sampler/filesingle/ldms-sensors-config.man

updates utility script to optionally suppress - in the labels/names published by the kernel.

add option to suppress - in output of ldms-sensors-config

---

lib/src/ovis_json/Makefile.am
lib/src/ovis_json/input/ovis_json_perf_test.sh
lib/src/ovis_json/ovis_json_perf_test.c

The overhead for using jbuf to assemble json messages in darshan (relative to sprintf) is roughly 3.7. At high message rates this matters, so I'm adding a benchmark we can investigate and monitor for performance improvement or regression.
The benchmark runs with a message during 'make installcheck'

add performance benchmark of jbuf operation

---

lib/src/ovis_json/ovis_json.c
lib/src/ovis_json/ovis_json.h

A jbuf_t maintains an internal cursor that is advanced as data is
appended to the buffer. The jbuf_reset interface resets this cursor
pointer to zero so that the buffer can be reused avoiding the overhead
of jbuf_new() and jbuf_free() for each jbuf record.

Add the jbuf_reset interface

---

configure.ac
ldms/src/contrib/sampler/Makefile.am
ldms/src/contrib/sampler/gpu_metrics_sampler/Makefile.am
ldms/src/contrib/sampler/gpu_metrics_sampler/gather_gpu_metrics.cpp
ldms/src/contrib/sampler/gpu_metrics_sampler/gather_gpu_metrics_from_one_api.c
ldms/src/contrib/sampler/gpu_metrics_sampler/gather_gpu_metrics_from_one_api.h
ldms/src/contrib/sampler/gpu_metrics_sampler/gmg_common_util.c
ldms/src/contrib/sampler/gpu_metrics_sampler/gmg_common_util.h
ldms/src/contrib/sampler/gpu_metrics_sampler/gmg_ldms_util.c
ldms/src/contrib/sampler/gpu_metrics_sampler/gmg_ldms_util.h
ldms/src/contrib/sampler/gpu_metrics_sampler/gmg_log.c
ldms/src/contrib/sampler/gpu_metrics_sampler/gmg_log.h
ldms/src/contrib/sampler/gpu_metrics_sampler/gpu_metrics_ldms_sampler.c

This is an LDMS GPU metrics sampler built over the Intel OneAPI.  OneAPI can be used to sample GPU metrics.  In our testing, we mitigated the risk of resource leaks using the following strategy:
* Klocwork scan.
* Valgrind was used during functional testing of the primary business logic.
* We also track the outstanding malloc allocations by the sampler, and the sampler code will write any suspected leak to the sampler log.
Signed-off-by: sindhuja <sindhuja.gajula@intel.com>

[FEAT] ldms gpu metrics sampler

---

lib/src/zap/sock/zap_sock.c

We can arrive in sock_read() when the endpoint is in the ZAP_EP_CLOSE
state if the EPOLLIN events arrived between the endpoint state changing
to ZAP_EP_CLOSE and the connection shutdown, so we should not call
assert().

Not calling assert() in zap_sock:sock_read() in the ZAP_EP_CLOSE case

---

configure.ac
ldms/scripts/examples/.canned
ldms/scripts/examples/lustre_mdc
ldms/scripts/examples/lustre_mdc.1
ldms/scripts/examples/lustre_mdc.2
ldms/scripts/examples/lustre_mdc.3
ldms/src/sampler/Makefile.am
ldms/src/sampler/lustre_mdc/Makefile.am
ldms/src/sampler/lustre_mdc/NOTES
ldms/src/sampler/lustre_mdc/Plugin_lustre_mdc.man
ldms/src/sampler/lustre_mdc/lustre_mdc.c
ldms/src/sampler/lustre_mdc/lustre_mdc.h
ldms/src/sampler/lustre_mdc/lustre_mdc_general.c
ldms/src/sampler/lustre_mdc/lustre_mdc_general.h

Includes jobid and set perm support, basic test script.
The sampler can run without root access if timing data is excluded.
The mdc timing stats can be suppressed optionally.

add lustre_mdc (client side metadata perf) sampler

---

ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_strgp.c

A storage policy maps to a set schema and assumes all sets of the same schema
have the same metric list. If this is not true, due to misconfiguration or
multiple architectures on the system, LDMSD may crash when it tries to store
sets.
With the patch, LDMSD logs a message when it finds a set that has a different
schema digest from its storage policy's cached digest. Also, LDMSD does not
store such sets. In another word, LDMSD will store sets that a storage policy
has cached its digest.

Enable logging for legacy stores where a set schema has different definitions

---

ldms/src/ldmsd/ldmsd_strgp.c

The digest mismatch logging was introduced in the legacy store path to
report mismatch sets (5a58428). However, the change introduced a bug
that a strgp always calls `store->open()` interface regardless of
`decomposition` or `legacy` strgp. This patch fixed the issue, putting
the digest checking / reporting logic inside the case of the legacy
store.

Fix strgp decomposition bug introduced by digest logging

---

configure.ac
ldms/src/contrib/sampler/geopm_sampler/README.md
ldms/src/contrib/sampler/geopm_sampler/ldms_geopm_sampler.c
ldms/src/contrib/sampler/geopm_sampler/ldms_geopm_sampler.h
ldms/src/contrib/sampler/geopm_sampler/ldms_geopm_sampler_test.c
ldms/src/contrib/sampler/geopm_sampler/ldms_geopm_sampler_test.expect

- Add call to geopm_pio_reset in the term() callback
- Update source build instructions to point to v2.0.0~rc2
- Note v2.0.0~rc1 does not have the geopm_pio_reset() api
- Add check for new api geopm_pio_reset() to the configure script
Signed-off-by: Christopher M. Cantalupo <christopher.m.cantalupo@intel.com>

Enable clean restart of the GEOPM LDMS Sampler

---

.github/workflows/4.3.3-compat-test.yaml
ldms/etc/Makefile.am
ldms/etc/init.d/Makefile.am
ldms/etc/logrotate.d/Makefile.am
ldms/etc/systemd/Makefile.am
lib/etc/ld.so.conf.d/Makefile.am
lib/etc/ovis/Makefile.am
util/sample_init_scripts/README

This does not remove the --enable-etc option. Since docdir is unconditionally writable during build, it is not necessary to have the option. I can remove the option (always write opt/etc example into docdir) if wanted as an additional patch.

move direct installs to /etc into $(docdir)/sample_init_scripts/opt

---

ldms/src/core/ldms.c
ldms/src/core/ldms.h
ldms/src/test/test_ldms_set_new.c

The patch fixes the bug that ldms_set_new_custon() accesses the set
after __record_set() returns NULL.

Fix ldms_set_new_custom() that accesses a NULL pointer

---

ldms/src/ldmsd/test/ldmsd_stream_publish.c

ldmsd_stream_publish when invoked with incomplete/incorrect options can use a null ldms stream pointer.

fix missing error check & init to prevent uninit pointer use

---

ldms/src/decomp/as_is/decomp_as_is.c

It looks like an uninit temporary rec_mid was used where a lookup based on context is needed.

fix rec_mid uninit/misuse

---

ldms/src/ldmsd/test/ldmsd_stream_publish.c

The pull request #979 prevents users from using ldmsd_stream_publish
with the -f option. To be precise, it causes ldmsd_stream_publish to
always return an error if one of the -n, -N, and -l options is not
given. The patch fixes the problem.

Fix ldmsd_stream_publish's bug caused by #979

---

ldms/python/ldmsd/ldmsd_util.py

ldmsd_controller uses `ldmsd_util.py` which used `find_executable()`
from the deprecated Python package `distutils`. This patch replaces
`find_executable()` with the equivalent `shutil.which()` call.

Fix distutils deprecation in ldmsd_controller (Ubuntu 22.04)

---

.github/workflows/4.3.3-compat-test.yaml
configure.ac
lib/etc/ld.so.conf.d/Makefile.am
lib/etc/ovis/Makefile.am

PR #985 relocated ${PREFIX}/etc to a much deeper location
${PREFIX}/share/doc/ovis-ldms/sample_init_scripts/opt/etc. This may be
fine for example startup scripts (for init.d and systemd), but is
extremely inconvenient for ENV files like
${PREFIX}/etc/profile.d/set-ovis-variables.sh and
${PREFIX}/etc/ld.so.conf.d/ovis-ld-so.conf.  The relocation also broke
tests that use these two files to setup OVIS environment.
This patch partially reverts #985 by installing
${PREFIX}/etc/profile.d/set-ovis-variables.sh and
${PREFIX}/etc/ld.so.conf.d/ovis-ld-so.conf. To prevent installing these
files into "/etc", the installation is guarded by the sysconfdir
checking condition, i.e. if "$(sysconfdir)" is "/etc", they won't be
installed.

Install ${PREFIX}/etc but not /etc

---

ldms/python/ldms.pyx

When ldms xprt connect/listen failed synchronously, the caller must drop
the xprt and don't ever touch it again. The Xprt object held the C xprt
after connect/listen synchronous failure, making it proned to
Xprt.close() by the Python application (e.g. maestro) which subsequently
incorrectly called `ldms_xprt_close()` on the C xprt that lead to a
segmentation fault. This patch modifies the ldms.pyx Xprt.connect() and
Xprt.listen() to properly handle the connect/listen synchronous error.

Fix ldms.pyx Xprt connect/listen synchronous error handling

---

ldms/src/auth/ldms_auth_munge.c

Munge authentication checking must be performed after the context has
been set. Otherwise, we will always check against the default settings
and ignore the options specified by users.

Fix munge auth check

---

lib/src/ovis_util/util.h

gcc 7.2 fails on a C-allowed cast with use of STRERROR in fprintf from c++ code (kokkos). This patch makes the C cast explicit.

add cast in STRERROR macro to keep c++ happy.

---

ldms/src/ldmsd/test/Makefile.am
ldms/src/ldmsd/test/ldmsd_stream_subscribe.c
ldms/src/ldmsd/test/ldmsd_stream_subscribe.man

This adds a man page and options so that ldmsd_stream_subscribe can be used as a testing tool  with -D for those other than root.
The daemon(0,0) command causes -D to fail for non-root users; the options below allow the users to adjust the args.
-R,--daemon-noroot suppresses the 'cd /' part of the daemon command.
-i,--daemon-io suppresses the closing of IO channels at the fork so messages go to the terminal while the daemonized process continues
For other debugging/use purposes, the -E,--events-raw suppresses the generation of the EVENT:{} wrapper around messages (which may not be json), but does add the carriage return after each message logged.

add man page and usability options to ldmsd_stream_subscribe

---

ldms/man/Plugin_store_csv.man
ldms/man/Plugin_store_function_csv.man
ldms/scripts/examples/rollemptycsv
ldms/scripts/examples/rollemptycsv.2
ldms/scripts/examples/rollemptycsv.3
ldms/src/store/store_csv.c
ldms/src/store/store_function_csv.c
ldms/src/store/stream/Plugin_stream_csv_store.man
ldms/src/store/stream/stream_csv_store.c

rolling empty files periodically is an inode-wasting thing to do.
this stops it for store_csv, store_function_csv and the stream csv store.

suppress rollover of empty csv files

---

config/config.rpath
configure.ac
m4/lib-ld.m4
m4/lib-link.m4
m4/lib-prefix.m4

These are the latest files from gnulib. This seems to resolve an issue with the AC_LIB_HAVE_LINKFLAGS() macro that we are seeing in PR #1000.

Update config.rpath and lib-*.m4 files with latest from gnulib.

---

ldms/src/sampler/examples/test_sampler/test_sampler.c

`add_schema` config command of `test_sampler` can specify either an explicit list of metrics or `num_metrics` (just the number of metrics). In the latter case, the `num_metrics` variable in the code was not set to the value given by the user. It was uninitialized. This made the sampler miscalculated the required memory size and stomp on others' memory (e.g.  corrupting malloc chunks).

Fix test_sampler config add_schema num_metrics

---

ldms/src/core/ldms_private.h
ldms/src/core/ldms_xprt.c

__ldms_format_set_meta_as_json has an assumption of a lock on the set,
but one of the call paths to __ldms_format_set_meta_as_json was missing
that lock. ldmsd_set_register (descendants) and ldms_transaction_end are
some of the other sites using it.

fixes #957 race on __ldms_format_set_meta_as_json

---

ldms/man/ldmsd_controller.man
ldms/python/ldmsd/ldmsd_controller

changes -h (or --help) to -? or --help to remedy collision with our -h host common syntax.

add -x -p -h args so ldmsd_controller options are like others

---

ldms/src/ldmsd/ldmsd.c

vasprintf needs freeing in the early error case. this is otherwise handle by log_actor after init.

fix missing free before logger starts.

---

ldms/src/sampler/procstat/procstat.c

base_del() already frees `schema`. Calling ldms_schema_delete(g.schema) frees the already freed schema.

Fix procstat.c that doubled frees g.schema

---

configure.ac
ldms/src/contrib/sampler/Makefile.am
ldms/src/contrib/sampler/variorum_sampler/Makefile.am
ldms/src/contrib/sampler/variorum_sampler/Plugin_variorum_sampler.man
ldms/src/contrib/sampler/variorum_sampler/README.md
ldms/src/contrib/sampler/variorum_sampler/variorum_sampler.c

This pull request introduces a vendor-neutral power monitoring plugin that reports node, CPU (socket), memory and GPU power using LLNL's Variorum library (https://variorum.readthedocs.io/).

Variorum LDMS Plugin for vendor-neutral power management

---

ldms/src/core/ldms.c
ldms/src/core/ldms_xprt.c

When a set delete timeout has reached, delete_proc() does not destroy the set that one of its push or lookup peer is connected. This prevents the race between delete_proc() and the SET_DELETE reply from the client.

Not destroy deleting sets that a client has reference on it

---

ldms/src/ldmsd/ldmsd_prdcr.c

Improve the debugging utility of the prdcr_connect_cb message; seeing the auth name makes it a lot easier to notice if it is not what you expect.

add auth name to prdcr_connect_cb log message

---

ldms/src/core/ldms_xprt.c

Before the change, the if-statement uses the bitwise-AND to check whether the authentication has been approved. However, the flags are enumerated. The change makes ldms_xprt forwarding the send_complete events to applications only when the auth flag is equal to LDMS_XPRT_AUTH_APPROVED.

Fix the auth_flag if-statement when ldms_xprt receives a send_complete

---

ldms/src/sampler/slurm/slurm_sampler.c

The extra job slots are buffers of complete jobs, so aggregators will get updates on the job complete status before they get replaced by new jobs.

Double the number of job slots from the given value in slurm_sampler

---

README.md

Instead of full test log, the README.md badge links to the test report summary in the test report repository (simple passed/failed by test cases). Each test case in the summary list will link to the log for the particular test case.

README.md badge click to test summary

---

ldms/src/ldmsd/ldmsd_request_util.c

The bug is that ldmsd_parse_config_str() appends the terminating attribute to the request only when there are other attributes.
The patch makes the functions to always append the terminating attribute.

Fix a bug introduced by PR 1039

---

configure.ac
ldms/src/sampler/Makefile.am
ldms/src/sampler/ibmad_records_sampler/Makefile.am
ldms/src/sampler/ibmad_records_sampler/Plugin_ibmad_records_sampler.man
ldms/src/sampler/ibmad_records_sampler/ibmad_records_sampler.c

Implement the ibmad_records_sampler plugin. Versus the ibmad_sampler, the major change is that we use a single list of records per ib interface rather than a metric set per ib interfaces.
There are a number of other changes and cleanups that fell out of that change. For instance, we can fully use the sampler_base code now that we only have a single metric set.

Ibmad records sampler

---

ldms/src/core/ldms.c
ldms/src/core/ldms.h

The examples explicitly show the units parameter of ldms_record_metric_add() being NULL, but there are no tests for NULL, which allows for segfaults. We add tests before using the usage and name pointers.

Test for NULL in ldms_record_metric_add()

---

configure.ac
ldms/src/sampler/Makefile.am
ldms/src/sampler/slingshot_info/Makefile.am
ldms/src/sampler/slingshot_info/Plugin_slingshot_info.man
ldms/src/sampler/slingshot_info/slingshot_info.c
ldms/src/sampler/slingshot_metrics/Makefile.am
ldms/src/sampler/slingshot_metrics/Plugin_slingshot_metrics.man
ldms/src/sampler/slingshot_metrics/slingshot_metrics.c

Introduce two sampler plugins for slingshot NICs: slibgshot_metrics and slingshot_info. The former is intended for high-frequency detailed counters, and the latter for lower-frequency general information.

Slingshot samplers

---

ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldmsd_request.c
lib/src/zap/rdma/zap_rdma.c
lib/src/zap/sock/zap_sock.c
lib/src/zap/ugni/zap_ugni.c
lib/src/zap/zap.c
lib/src/zap/zap.h
lib/src/zap/zap_priv.h

For example:
```sh
$ ldmsd_controller --port 10000 --host cygnus-06-iw --xprt rdma
Welcome to the LDMSD control processor
rdma:cygnus-06-iw:10000> thread_stats
Name             Samples      Sample Rate  Utilization  Send Queue Size  Num of EPs
---------------- ------------ ------------ ------------ ---------------- ------------
zap_rdma_io                64         2.33         0.03                0            4
zap_rdma_io                76         2.75         0.03                0            4
zap_rdma_io                74         2.68         0.04                0            5
zap_rdma_io                56         2.02         0.03                0            4
zap_rdma_io                 1         0.04         0.00                0            1
rdma:cygnus-06-iw:10000>
```
This has …

Add sq_sz and n_eps to zap thread stat

---

lib/src/zap/rdma/zap_rdma.c
lib/src/zap/sock/zap_sock.c
lib/src/zap/ugni/zap_ugni.c

Check the zap thread before manipulating endpoint-thread statistics.

Fix SIGSEGV due to NULL zap thread

---

ldms/python/ldmsd/ldmsd_request.py
ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_request.h

Add configuration counter that increments when a ldmsd successfully completes a configuration request
Config counter only increments for requests that modify the current configuration of the ldmsd

LDMSD configuration counter

---

ldms/src/sampler/blob_stream/blob_stream_writer.c

the leak fixed is a path name leaked once per stream configured.

Fix missing free on a config string for blob_stream_writer.

---

ldms/man/Makefile.am
ldms/scripts/examples/app_sampler
ldms/scripts/examples/blob_writer
ldms/scripts/examples/linux_proc_sampler
ldms/src/sampler/app_sampler/Makefile.am
ldms/src/sampler/app_sampler/Plugin_app_sampler.man
ldms/src/sampler/app_sampler/Plugin_linux_proc_sampler.man
ldms/src/sampler/app_sampler/app_sampler.c
ldms/src/sampler/app_sampler/linux_proc_sampler.c
ldms/src/sampler/netlink/ldms-notify.service
ldms/src/sampler/netlink/netlink-notifier.c
ldms/src/sampler/netlink/netlink-notifier.man

This adds the ability to optionally collect names corresponding to uid and gid values, enabling analyses based on user or group name.
The library call(s) to lookup username/groupname are not repeated so long as the paired uid/gid value does not change.

add user and group names options for status_uid/gid

---

ldms/src/sampler/ibmad_records_sampler/Plugin_ibmad_records_sampler.man
ldms/src/sampler/ibmad_records_sampler/ibmad_records_sampler.c

We came across a system where there are RoCE devices on a node. Those device show up in the umad device listing, but connections to the devices for sampling always fail. Also, the device lookup seems to be especially long on that system, and my suspicion is that the RoCE device(s) may be to blame there as well.
First, we add a check to skip over device ports with a link_layer that is no InfiniBand (the RoCE ones where link_layer Ethernet).
Next we add a refresh_interval_sec configuration option so we can refresh the list of available devices on a longer interval so we can avoid the high cost of device lookup on most sampling intervals.

Updates for ibmad_records_sampler

---

ldms/src/sampler/netlink/Makefile.am

The installcheck scirpt `test_slps.sh` hanged in github workflow for Ubuntu-20.04, causing the `distcheck` workflow to fail after 6 hours. This is a work around so that we can move forward while the plugin authors figuring out the cause.

Remove `installcheck-local` in netlink/Makefile.am

---

ldms/src/core/ldms.c
ldms/src/core/ldms_private.h
ldms/src/core/ldms_xprt.c

The lookup error path will call ldms_set_delete which in turn will call ldms_xprt_set_delete which informs downstream aggregators of the deleted set. However, in the error path the downstream peer has never received a dir_add because the set was never published. This results in the downstream reporting an error that a dir_delete was received for a set that was never added.
It also fixes the case where the set is created in the local tree, but an error occurs in the RDMA of the meta data into the local set. In this case, the set was not being removed from the set tree which would cause all subsequent lookup requests to fail synchronously because the set was already present in the tree.

Refactor the lookup error path

---

ldms/python/ldmsd/ldmsd_config.py
ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldmsd_request.c

Users can do 'updtr_status reset=true' in ldmsd_controller to reset the updaters' counters.
The descriptions of the updaters' counters are provided in the command help. Do 'help updtr_status' in ldmsd_controller to see the descriptions.

Add the capability to reset the updater's counters thru updtr_status

---

ldms/src/ldmsd/ldmsd_stream.c

The deadlock occurs when applications publishes data on the same stream multiple times by calling ldmsd_stream_publish().

Fix a possible deadlock caused by ldmsd_stream_publish()

---

ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_stream.c

- Remove a possible race between forwarding the stream_status request to the connected producer and receiving the response back. The race could cause LDMSD to free the forwarding request context before LDMSD receives all the responses.

Fix prdcr_stream_status's handler

---

ldms/src/core/ldms_xprt.c

When the caller provides '*' wild card address to
`ldms_xprt_listen_by_name()`, the expected behavior is to listen to all addresses (0.0.0.0). However, because the AI_PASSIVE has not been specified in the `ai_flags` hint, '*' is resolved to `127.0.0.1` instead of `0.0.0.0`. This patch specified `AI_PASSIVE` in `hint.ai_flags` to fix the issue.

Fix `ldms_xprt_listen_by_name()` for wildcard address

---

ldms/src/ldmsd/ldmsd_request.c

A number of error pathways in ldmsd_request lead to free(wild) or return wild;. This fixes the ones gcc -Wall finds.

fix wild pointer and wild rc values in ldmsd_request.c

---

ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_strgp.c

Without the patch, whenever LDMSD receives a term request for a store plugin, the store plugin's resources will be freed, and the plugin will be unloaded. LDMSD will, then, segfault if the store links to a running storage policy.

Take a store plugin's reference when ldmsd links it to a strgp

---

ldms/src/core/ldms.c
ldms/src/core/ldms.h

This change adds a function, ldms_list_last(), that returns the tail of a list.

Add ldms_list_tail API

---

ldms/src/core/ldms.c
ldms/src/core/ldms.h
ldms/src/core/ldms_core.h

The LDMS_V_TIMESTAMP was added as part of the
decomposition support, but the accessor functions
were never added.

Add LDMS_V_TIMESTAMP accessor functions

---

lib/src/ovis_log/ovis_log.c
lib/src/ovis_log/ovis_log.h

Changed the name to more accurately represent that the purpose of this function is to register a new subsystem with the logger.

Change ovis_log_create to ovis_log_register

---

ldms/python/ldmsd/ldmsd_controller

- Fix an error message in do_prdcr_start()
- Remove the error code in the message from do_plugn_load(). The error code may be -1 if LDMSD fails to load the plugin library. It is not meaningful to report -1. The message sent from LDMSD contains the reason.

Fix error messages in ldmsd_controller

---

ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldmsd_request.c

Add True/False parameter 'thread_stats' to daemon_status to optionally return the daemon's thread statistics in daemon_status response. This reduces the request load for users only seeking the daemon's status

thread_stats parameter for daemon_status

---

ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller

recv_timeout sets the timeout for a receive_response request.
recv_timeout can be manually set on instantiation of Communicator class, otherwise defaults to 5 seconds.
If ldmsd_controller is called in debug mode, receive_response becomes blocking.

Add class variable recv_timeout to Communicator class

---

ldms/src/sampler/lustre_mdc/Plugin_lustre_mdc.man
ldms/src/sampler/lustre_mdc/lustre_mdc.c
ldms/src/sampler/lustre_mdc/lustre_mdc_general.c
ldms/src/sampler/lustre_mdc/lustre_mdc_general.h

This commit:
- changes the incorrectly typed (u64) metrics to s64 to match the lustre code producing them (schema change). 
- removes the "-mdc-$hexaddr" suffix from the "mdc" field; the hex part previously varied from node to node and made the "mdc" field useless as an index.
- adds the option (default enabled) that if rollover to negative values occurs the sampler resets the counters. The time (epoch seconds) of the most recent reset is reported in the "last_reset metric". If auto_reset=0 disables the reset process, a single log message occurs should the need for a reset occur.

update metric types to signed for lustre_mdc sampler

---

ldms/src/decomp/as_is/decomp_as_is.c

This has been tested with 1 sampler damon - 1 aggregator daemon with the following config:
- *samp.conf*
```conf
env HOST=$(hostname)
listen xprt=sock port=10000
load name=meminfo
config name=meminfo instance=${HOST}/meminfo producer=${HOST}
start name=meminfo interval=2000000 offset=0
load name=vmstat
config name=vmstat instance=${HOST}/vmstat producer=${HOST}
start name=vmstat interval=2000000 offset=0
```
- *agg.conf*
```conf
listen xprt=sock port=10001
load name=store_csv
config name=store_csv path=store buffer=0
prdcr_add name=local host=localhost xprt=sock port=10000 type=active interval=2000000
prdcr_start name=local
strgp_add name=any plugin=store_csv container=any regex=.* decomposition=decomp.json
strgp_start name=any
updtr_add name=all interval=2000000 offset=100000 …
```

Fix `as_is` decomposition SEGV when there are no indices

---

ldms/src/store/avro_kafka/Plugin_avro_kafka_store.man
ldms/src/store/avro_kafka/store_avro_kafka.c

As it turns out serdes_new() frees the associated
configuration context. Freeing again in close()
resulted in a double free. This fixes issue #1146.

Fix double free of serdes_conf in Avro-Kafka store

---

ldms/src/core/ldms.c
ldms/src/ldmsd/ldmsd_prdcr.c

The logic in the set delete path notified subscribers of set deletion prior to adding the set to the delete tree. This could cause the set delete callback path to remove a set from the tree that had not yet been added; corrupting the tree.

Fix race between delete thread and xprt set delete

---

ldms/scripts/examples/linux_proc_sampler
ldms/src/sampler/app_sampler/get_stat_field.c
ldms/src/sampler/app_sampler/linux_proc_sampler.c
ldms/src/sampler/netlink/Makefile.am
ldms/src/sampler/netlink/ldms-netlink-notifier.man
ldms/src/sampler/netlink/ldms-notify.man
ldms/src/sampler/netlink/ldms-notify.service
ldms/src/sampler/netlink/netlink-notifier.c
ldms/src/sampler/netlink/netlink-notifier.man
util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/ldms-functions.in

Fix bugs, man pages, and options so that linux_proc_sampler +  ( spank and/or netlink pid publisher) works with pushing metric sets.
key bugs fixed:
- uptime was not initialized in computation of process start times.
- netlink messages could not be used for dashboarding process events (lacking node name)
- corner case hit at scale lead to sampler not deleting some sets ( this is not the same as #1141) .
- push sets needed genders-generated updtr to enable auto_interval for all other sets to be correct.
- man page for ldms-notify hard to find for admin.

Netlink toss changes

---

ldms/src/sampler/spank/Plugin_slurm_notifier.man
ldms/src/sampler/spank/slurm_notifier.c

The output of the slurm notifier DEBUG2 macro is visible in user log files. This is not desired in normal operation. This patch adds the 'user_debug' option to the spank plugin to enable user's job log output when the slurm admin is debugging use of the plugin and to route these DEBUG2 messages to slurm_debug2() otherwise.

add user_debug option to control user job logging of plugin handling messages in slurm_notifier

---

ldms/src/ldmsd/ldmsd_decomp.c

It appears that logical types must be declared as a nested type in avro.

Correct timestamp-millis in avro schema

---

ldms/src/store/avro_kafka/Makefile.am
ldms/src/store/avro_kafka/Plugin_store_avro_kafka.man

Give the store_avro_kafka man page the correct name (also corrected internally in the man page).
Also include the man page in the dist.

Avro kafka man page fixes

---

ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_decomp.c
ldms/src/store/avro_kafka/Plugin_store_avro_kafka.man
ldms/src/store/avro_kafka/store_avro_kafka.c

These changes fix issues with store_avro_kafka that result from the fact the LDMS metric and schema names support many characters that are considered invalid by Avro. 
This change fixes #1136 as well as complaints about how container= is handled by the store.
@morrone, could you please try these out? It fixes the issue(s) for me.

Avro name mapping

---

ldms/src/ldmsd/ldmsd_decomp.c

This change adds logicalTypes support for unsigned values when mapping from LDMS to Avro/Kafka.

Logical types

---

ldms/src/sampler/procnetdev2/Makefile.am

Include procnetdev2 man page, and clean up Makefile.am
The "if ENABLE_PROCNETDEV" conditional is redundant. It is handled one level up.

Include procnetdev2 man page, and clean up Makefile.am

---

lib/src/zap/zap.c

Threads were unconditionally being created even when there were idle zap_io_threads available.

Reap unused Zap threads

---

ldms/scripts/examples/blob_writer
ldms/scripts/examples/blob_writer.2
ldms/src/sampler/blob_stream/Plugin_blob_stream_writer.man
ldms/src/sampler/blob_stream/blob_stream_writer.c

this also updates the usage string for previously added arguments and simplifies repetitive cleanup code.

add spool-on-close option to simplify db ingest from blob_stream_writer

---

.github/workflows/4.3.3-compat-test.yaml
.github/workflows/build-ddebug-centos7.yaml
.github/workflows/build-test-centos7.yaml
.github/workflows/build-test-ubuntu-22.04.yaml
.github/workflows/build-test-ubuntu.yaml
.github/workflows/create-release.yaml
.github/workflows/ldms-test-build.yaml
.github/workflows/space-check.yaml
.github/workflows/test-make-dist.yaml

Github actions are warning about:
>Create Release
>Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/create-release@v1, >actions/upload-release-asset@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Updating to newer versions of actions/checkout and actions/upload-artifact help with that.
Also, we replace actions/upload-release-asset with softprops/action-gh-release. Github has abandoned work on actions/upload-release-asset, and softprops/actions-gh-release is one of the suggested replacements. It seems to do what we need.

Update GitHub workflows

---

configure.ac
lib/src/zap/Makefile.am
lib/src/zap/fabric/Makefile.am
m4/options.m4

`--with-libfabric` was only looking for the library in `PREFIX/lib`.
This patch removed `--enable-fabric` and use `--with-fabric` that check
for the library/header by default.

libfabric build fix

---

configure.ac

missing $ caused explicit --disable-Feature to be ignored in several cases. This adds the $ back where they belong.

fix slingshot, opa2, infiniband, ibnet am_conditionals

---

configure.ac
ldms/src/sampler/rdc_sampler/Makefile.am

In ROCM 5.5.0, rdc.h has been fixed so that it compiles under gcc. As a result we can drop our hack to fix rdc.h on the fly during the build.
NOTE: This will require anyone using librdc_bootstrap to have ROCM 5.5.0 or later.
The ROCM source tree has seen movement towards a more standardized structure, so also convert to using the AC_LIB_HAVE_LINKFLAGS macro. If ROCM is not installed in the standard search path, the path to librdc_bootstrap can be specified with a single
--with-librdc_boostrap-prefix option. For instance:
./configure --enable-rdc --with-librdc_bootstrap-prefix=/opt/rocm-5.5.0

rdc_sampler: Remove rdc.h hack, change configure options

---

ldms/src/ldmsd/ldmsd_decomp.c

Check for null before comparing dictionary value type.
Missing "type" attribute in decomposition json file will cause ldmsd to crash with segfault

Check for null val in __jdict_str

---

ldms/src/store/store_csv.c

The commit_rows() function for decomposition did not increment the row count. This effectively disabled roll-over when using decomposition with the CSV store.

Increment row count in store_csv commit_rows

---

ldms/src/contrib/sampler/daos/Makefile.am
ldms/src/contrib/sampler/daos/daos.c
ldms/src/contrib/sampler/daos/pool_target.c
ldms/src/contrib/sampler/daos/pool_target.h
ldms/src/contrib/sampler/daos/rank_target.c
ldms/src/contrib/sampler/daos/rank_target.h

Also embeds the relevant schema name in the instance for
better organization, and removes the system name as it's
not organizationally-useful.
Signed-off-by: Michael MacDonald <mjmac.macdonald@intel.com>

Update DAOS sampler for new producer/component details

---

ldms/src/core/ldms.c
ldms/src/core/ldms.h
ldms/src/core/ldms_core.h

- Add an API that returns an LDMS schema name given the ldms_schema_t structure.
- Remove unnecessary x-digit code that is part of libc in ctype.h
- Fix bug in LDMS_V_RECORD_ARRAY logic that miscalculates offset of next metric
- Tweak record and record-array documentation

Add ldms_schema_name_get API

---

ldms/src/core/ldms_xprt.c
ldms/src/ldmsd/ldmsd_request.c

- If a set is not being updated, the set_stats command will get a divide by zero error
- The lookup error path may assert if a lookup completes for a set already present in the set tree.

Fix stats calc and lookup error path

---

ldms/man/ldmsctl.man
ldms/man/ldmsd_controller.man
ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldmsctl.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_request_util.c

The loglevel command works, but it is being deprecated. It will be removed, eventually.

Add the log_level cmd as a replacement of the loglevel command

---

.github/workflows/4.3.3-compat-test.yaml
ldms/man/ldms_auth_munge.man
ldms/src/auth/ldms_auth_munge.c
ldms/src/auth/ldms_auth_naive.c
ldms/src/auth/ldms_auth_ovis.c

Change munge error message to info
The munge authentication message consists of the
local and remote addresses of the transport between
the two peers. This message presumes that both peers see
the same addresses (albeit swapped). This assumption is
false in many routed and NAT'd environments.
This change replaces the error with an informational message
so that administrators will be aware of this difference
and can make a determination whether or not this difference
is expected.

Change munge authentication message

---

ldms/python/ldmsd/ldmsd_communicator.py

'credits' and 'rail' are optional attributes in prdcr_add command. They were accidentally listed under the required attribute list.

Fix 'credits' and 'rail' optional attributes in ldmsd_controller prdcr_add

---

ldms/man/ldmsctl.man
ldms/man/ldmsd_controller.man
ldms/python/ldmsd/ldmsd_communicator.py
ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd_prdcr.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_updtr.c
lib/src/ovis_util/util.c
lib/src/ovis_util/util.h

The patch makes LDMSD support time-interval strings. A time-interval string is an integer followed by a unit string. A unit string is one of the followings:
us -- microseconds
ms -- milliseconds
s  -- seconds
min -- minutes
hr  -- hours
day -- days
For example, with this patch, to specify a sampling interval of 1 second, '1s' can be used.

Make LDMSD support interval strings

---

ldms/src/core/ldms_stream.c

The error arose from 'ldms_stream_client_stat_str()' on the ldmsd side.
When the stream client list was empty, 'ldms_stream_client_stat_str()' returned `NULL` with errno=ENOENT. This consequently got forwarded to `ldmsd_controller` and displayed as an error.
This patch modified ldms_stream_client_stat_str() to return "[]" on empty client list.

Fix 'ldms_stream_client_stats_str() error: 2' in ldmsd_controller

---

ldms/src/ldmsd/ldmsd_plugattr.c
ldms/src/ldmsd/ldmsd_plugattr.h

The patch is to fix build problems of stand-alone application in the project that uses the library.

Make ldmsd_plugattr report log messages to the application's default log

---

ldms/src/sampler/json/Plugin_json_stream_sampler.man
ldms/src/sampler/json/json_stream_sampler.c

This change adds the uid and gid from the stream
event to the JSON stream metric set.

Add stream meta data to JSON stream metric set

---

ldms/src/ldmsd/test/ldmsd_stream_subscribe.c

Multiple threads in `ldmsd_stream_subscribe` can race to handle stream recv events. The recv handler called `msglog()` multiple times to print out the EVENT. This lead to intermingled events in the output. This patch modifies the handler to print the events in single msglog call to avoid the intermingled output.

Fix ldmsd_stream_subscribe intermingled events output

---

ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_config.c
ldms/src/ldmsd/ldmsd_request.c

- dump_cfg exports the command-line options, e.g., the log path and verbosity
- Make dump_cfg support plugins that allow multiple config command lines
- Make dump_cfg export the regex instead of schema at strgp_add if regex was originally given.

Improve dump_cfg

---

ldms/src/store/avro_kafka/store_avro_kafka.c

@morrone could you please test this out on your system to see if it resolves the memory leak issue?

Fix error path memory leaks in avro_kafka

---

ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller

Ensure rx_rate argument is a string before instantiating LDMSD_Req_Attr object

Convert rx_rate parameter argument to string in prdcr_subscribe

---

ldms/src/store/avro_kafka/store_avro_kafka.c

Call the avro_value_iface_decref() that should follow avro_generic_value_new().
Some code is refactored to allow the call to be clean and the code more symmetric.
Fixes #1275

Fix memory leak in store_avro_kakfa

---

.github/workflows/ldms-test-build.yaml
m4/options.m4

Since git v2.30.3, git added a top-level directory ownership check
(please see https://github.com/git/git/commit/8959555ce). If the owner
of the top-level directory does not match the current user, all git
commands failed with message "fatal: detected dubious ownership in
repository at _PATH_". However, our configure script does not properly
report the error nor give a recommended action. The configure script
silently moving on with 'NO_GIT_SHA' value.
This patch modify the configure script to check the git command if we
are in a git repository. If the git command resulted in an error, the
configure script report the error messages from the git command and
exited with a failure status. Please note that if the source tree is not
in a git repository (no .git directory), the configure scirpt …

Fix configure script GIT SHA issue

---

ldms/python/ldms.pxd
ldms/python/ldms.pyx
ldms/src/core/ldms_stream.c

This pull request includes
- `ldms_stream_close()` race fix
- Python `ldms.Xprt.stream_unscribe()` GIL deadlock fix
- Exporting `ovis_log_set_level_by_name()` to Python ldms for debugging / verification purpose.
The following is the description of the `ldms_stream_close()` race: 
Stream-Client-Entry (sce) is a tailq entry that lives in
`stream->client_tq` (list of clients subscribing the stream) and
`client->stream_tq` (list of streams the client subscribed to) to
manage client-stream relation. When a stream client closes, it is
unbound from the stream, and the `sce` is removed from the list. This
leads to a use-after-free when another thread iterate through the
`stream->client_tq` and unlock to call the application callback
function. This patch modifies the unbind procedure to NOT remove …

ldms_stream_close race fix

---

ldms/src/core/ldms_stream.c

The `ldms_stream_close()` race fix (3fe7765a) changed the condition of the stream-client entry (sce) such that it can contain NULL client or stream. The stream stats code path that also go through the list must also been modified to support it.

Fix segmentation fault in stream stats

---

ldms/src/ldmsd/ldmsd_strgp.c

If the `strgp` uses decomposition, it does not `open()` the store and hence does not have `store_handle` to `flush()`. The strgp with decomposition should not call `flush()` store interface.

Fix possible unintentional `flush()` call in decomposition

---

m4/cython_check.m4

This patch addresses 2 things:
1) Add `cython{$python_major_version}` (e.g. 'cython3') into the
cython program check list. Let's suppose the Python version is 3.6,
the current check list only contains 'cython-3.6', 'cython3.6', and
'cython'. This caused an issue on Ubuntu 22.04 since the cython
package installed the program as 'cython3'.
2) Fix the version checking logic when CYTHON configure variable is
specified (e.g.  './configure CYTHON=/opt/cython/bin/cython3').
The existing CYTHON_CHECK macro uses 'AC_PATH_PROGS_FEATURE_CHECK'
macro on CYTHON variable, which will skip the 'feature-test' part of
the macro if the variable (CYTHON) is defined. Since the version
checking logic is in the 'feature-test' part, the cython version has
never been checked and 'cython not found' error is …

Fix CYTHON_CHECK m4 macro

---

ldms/scripts/examples/.canned
ldms/scripts/examples/dcgm1
ldms/scripts/examples/dcgm1.1
ldms/scripts/examples/dcgm1.2
ldms/src/sampler/dcgm_sampler/Makefile.am
ldms/src/sampler/dcgm_sampler/Plugin_dcgm_sampler.man
ldms/src/sampler/dcgm_sampler/dcgm_sampler.c
ldms/src/sampler/dcgm_sampler/gen-ldms-dcgm-list-fields

* enables compid, perms, uid/gid, etc, with default the original behavior
* provide demo/test of dcgm
* provide configuration support utility listing fields available and numbers
* fix omissions in ldms_sampler_base man page

add use_base to dcgm sampler to ovis-4

---

ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldmsd_request.c

The patch makes the update_time_stats command reports the skipped and oversampled counters. Previously, updtr_status reports the counters.

Move the results of the skipped and oversampled counters

---

lib/src/zap/fabric/zap_fabric.c
lib/src/zap/rdma/zap_rdma.c
lib/src/zap/sock/zap_sock.c
lib/src/zap/ugni/zap_ugni.c
lib/src/zap/zap.c
lib/src/zap/zap_priv.h

The patch separates the process of reducing the number of Zap endpoints associated with an IO thread from the process of releasing the endpoint from the IO thread. Additionally, it defers the nullification of `zap->thread` until the endpoint reference reaches zero.
`zap_sock` and `zap_ugni` need to remove their events from epoll before delivering the disconnected event to applications, preventing the reception of additional epoll events. However, without this patch, this results in resetting `zap->thread` to NULL. Thus, the applications cannot retrive Zap thread information in the disconnected path. The patch addresses this limitation.

Modify the releasing Zap endpoints from IO thread process

---

ldms/src/sampler/netlink/Makefile.am
ldms/src/sampler/netlink/input/test_slps.sh
ldms/src/sampler/netlink/simple_lps.c

this installcheck version checks the return code and wraps test_slps in 'timeout' so it cannot hang forever, should a transport hang occur.
also
fixes #1095
This is the rc branch version of  #1145, which is still being worked on.

this installcheck version checks the return code and wraps test_slps

---

lib/src/zap/sock/zap_sock.c

`zap_sock` forgot to put the reference corresponding to `zap_new()` when the application `zap_reject()` the endpoint of the incoming connection request. This resulted in endpoint resource leakage (e.g. file descriptor). This patch put back the reference (calling `zap_free()`) in reject call.

Fix `zap_sock` rejected endpoint leak (on 4.4.1)

---

ldms/src/sampler/dcgm_sampler/dcgm_sampler.c

Use correct ldms function to add string metrics.
Add error messages.

dcgm_sampler: fix handling of DCGM string fields

---

ldms/src/ldmsd/ldmsd.c

when logging is via syslog, flush must not be called. Calling syslog is achieved by assigning log_fp a sentinel value which can never be a file pointer and checking for it before calls that expect a file pointer. This patch fixes a missing check before an fflush that was introduced with the new logging infrastructure.

fix segfault caused by attempting to flush syslog

---

lib/src/ovis_log/ovis_log.c

ovis_log_flush can be called in any order wrt initialization, so it must be guarded against null and syslog values. This prevents segfault in fflush.

protect ovis_log_flush from invalid arguments.

---

m4/cython_check.m4

This patch addresses 2 things:
1) Add `cython{$python_major_version}` (e.g. 'cython3') into the
cython program check list. Let's suppose the Python version is 3.6,
the current check list only contains 'cython-3.6', 'cython3.6', and
'cython'. This caused an issue on Ubuntu 22.04 since the cython
package installed the program as 'cython3'.
2) Fix the version checking logic when CYTHON configure variable is
specified (e.g.  './configure CYTHON=/opt/cython/bin/cython3').
The existing CYTHON_CHECK macro uses 'AC_PATH_PROGS_FEATURE_CHECK'
macro on CYTHON variable, which will skip the 'feature-test' part of
the macro if the variable (CYTHON) is defined. Since the version
checking logic is in the 'feature-test' part, the cython version has
never been checked and 'cython not found' error is …

Fix CYTHON_CHECK m4 macro (4.4.2 backport)

---

configure.ac
ldms/src/sampler/Makefile.am
ldms/src/sampler/zfs_leafvdevs/Makefile.am
ldms/src/sampler/zfs_leafvdevs/Plugin_zfs_leafvdevs.man
ldms/src/sampler/zfs_leafvdevs/zfs_leafvdevs.c
ldms/src/sampler/zfs_topvdevs/Makefile.am
ldms/src/sampler/zfs_topvdevs/Plugin_zfs_topvdevs.man
ldms/src/sampler/zfs_topvdevs/zfs_topvdevs.c
ldms/src/sampler/zfs_zpool/Makefile.am
ldms/src/sampler/zfs_zpool/Plugin_zfs_zpool.man
ldms/src/sampler/zfs_zpool/zfs_zpool.c

Added 3 plugins for ZFS:
1) zfs_topvdevs
2) zfs_leafvdevs
3) zfs_zpool

ZFS LDMS samplers from LLNL

---

ldms/src/auth/ldms_auth_munge.c
ldms/src/core/ldms_xprt.c

`ldms_xprt_listen_by_name()` listened to 0.0.0.0 IPv4 address by default if `host` is `NULL`. This patch made
`ldms_xprt_listen_by_name()` to fully rely on `getaddrinfo()` in resolving the addresses, and then we pick the first IPv6 address. If no IPv6 addresses available, the first address returned by `getaddrinfo()` is used.
This has been tested with `ldmsd` on IPv4-only machine, and IPv4+6 machine.
On IPv4+6 machine, if the users only to listen on IPv4 addresses, they have to either provide listening address on the CLI (e.g. `-x sock:411:0.0.0.0`), or specify the host in config file (e.g. `listen port=411 xprt=sock host=0.0.0.0`).

Make `ldms_xprt_listen_by_name()` prefers IPv6.

---

ldms/scripts/examples/dcgm1
ldms/scripts/examples/dcgm1.1
ldms/scripts/examples/dcgm1.2
ldms/src/sampler/dcgm_sampler/Makefile.am
ldms/src/sampler/dcgm_sampler/Plugin_dcgm_sampler.man
ldms/src/sampler/dcgm_sampler/dcgm_sampler.c

An integration test demonstrating use and optionally valgrind-cleanliness is also supplied.
'ldms-static-test.sh dcgm_sampler'
Unlike the previous attempt, this version does not:
- add the pthread code to prevent term/sample/config collisions.
- use an extra use_base variable where the base pointer itself will do. 
- add an extra program to dump the available metric and their numbers.

Add dcgm option to use sampler base and add help string.

---

configure.ac
ldms/src/sampler/slingshot_metrics/slingshot_metrics.c

libcxi.h fails to include cassini_cntr_desc.h, which is almost certainly a bug in their header include tree. We include it explicitly until they fix things.

slingshot_metrics: new header include needed by shs-2.1.0

---

ldms/src/ldmsd/ldmsd_decomp.c
ldms/src/store/avro_kafka/store_avro_kafka.c

This pair of patches allows avro schema evolution in a kafka registry. It required two changes:
1. Add avro "default" values to each field in a schema
2. Always generate the avro schema and attempt to push it to the kafka registry (because it may be newer than what is in the registry).

Support avro schema evolution

---

lib/src/ovis_json/ovis_json.c

Any time the jbuf string grows, the head of the jbuf must be accounted for. This patch fixes that oversight. The oversight leads to writing past the end of the string after it is expanded. Any code publishing large messages assembled with jbuf_t is subject to memory corruption if it writes in the last 16 bytes of the space believed to be available when they in fact aren't.
cherry picked for top of tree from https://github.com/ovis-hpc/ovis/commit/40ebe9b7eaac64b2de632892922068b6965a5b90

fix mis-sizing of string in jbuf implementation

---

ldms/src/core/ldms.c
ldms/src/core/ldms_xprt.c
ldms/src/decomp/as_is/decomp_as_is.c
ldms/src/ldmsd/ldmsd_request.c
lib/src/zap/zap.c

These changes fix issue found during v4.4.2 testing. The first commit fixes an issue with outstanding update requests occurring with concurrent incoming LDMS_SET_DELETE notifications. The second commit removes memory leaks from the as_is decomposition plugin. 
@nichamon, @narategithub, @nick-enoent please take a look. I'm most concerned with the transport changes.

V4.4.2 fixes

---

.github/workflows/4.3.3-compat-test.yaml
.github/workflows/build-ddebug-centos7.yaml
.github/workflows/build-test-centos7.yaml
.github/workflows/build-test-ubuntu-22.04.yaml
.github/workflows/build-test-ubuntu.yaml
.github/workflows/ldms-test-build.yaml
.github/workflows/space-check.yaml
.github/workflows/test-make-dist.yaml

The github workflow tests we have only target pull requests for 'OVIS-4' branch. This patch make them target pull requests for any branch matching 'OVIS-4**' (any branch starting with 'OVIS-4').

Enable github workflow tests on 'OVIS-4.x.x'

---

ldms/src/ldmsd/ldmsd_config.c

clean up avl/kwl in ldmsd_config_plugin error case (cherry picked https://github.com/ovis-hpc/ovis/pull/1339/commits/d7d603b9c11e449c6a93a7dd426eb674035b462d)

fix memory leak on config call with bad plugin name

---

configure.ac

Without the patch, the build variable OPENSSL_LIBS is only assigned when `ovis_auth` is enabled. However, LDMS uses OpenSSL to generate digests for LDMS Sets. The patch ensures that OPENSSL_LIBS is always populated.

Check for the openssl library and always assign OPENSSL_LIBS

---

ldms/src/ldmsd/ldmsd_config.c

ldmsd_plugins_usage checking for input 'all' must be done only if the input is not already null.

fix missing ldmsd_plugins_usage check for 'all' that crashes

---

ldms/src/ldmsd/ldmsd_config.c

ldmsd_plugins_usage checking for input 'all' must be done only if the input is not already null.
cherry picked from https://github.com/ovis-hpc/ovis/pull/1354/commits/e6558e5e17185df7af1ad9c46e3a6a0825d528f7

fix missing ldmsd_plugins_usage check for all that crashes

---

configure.ac
ldms/src/Makefile.am
ldms/src/sampler/Makefile.am
ldms/src/sampler/slingshot_switch/Makefile.am
ldms/src/sampler/slingshot_switch/Plugin_slingshot_switch.man
ldms/src/sampler/slingshot_switch/slingshot_switch.c
ldms/src/sampler/slingshot_switch/slingshot_switch_1.c

This includes
1) Slingshot switch samplers
2) Fixes to the top configuration for build checks
This is being submitted as one request with two commits since a merge of the two would necessary anyway

Slingshot Switch Samplers Plus Config fixes

---

ldms/scripts/examples/linux_proc_sampler
ldms/src/sampler/netlink/netlink-notifier.c
ldms/src/sampler/netlink/netlink-notifier.man

While not always calculable, the duration of tracked pids is of great interest and rather hard to compute downstream. This adds the duration field to process end messages and a format option to suppress it for sites not ready to migrate to the expanded schema.
Unlike ldmsd, the status of ldms-notify cannot be determined remotely, so this also adds a heartbeat message, which by default is not generated.

ldms-notify enhancements needed for production convenience.

---

ldms/src/sampler/json/json_stream_sampler.c

JSON_LIST_VALUE_setter now:
checks for malloc failure in asprintf
stops potential use after free on rec_type_name
puts out error messages if malloc fails
checks for rec_idx being set properly before use.
stops cross-iteration control value pollution.
This also shuts up several gcc warnings on gcc 4.8.

fix memory misuse potential in json_stream_sampler

---

ldms/src/sampler/netlink/netlink-notifier.c

cloned code from init message env variable copy code needed conversion to the _end variable.

fix task end message env variables copy code in netlink notifier

---

ldms/src/core/ldms.h
ldms/src/core/ldms_xprt.c
ldms/src/ldmsd/ldmsd_prdcr.c

Without this patch, passive producers may not function correctly on systems that support IPv6. This patch ensures that passive producers work properly on IPv6.

Make ldms_xprt_by_remote_sin() support IPv6

---

ldms/scripts/examples/linux_proc_sampler
ldms/src/sampler/netlink/netlink-notifier.c
ldms/src/sampler/netlink/netlink-notifier.man

This adds a format extension to include program names in exit messages, the purge-track-dir option to clean up expired tracking files, and fixes certain ignored environment variables. The test of the notifier is updated with it.

443 netlink improvements

---

ldms/src/sampler/app_sampler/linux_proc_sampler.c

Extraneous %s in format strings cause wild pointer reads and crashes.

remove extra string substitution that crashes in linux_proc_sampler

---

ldms/src/ldmsd/ldmsd_request_util.c

The parsing code adds extra STRING attribute when no authentication plugin attribute is given.

Fix the default_auth request parsing logic

---

ldms/scripts/examples/linux_proc_sampler.job
ldms/scripts/examples/linux_proc_sampler.job.1
ldms/scripts/examples/linux_proc_sampler.job.2
ldms/scripts/examples/linux_proc_sampler.job.3
ldms/src/sampler/netlink/netlink-notifier.c
ldms/src/sampler/netlink/netlink-notifier.man

This takes care of getting the jobid to the netlink-notifier messages for the many ways in which a process can be created in slurm/lsf without receiving a resource manager environment variable list. The intent is to use the same data source as the job_info/jobid plugins now use.
Processes with uid's below the user range do not get a jobid applied to them.
If enabled, a list of default locations and variable names is checked for a jobid string.
The file location can be overridden. It is reread on inotify events.
This feature is not enabled by default.
The integration test is supplied:ldms-static-test.sh linux_proc_sampler.job.

Netlink add jobid 4.4.x

---

README.md

The patch clarifies that Python3 and munge development libraries are dependencies. This patch also adds a section that points to pre-built containers.

Clarify the dependencies in README.md

---

configure.ac

I encountered an issue when trying to build LDMS on AlmaLinux8 where flex wasn't installed on the system.  It doesn't fail at configure, and the error during compilation is esoteric. 
@nichamon @bschwal @baallan
The issue:
there’s a problem when you run configure without flex support, it configures fine, but fails with some esoteric error:
```
make[6]: Entering directory '/home/jkgreen/Source/ovis/build/lib/src/ovis_json'
CC       ovis_json_test-ovis_json_test.o
CC       ovis_json.lo
: -o ovis_json_lexer.c ../../../../lib/src/ovis_json/ovis_json_lexer.l
CC       ovis_json_lexer.lo
gcc: error: ovis_json_lexer.c: No such file or directory
gcc: fatal error: no input files
```
The error output suggests a bug or incompatibility in bison or yacc, when really, it just needs a flex package to …

Add logic in configure.ac to check for flex and fail if not found

---

configure.ac

The last tag in the OVIS-4 branch's history is OVIS-4.3.11. We might want to make a "v4.3.11" tag pointing to the same commit as OVIS-4.3.11 to give git-verson-gen something to find when this commit lands.

Change prefix used by git-version-gen to "v" from "OVIS-".

---

ldms/scripts/examples/blob_writer_rollover
ldms/scripts/examples/blob_writer_rollover.1
ldms/scripts/examples/blob_writer_rollover.2
ldms/src/sampler/blob_stream/Makefile.am
ldms/src/sampler/blob_stream/Plugin_blob_stream_writer.man
ldms/src/sampler/blob_stream/blob_stream_writer.c

This eliminates the need for cron-driven scripting to make interactive plugin reconfig calls just to achieve file rollover.
This will help reduce incomplete blob file writes as well.

add rollover to blob_stream_writer in b4.4

---

ldms/scripts/examples/linux_proc_sampler.job
ldms/src/sampler/netlink/netlink-notifier.c

Adds format 3 option to the netlink publisher. This makes linux/slurm/lsf json messages and init/exit messages similar in field ordering to the maximum extent possible so that creating policies and tools transforming stream data across resource managers is simpler.

Netlink stream format harmonization for 4.4

---

configure.ac
ldms/src/core/ldms.c
ldms/src/core/ldms.h
ldms/src/decomp/as_is/Makefile.am
ldms/src/decomp/as_is/decomp_as_is.c
ldms/src/decomp/flex/Makefile.am
ldms/src/decomp/flex/decomp_flex.c
ldms/src/decomp/static/Makefile.am
ldms/src/decomp/static/decomp_static.c
ldms/src/ldmsd/Makefile.am
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_decomp.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_row_cache.c
ldms/src/ldmsd/ldmsd_strgp.c

This set of changes implements functional operators in the decomposition path. These changes also change the JSON parser to use the libjansson library which provides better error reporting and an easier to use API.

Decomp func op

---

ldms/src/core/ldms_stream.c

This was a copy-paste typo. It should be
LDMS_STREAM_EVENT_UNSUBSCRIBE_STATUS, not
LDMS_STREAM_EVENT_SUBSCRIBE_STATUS.

Fix typo in ldms_stream_cb (LDMS_STREAM_EVENT_UNSUBSCRIBE_STATUS)

---

.github/workflows/4.3.3-compat-test.yaml
.github/workflows/build-ddebug-centos7.yaml
.github/workflows/build-test-centos7.yaml

CentOS7 is old, and GitHub Runner recently uses 'node20' which requires newer GLIBC that does not exist in CentOS7. As a result, the three workflows in our repository that use 'ovis-centos-build' image fails to even checkout the code since `actions/checkout@v3` was implemented in TypeScript that run using 'node.js'.
According to this:
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/ CentOS7 is also removed from the supported OS list due to node20 not supported on CentOS7.
This patch does the following on the CentOS7-based workflows:
- Use `actions/checkout@v1` (instead of v3) because it is implemented as a plugin that comes with the GitHub Runner (C++). We do not use any advanced features that does not exist in v1.
- …

Workaround for GitHub workflow dropping CentOS7 support

---

ldms/src/store/kokkos_appmon/kokkos_appmon.c

Top of tree has the correct file but b4.4 and 4.4.3 do not. Strings should not get padded by 1, this is from some legacy stuff.

Update kokkos_appmon.c to not pad extra characters to node / name

---

ldms/python/ldms.pyx

The `isinstance(cb, types.FunctionType)` check does not cover all callables. If the application supplies a method as `cb`, the `isinstance` check failed. This patch modifies the condition to use `callable()` check instead to cover all callable types.

Use `callable()` to check callable in ldms.Xprt (ldms.pyx)

---

ldms/src/ldmsd/ldmsd_prdcr.c

Check that transport exists before attempting to assign event callback
when using deprecated producer type passive

Resolve segfault when using deprecated producer type "passive"

---

ldms/src/decomp/static/decomp_static.c
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_row_cache.c

There are multiple fixes and improvements in this PR.
The bug that instigated this work is fixed in the commit titled "ldmsd_row_cache: fix tree_comparator() function".
Also notable is the fix for the timestamp calculations in commit "decomp_static: correct timestamp calculations".

Fix decomp operations (b4.4. branch)

---

ldms/python/ldms.pxd
ldms/python/ldms.pyx
ldms/src/core/ldms_rail.c
ldms/src/core/ldms_xprt.c
ldms/src/core/ldms_xprt.h

This pull request addresses the following issues:
- Add the _forgotten_ `set_by_name()` xprt operation. 
- The passive (accepted) legacy xprt was intentionally exposed to the application. It should be wrapped in rail object.
- Fix `set_delete` notification code path to support rail.

LDMS Rail fixes

---

ldms/src/core/ldms_xprt.c

Move ref_put before assigning local set to NULL to avoid referencing a NULL address. Resolves segfault.

Fix null reference in ldms_xprt.c

---

ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller

When there is no `ldmsd` connection, `ldmsd_controller` command parameter completion does not work. This patch fixes the issue.

[b4.4] Fix `ldmsd_controller` completion without ldmsd connection

---

ldms/src/core/ldms_xprt.c

Previosly, ldms_xprt_names() incorrectly passed the local address to getnameinfo() to obtain the remote hostname and port. This resulted in incorrect output.

Fix incorrect remote hostname and port produced by ldms_xprt_names()

---

ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller

When there is no `ldmsd` connection, `ldmsd_controller` command parameter completion does not work. This patch fixes the issue.

Fix `ldmsd_controller` completion without ldmsd connection

---

ldms/src/sampler/filesingle/ldms-sensors-config

mellanox device headings in the output of the 'sensors -u' command may include a colon embedded in the device name. Prior to this fix, the last_group variable would become unassigned for mlx devices, causing output failure.
also removes a trailing line and incorrect usage comment line.

fix device group detection for mellanox in filesingle in b4.4 on CTS2 machines

---

ldms/src/core/ldms.c
ldms/src/core/ldms_rail.c

Ensure that the update operation is handled by `__rail_update()`, allowing the rail handle to be delivered upon update completion

Interpose rail update callback to inject rail handle during update

---

ldms/scripts/ldms-csv-anonymize
ldms/scripts/ldms-csv-export-sos
ldms/scripts/ldms_local_opa2test.sh.in
ldms/scripts/ovis-roll-over.py
ldms/src/sampler/filesingle/ldms-sensors-config
ldms/src/sampler/shm/mpi_profiler/mpi_profiler.c
ldms/src/sampler/shm/mpi_profiler/wrap/wrap.py
ldms/src/sampler/shm/shm_sampler.c

@bschwal this removes python2 from OVIS-4
```
bash-4.4$ grep -r "/usr/bin/env python2" rpmbuild/BUILD/    
rpmbuild/BUILD/ovis-ldms-4.4.3/ldms/src/sampler/shm/mpi_profiler/wrap/wrap.py:#!/usr/bin/env python2  
rpmbuild/BUILD/ovis-ldms-4.4.3/ldms/src/sampler/filesingle/ldms-sensors-config:#! /usr/bin/env python2  
rpmbuild/BUILD/ovis-ldms-4.4.3/ldms/scripts/ldms-csv-export-sos:#! /usr/bin/env python2  
rpmbuild/BUILD/ovis-ldms-4.4.3/ldms/scripts/ovis-roll-over.py:#!/usr/bin/env python2  
rpmbuild/BUILD/ovis-ldms-4.4.3/ldms/scripts/ldms-csv-anonymize:#! /usr/bin/env python2
```
I still need to do some testing to ensure I didn't introduce any bad syntax. Evan and I plan on testing  this early this week.  If you have a chance, please review.

Python2 removal multiple scripts

---

ldms/src/core/ldms_rail.c

rail->max_msg() shall return the maximum length of data the application can send. Thus, it is underlying zap max_msg less the size of LDMS message header.

Fix LDMS rail max_mgs

---

ldms/src/core/ldms_xprt.c

The ldms_xprt_sockaddr() function can cause a segfault if the x->zap_ep endpoint is NULL. This commit adds a check to prevent this issue.

Prevent segfault in ldms_xprt_sockaddr() by checking for NULL endpoint

---

ldms/src/core/ldms.c

The ldmsd aggregators on one of our production clusters would enter into a deadlock state waiting on `delete_thread` indefinitely, where the aggregator daemon continued to run, would use 100% cpu, and in gdb session with a debug-symbol supported aggregator daemon instance, we discovered the issue manifests in `ldms/src/core/ldms.c` where an if statement lacked a test to confirm success of red/black node relationship, (?).
I'm proposing adding in this code-fix for this issue we continue to encounter on Sandia systems after debug session on tag release v4.4.3 with @tom95858, on aggregators without the patch.
@bschwal

 ldmsd hanging on delete_thread fix

---

ldms/python/ldms.pxd
ldms/python/ldms.pyx
ldms/src/core/ldms.c
ldms/src/core/ldms.h

This is to support information access to LDMS Schema and Record
Definition objects without the LDMS sets. The schema registry needs
these APIs to access metric information inside the Schema and Record
Definition to construct their representation in the Schema Registry
database.
This pull request also includes bug fixes found along the way.

Add C and Python API for LDMS Schema info access

---

ldms/src/ldmsd/ldmsd_request.c

`dump_cfg` ldmsd command produced deprecated CLI options (e.g. -C, -P). This patch removed the deprecated CLI options and produced commands in config file instead.

Fix `dump_cfg` producing deprecated CLI options

---

ldms/scripts/ldms-csv-anonymize
ldms/scripts/ldms-csv-export-sos
ldms/scripts/ldms_local_opa2test.sh.in
ldms/src/sampler/filesingle/ldms-sensors-config
ldms/src/sampler/shm/mpi_profiler/mpi_profiler.c
ldms/src/sampler/shm/mpi_profiler/wrap/wrap.py

Pulling in the changes to bring python2 to python3 into the b4.4 branch. @baallan

python2 to 3 conversion backport to b4.4

---

ldms/src/core/ldms.c

The set name provided to ldms_set_create cannot contain characters that cannot be encoded in a quoted string. Prior to this patch it was possible to create a set that would crash ldms_set_dir because the result is encoded as a JSON object and the instance name as a JSON string.

Perform validity checks on set name

---

configure.ac
lib/src/zap/Makefile.am
lib/src/zap/fabric/Makefile.am

`--with-libfabric` was only looking for the library in `PREFIX/lib`. This patch removed `--enable-fabric` and use `--with-fabric` that check for the library/header by default.
Fixes #1472
Backporting this commit would probably address issue #1472. The only thing to consider though, is whether we want to make which change to the configure command line options in b4.4.

Fix libfabric build option (b4.4 backport)

---

ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/Makefile.am
ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd_request.c
lib/src/ovis_log/ovis_log.c

The pull request resolves #1471 .

Address mixed use of ldmsd_log() and ovis_log()

---

.github/data/dispatch.yaml
.github/workflows/create-release.yaml

This patch adds another job in the `create-release.yaml` that dispatches `docker buildx bake` jobs in `ldms-containers` after the `build` job in `create-release.yaml` succeeded.
This is the same as #1477 but for b4.4.

(for b4.4) Add ldms-containers dispatcher on release

---

.github/data/dispatch.yaml
.github/workflows/create-release.yaml

This patch adds another job in the `create-release.yaml` that dispatches `docker buildx bake` jobs in `ldms-containers` after the `build` job in `create-release.yaml` succeeded.

Add ldms-containers dispatcher on release

---

ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller

This change refactors ldmsd_controller to consistently handle failures from handle_args() and fmt_status(). This change
more consistently reports server-side errors such as 'Operation not permitted' which would previously result in a crash or confusing output.
There are still issues if ldmsd_controller is started without specifying a host/port/auth. In this mode, it is not connected and therefore nearly all commands will fail with a crash. The only use case I know of for this mode is to access the help which provides useful syntax information. We should consider removing it to avoid user confusion.
@narategithub has run this change through the ldms-test system test suite and this change does not cause any errors.

Improve error reporting in ldmsd_controller

---

ldms/src/core/ldms.c
ldms/src/core/ldms.h
ldms/src/decomp/static/decomp_static.c

This is the same as #1456, but for b4.4.

[b4.4] Fix static decomposition

---

ldms/src/sampler/blob_stream/blob_stream_writer.c

For rollover periods where no messages arrive to store, remove the  empty output files instead of filling up the disk.

wip: b4.4 bug: blob_stream_writer plugin: stop generating empty files

---

configure.ac
ldms/src/sampler/rdc_sampler/Makefile.am
ldms/src/sampler/rdc_sampler/rdcinfo.h

Some fixes to allow compiling rdc_sampler with ROCm 6.2.1.

[main] rdc_sampler fixes

---

configure.ac
ldms/src/sampler/rdc_sampler/Makefile.am
ldms/src/sampler/rdc_sampler/rdcinfo.h

Some fixes to allow compiling rdc_sampler with ROCm 6.2.1.

[b4.4] rdc_sampler fixes

---

ldms/src/ldmsd/ldmsd.c

truncating the log now works correctly whether the old log exists or not and independent of the ordering of -l and -t commands.

b4.4 bug: deprecate -t since it is gone in main, mixes poorly with -l, and exits when there is no preexisting log

---

ldms/src/sampler/examples/test_sampler/test_sampler.c

Test sampler access raw metric value with `mval->v_u64` and increment that value by 1. This works for integer values. When `mval` contains float or double, `mval->v_u64` became big number due to IEEE 754 binary32 or binary64 format. As such, `test_sampler` should use `ldms_mval_as_u64()` to coerce the `mval` to u64 properly.

[b4.4] Fix value increment in test_sampler

---

ldms/man/ldmsd_controller.man
ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_failover.c
ldms/src/ldmsd/ldmsd_prdcr.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_request_util.c

Change producer's hostname resolution failure at config time from an error to a warning, allowing ldmsd to continue starting up. The hostname will be resolved again before establishing the connection and retired at the reconnect interval if the resolution fails.
Resolves #1489

Make ldmsd continue startup on producer's hostname resolution failure

---

ldms/src/sampler/examples/record_sampler/record_sampler.c

Add `with_name` option to record_sampler to generate `dev[name]` device name in the set (for testing).

[b4.4] record_sampler `with_name` option

---

ldms/src/core/ldms.c
ldms/src/core/ldms.h
ldms/src/decomp/static/decomp_static.c
ldms/src/sampler/examples/test_sampler/test_sampler.c

`ldms-test/ldmsd_decomp_test` was failing and the following bugs were discovered:
- "type" from the configuration was ignored,
- "fill" was not working because "type" was ignored,
- the ARRAY values were ignored.
This pull request addressed the discovered issued as well as keeping the destination rows consistent within `ldmsd` process life span as follows:
- The type of a destination column is stored in `cfg_col->type`.
- If "type" of a column is specified in the config file, `cfg_col->type` is set
to the specified "type".
- Otherwise, `cfg_col->type` is discovered from the `metric` in the `set` being
processed. If it cannot be resolved, the row is skipped.
- If the type of the metric from `src` (e.g. from `set`) is not the same as
the same type of the `dst`, the value will be coerced. …

Fix static decomposition

---

ldms/src/sampler/examples/record_sampler/record_sampler.c

Add `with_name` option to record_sampler to generate `dev[name]` device name in the set (for testing).
This is the same as #1510, but for `main` branch.

record_sampler `with_name` option

---

lib/src/ovis_event/ovis_event.c

When `__thrstat_wait_start()` was called, the caller was going into INACTIVE state from ACTIVE state. Hence, the duration from `wait_end` to `now` was the active time and should be added to `proc_tot`.
Likewise, when `__thrstat_wait_end()` was called, the caller just woke up. Hence, the duration from `wait_start` to `now` was an INACTIVE time and should be added to `wait_tot`.

Fix ovis_event thrstat calculation

---

ldms/src/ldmsd/ldmsd_request.c

Modify updtr_task, prdcr_hint, and set_route handlers to use ldmsd_send_req_response() for sending error messages back to requesters. This function automatically handles message length calculation, removing the need for manual length calculations in these handlers.

Standardize error response in three request handlers

---

ldms/man/ldmsd_controller.man
ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_request.h
ldms/src/ldmsd/ldmsd_request_util.c

This change adds a command to disable stream support in the ldmsd daemon. When streams communication is disabled, stream data cannot be published to or subscribed from the daemon.
The current default of enabled is maintained.

Add requests to enable/disable streams communication

---

ldms/man/Makefile.am
ldms/man/ldmsd_yaml_parser.man
ldms/python/ldmsd/Makefile.am
ldms/python/ldmsd/hostlist.py
ldms/python/ldmsd/ldmsd_yaml_parser
ldms/python/ldmsd/parser_util.py
ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_config.c

Support for YAML configuration files for LDMSD.
YAML configuration file allows configuration of an entire cluster in a single YAML file.
Add -y option to LDMSD CLI that loads a YAML configuration file in the same manner as "-c" for LDMS v4 configuration files.
The -y option parses a YAML cluster file and applies relevant configuration to a specific daemon.
New command ldmsd_yaml_parser command that can generate v4 configuration files from a YAML file.

Yaml support

---

ldms/man/ldmsd_peer_daemon_advertisement.man
ldms/src/ldmsd/ldmsd_prdcr.c
ldms/src/ldmsd/ldmsd_request.c

Currently, an advertised producer's name is the name of the advertiser on the peer. This creates confusion. The patch constructs the producer name as <hostname>:<port>, where hostname is the peer hostname and port is the listening port. If there are multiple listening ports, ldmsd uses the first listening port.

Use peer's hostname and listen port for advertised producer's names

---

ldms/man/ldmsd_yaml_parser.man
ldms/python/ldmsd/parser_util.py

Enhance the permission string parsing from PR #1564.
Add full checking of the string permission representation: (r|-)(w|-)-(r|-)(w|-)-(r|-)(w|-)- )
Add checking of an octal-number-in-a-string, at least verifying that the number looks like octal, and doesn't have excess digits.
(We could perhaps also verify that the "x" bits are not set, but do not do so in this patch.)

Enchance permission string parsing

---

ldms/src/ldmsd/ldmsd_stream.c
ldms/src/sampler/blob_stream/blob_stream_writer.c

fix errno misreported in blobwriter, and stop warning about repeat subscribe, which happens a lot (50000 out of 55000 log lines in a recent case)

fix errno report in  blobwriter, stop warning about repeat subscribe

---

ldms/man/ldmsd_yaml_parser.man
ldms/python/ldmsd/parser_util.py

Add cache_ip option to aggregators->peers
Update documentation

Update YAML permissions in configuration

---

ldms/python/ldms.pxd

This patch addressed issues with Cython3. The patch does not break Cython 0.29 compatibility.
Cython3 became the stock package on Ubuntu 24.04. The change in Cython language policy requires explicit `except` directive on the C function pointer type; otherwise, the function pointer type was assumed `noexcept` but the actual function implementations without `except` directive is assumed `except *`, making them not able to be assigned as callback functions.
In addition, Cython 3.0.8 (stock package on Ubuntu 24.04) has Enum generation bug (multiple declarations of same Enum). When `ldms_xprt_event_type type` enum type is explicitly referred to in `ldms_xprt_event` struct, Cython 3.0.8 somehow generated the same Enum "type_to_py" functions twice -- leading to compilation error. By declaring …

[main] Add Cython3 support (still support Cytnon 0.29)

---

ldms/python/ldms.pxd

This patch addressed issues with Cython3. The patch does not break Cython 0.29 compatibility.
Cython3 became the stock package on Ubuntu 24.04. The change in Cython language policy requires explicit `except` directive on the C function pointer type; otherwise, the function pointer type was assumed `noexcept` but the actual function implementations without `except` directive is assumed `except *`, making them not able to be assigned as callback functions.
In addition, Cython 3.0.8 (stock package on Ubuntu 24.04) has Enum generation bug (multiple declarations of same Enum). When `ldms_xprt_event_type type` enum type is explicitly referred to in `ldms_xprt_event` struct, Cython 3.0.8 somehow generated the same Enum "type_to_py" functions twice -- leading to compilation error.  By declaring …

[b4.4] Add Cython3 support (still support Cytnon 0.29)

---

ldms/python/ldmsd/parser_util.py

Resolves error when "stores" is returned as None, rather than an empty dictionary in the event no "stores" are present in the YAML configuration

Bug fix when "stores" is not present in YAML config

---

ldms/man/ldmsd_yaml_parser.man
ldms/python/ldmsd/parser_util.py

Addresses bug when "updaters" is omitted from "peers" dictionary in top level "aggregators" dictionary. 
Fixes bug that occurs when "producers" regular expression is not defined in the "updaters" dictionary.
Updaters now correctly only add the parent dictionary's producers when "produers" is not defined in the updaters dictionary.
Updated producer balancing when multiple aggregators share producers in the YAML configuration.
Updated ldmsd_yaml_parser man page

Bug fix for updater parsing

---

ldms/man/ldms_ls.man
ldms/src/ldmsd/ldms_ls.c

This extends (on main) ldms_ls to generate json or tabbed output for machine consumption such as python (json, pandas) and cut or spreadsheets.
In the json and tabbed formats, the age of sets at the last update is included in the outputs triggered by the -v flag. Age is reported in seconds and in intervals (where expected interval hint is available).
The addition of age data is not  made to the base pretty-print -v, as this would break existing scripts that derive data from ldms_ls -v.

add age & machine and readable outputs for ldms_ls: json/tab

---

ldms/src/core/ldms_xprt.c

Fix a race condition where a set delete request from a peer could invalidate maps while an update is being scheduled. Hold the lock during the entire update submission to ensure maps remains valid.

Prevent race between update scheduling and set deletion

---

ldms/src/core/ldms_xprt.c

Fix a race condition where a set delete request from a peer could invalidate maps while ldmsd is handling a rendezvous lookup and is about to submit a remote read request.  an update is being scheduled. Check if the remote and local map handles of the set are valid and hold the lock during the entire read submission to ensure maps remains valid.
This is a corner case. The time window between the times the server deletes the set and responds to a lookup request is very small. In practice, this could happen when a set is very short live.

Prevent race between look-up and set deletion

---

lib/src/ovis_json/ovis_json.c

The jbuf pointer is not updated correctly after the buffer has been reallocated when the entity contains dictionaries or lists. The patch makes sure that the jbuf handle points to the address returned by realloc().

Fix json_entity_dump() in ovis_json

---

.github/data/dispatch.yaml

Maestro has `OVIS-4.4.5` branch targeting `OVIS-4.4.5` release.

Use maestro ver `OVIS-4.4.5` to build containers in github action

---

ldms/python/ldmsd/ldmsd_controller

Before this change, 'min_ts' and 'max_ts' fields were not properly initialized, leading to a KeyError when displaying the statistics. Additionally, the min/max calculation logic didn't properly handle these timestamp values when processing data.
The patch initializes these fields in the data table creation and ensures proper assignment during min/max value calculation, fixing the display error in the store_time_stats command.

Fix timestamp fields in store_time_stats command

---

ldms/src/core/ldms_rail.c
ldms/src/core/ldms_xprt.c

The application-facing xprts are now rails. However `ldms_xprt_connect_by_name()` handled it as xprt and consequently corrupt the rail structure. This patch moves the related code into `ldms_rail.c` and handle it as rail accordingly.

Fix `ldms_xprt_connect_by_name()` wrong xprt type handling in sync mode

---

lib/src/ovis_json/ovis_json.c

The symptom here was a garbage value for the sample count.
The JSON_INT is passed as an int, however, the ovis_json logic was using uint64_t to pull the value from the stack. This resulted in garbage values on some platforms.

Fix incorrect cast in ovis_json

---

ldms/src/sampler/dcgm_sampler/Plugin_dcgm_sampler.man
ldms/src/sampler/dcgm_sampler/dcgm_sampler.c

Update the man page for dcgm_sampler to explain its requirement on the nv-hostengine daemon. Improve a dcgm_sampler error message to suggest checking for nv-hostengine when dcgmConnect() fails.
Fixes #1636

dcgm_sampler: Add documentation about nv-hostengine

---

ldms/src/ldmsd/ldmsd_request.c

- Fix incorrect `config` output, missing the value of `name` attribute.
- The `config` line produced by `dump_cfg` has "(empty)" appended at the end. This caused by `av_to_string()` produced literal "(empty)" when the keyword list has no entry (the keyword list usually has no entry). The memorized keyword list is now checked if it is empty first and uses "" instead of calling `av_to_string()` if it is an empty list. The attribute-value list does not have this issue because all plugins has at least "name" attribute in its config line.
- Fix the `load name=PLUGIN as=INST` output to `load name=INST plugin=PLUGIN`.

Fix dump_cfg ldmsd command

---

ldms/src/ldmsd/ldmsd_request.c

The macro was causing an indefinite loop when the length of the string to be appended equaled the size of the remaining buffer. In this case, LDMS_ROUNDUP(len-sz, __APPEND_SZ) evaluted to zero, resulting in reallocation with the same buffer size repeatedly.
This patch ensures that the buffer is always reallocated with a larger size when len == sz, preventing the infinite loop condition.

Fix __APPEND macro to prevent infinite loop of reallocation

---

ldms/src/ldmsd/ldmsd_request.c

The reference of the auth object was obtained by "find".

Fix wrong reference put in `qgroup_member_add` handler

---

ldms/src/core/ldms_rail.c

`stream_pub_profile` is expected to be not NULL when calling `__rep_publish()` regardless of profiling status for stream message "hop" information. All calls of `__rep_publish()`, except for this one, has non-NULL `stream_pub_profile`. This patch modifies this call site to behave like the other call sites.

Fix SIGSEGV due to NULL stream_pub_profile

---

lib/src/ovis_log/ovis_log.c

In the case of single log level, the function find the matching level from the `level_bl`, but it forgot to check the breeaking `NULL` entry and causing segmentation fault. In addition, the return code of the single-level case is also changed to `-EINVAL` to match that of the multi-level case (which matched the test cases).

Fix SIGSEGV in case of invalid log level

---

ldms/src/store/test/csv_time_drops.cxx

This adds the iostream include that for newer versions of g++ is no longer pulled in by another std include.

fix missing include in csv_time_drop util

---

ldms/src/store/Makefile.am

This adds store_app  darshan  proc_store to the existing list of store plugins that will only be built if sosdb was configured into ldms.

prevent building sos-dependent store plugins without sosdb

---

ldms/python/ldms.pxd
ldms/python/ldms.pyx
ldms/src/core/ldms.c
ldms/src/core/ldms.h
ldms/src/core/ldms_qgroup.c
ldms/src/core/ldms_rail.c
ldms/src/core/ldms_rail.h
ldms/src/core/ldms_xprt.c
ldms/src/core/ldms_xprt.h
ldms/src/core/ldms_xprt_auth.c
ldms/src/ldmsd/ldmsctl.c
ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd_config.c
ldms/src/ldmsd/ldmsd_failover.c
ldms/src/ldmsd/ldmsd_prdcr.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_stream.c
ldms/src/ldmsd/ldmsd_upload.c
ldms/src/sampler/netlink/simple_lps.c
ldms/src/test/test_ldms_notify.c
ldms/src/test/test_ldms_push.c
ldms/src/test/test_ldms_set_info.c
ldms/src/test/test_ldms_xprt_reconnect.c
ldms/src/test/test_ldms_xprt_send_recv.c
lib/src/ovis_ref/ref.h

The pull request is a set of patches:
- Refactor ldms_xprt to use ovis_ref
- Fix ldms_xprt & rail references in the advertisement path on aggregator
- Modify ref.h so that it unlocks ref objects before calling assert() when _REF_TRACK_ is enabled

Refactor ldms_xprt to use ovis_ref and fix rail & xprt references

---

lib/src/zap/fabric/Makefile.am
m4/options.m4

This pull request addressed the issue of zap fabric failed to build when libfabric was installed in a location that is not in the library lookup path. The build failed due to the following reasons:
- `@LIBFABRIC_LDFLAGS@` was not added to zap fabric LIBADD.
- `@LIBFABRIC_INCDIR_FLAGG@` was not set in the `OPTION_WITH_CHECK` macro.
- `@LIBFABRIC_CFLAGS@` was also incorrect (missing `-I` in front of the include path).
NOTE: If `libfabric` was installed in the default lookup locations (e.g. /usr or /usr/local), we will not see the issues.

Fix zap fabric build

---

ldms/src/ldmsd/ldmsd.h

Adding some reserved space to struct ldmsd_plugin will allow us to add furture calls without breaking backwards compatibility.

Add some reserved space in struct ldmsd_plugin

---

ldms/scripts/ldms-static-test.sh.in
ldms/scripts/pll-ldms-static-test.sh.in

also captures stderr/stdout. accounts for switch to not being daemonized automatically.

fix launch of daemons in [pll-]ldms-static-test.sh with &

---

ldms/src/ldmsd/ldmsd_config.c

Return an error message, as well as write to log, when a plugin that doesn't support multi-instance is loaded with an instance name other than the plugin name

Return error message on plugin load for use case

---

configure.ac
ldms/src/auth/Makefile.am
m4/options.m4

- Remove `--enable-munge` and `--disable-munge` (the default was --disable-munge)
- Without specifying anything, the configure script will default to "check", and build the dependant (currently only `ldms_auth_munge`) if `libmunge` is present. If `libmunge` is not present, the dependent will not be built.
- `--with-munge=no` will skip munge check and disable the build of the dependent.
- `--with-munge=yes` will check libmunge and exited with an error if libmunge is not found.
- `--with-munge=<MUNGE_PREFIX>` will build the dependent with libmunge in the munge installation prefix (e.g. /opt/munge).

Fix `--with-munge` configure option

---

ldms/src/ldmsd/ldmsd_request.c

Some of it was already fixed in main.

Fix free/put of uninitialized  pointers in ldmsd_request error paths

---

ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldmsd_config.c

When issuing the following command through `ldmsd_controller`
load name=bogus
the error message returned was
Error loading configuration named bogus with plugin None
In addition, when issuing the same load command through `ldmsctl`, there was no error message printed at all. This was because the response message from `ldmsd` only contained the error code with empty message.
This patch modified `ldmsd` to also return the error message in the response, and both `ldmsd_controller` and `ldmsctl` can just print the error message from the response. This patch also modified `ldmsd_load_plugn()` and `load_plugin()` to add more details in the error response, e.g.:
Error 2 configuration named 'bogus' with plugin 'bogus': failed to
load the plugin, dlerror: /opt/ovis/lib64/ovis-ldms/libbogus.so: …

Fix `load` command's error message

---

ldms/python/ldmsd/ldmsd_yaml_parser
ldms/python/ldmsd/parser_util.py
ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd_config.c

Support for multi-instance plugins in YAML.
Normalize parameter names to use underscores.
Bug fix for LDMSD continuing to run after an error is encountered in a configuration file.

Multi instance support for YAML parser

---

ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldmsd_request.c

Undeprecate `stream_status` and `prdcr_stream_status` commands.
This has passed the updated test: https://github.com/ovis-hpc/ldms-test/blob/main-dev/ldmsd_stream_status_test

Undeprecate `stream_status` and `prdcr_stream_status`

---

ldms/src/ldmsd/ldmsd_stream.c

The pull request ports https://github.com/ovis-hpc/ldms/commit/71bc6c6b2be06d95c96bae6ec19e333ac05ee4b3 from `b4.4`.

Prevent use-after-free in stream publisher RBN key

---

ldms/python/ldmsd/parser_util.py

The defaults for producer and instance should be emitted at most once, not every time, when there is a list of config lines for a sampler plugin. This adds a check to prevent repeats likely to disrupt plugins with multiline config languages.

yaml write_sampler should emit default producer/etc at most once 

---

ldms/src/ldmsd/ldmsd_plug_api.h

ldmsd_plug_log_set() appears in the ldmsd_plug_api.h header, but it is not implemented. We remove it.

Remove unimplemented function ldmsd_plug_log_set()

---

configure.ac
ldms/rules.mk

Allow the RST2MAN variable to point to be used in rules.mk.
Add AM_V_P logic that allows both quiet and verbose output when generating man pages.
Fixes #1760

Improve rst2man detection and build messages

---

ldms/src/ldmsd/ldms_ls.c

Empty lists would cause ldms_ls to crash with the -d option.

Fix crash in ldms_ls when dumping decomposition

---

ldms/src/contrib/store/timescale/store_timescale.c

There is a compile error when built with -Wall -Werror. The host in the format is a static string that is 100 bytes. That with the other elements of the format couuld exceed 128 resulting in truncated output.

Fix static string size bug in store_timescale

---

configure.ac
ldms/src/sampler/Makefile.am
ldms/src/sampler/cxi_sampler/Makefile.am
ldms/src/sampler/cxi_sampler/cxi_sampler.c
ldms/src/sampler/cxi_sampler/ldms-sampler_cxi_sampler.rst

This sampler parses data contained in files in the /sys/kernel/debug/cxi and /var/run/cxi directories and stores this data in a metric set. 
Includes optional config to collect specific counters.

Add a sampler of CXI telemetry and retry data

---

ldms/python/ldmsd/parser_util.py

Without this change, parser_util.py omits the advertiser section when generating aggregator configurations, causing incomplete output.

Address bugs in the prdcr_listen path in parser_util.py

---

ldms/src/ldmsd/ldmsd_request.c

The handler calls the wrong API to get the client list. The patch fixes the function to call the correct API.

Fix stream_client_dump_handler

---

ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldmsd_request.c

Without the patch, ldmsd creates duplicated keys of hostname of the endpoints in a rail, so ldmsd_controller only receives the send queue depth of the last endpoint in a rail. The patch fixes this. It also changes ldmsd_controller:display_xprt_stats() such that it reports the send queue depth of connected connections and skip the disconnected ones. Before the patch, the disconnected connection is represented by "No remote hostname", which confuses the readers.

Fix the sq_depth section of xprt_stats output

---

ldms/man/ldmsd_controller.rst
ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldmsd_failover.c
ldms/src/ldmsd/ldmsd_prdcr.c
ldms/src/ldmsd/ldmsd_request.c

Separate `stream` and `message_channel` subscription/unsubscription request for clarity (also easier to manage internally). Also update documentation to reflect this change.

`prdcr_subscribe/unsubscribe` command to `stream` and `message_channel` separation

---

ldms/src/sampler/Makefile.am
ldms/src/sampler/cxi_sampler/Makefile.am
ldms/src/sampler/cxi_sampler/cxi_sampler.c
ldms/src/sampler/cxi_sampler/ldms-sampler_cxi_sampler.rst

Various cxi_sampler plugin fixes and enhancements
The regex matching was previously matching if the string appeared
_anywhere_ in the file name. That is probably unintented behavior,
so we change the logic to only determine there is a match when the
regex matches the _entire_ file name string.
Collapse the counter file parser to a single function.
Other minor fixes and cleanup.
Maintain a consistent ordering of counters based on the order of the supplied patterns.
Sort the interfaces.
Don't maintain redundant rh_files and tel_files lists.

cxi_sampler plugin fixes and enhancements

---

configure.ac

The pull request ports 9b255fd8f from v4.4.5 to `main`.

Add missing x to ENABLE_PAPI conditional

---

ldms/src/sampler/lustre/ldms-sampler_lustre2_client.rst
ldms/src/sampler/lustre_client/ldms-sampler_lustre_client.rst
ldms/src/sampler/lustre_mdc/ldms-sampler_lustre_mdc.rst
ldms/src/sampler/lustre_mdt/ldms-sampler_lustre_mdt.rst
ldms/src/sampler/lustre_ost/ldms-sampler_lustre_ost.rst

This adds a reminder of the need for debugfs and root when using the lustre plugins to the related man pages.

add a note about debugfs for lustre plugins.

---

ldms/python/ldmsd/parser_util.py

There is a typo 'rails' in the prdcr_listen path. The correct parameter is 'rail' in the singular form. Without the patch, ldmsd_yaml_parser will not include the 'rail' value in the prdcr_listen_add line.

Fix prdcr_listen path in parser_util.py

---

ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd.rst
lib/src/ovis_log/ovis_log.c
lib/src/ovis_log/ovis_log.h

The default logging level and default mode are probably not the best default values. Probably the two most common ways that folks will run ldmsd is: on the command line when they first start playing with ldms, from systemd when ldmsd is using in production. In neither of these cases do genearlly want a timestamp to be prefixed to the log messages. For instance systemd logs to journald by default, and journald does its own timestamping. So right now when I use journalctl to list the ldmsd log, I see double time stamps like so:
```
Jun 12 12:17:42 hetchy1 ldmsd[2815186]: Thu Jun 12 12:17:42 2025: INFO      : Listening on sock:411 using `sock` transport and `munge` authentication
```
this is because on the command line ldmsd is doing:
```
$ ldmsd -F -c ./samp.conf
Thu Jun 12 12:12:41 2025: …
```

ovis_log: Improve the default logging format

---

lib/src/ovis_event/ovis_event.c

ovis_thrstats_init() was called in ovis_scheduler_loop() which was called on the other thread. The find_least_busy_thread() function was called from the main thread and consequently called ovis_scheduler_thrstats_get() while the thrstats was not yet initialized (the other thread was still starting), and causing SIGFPE (divided by zero). This happened on a slow virtual machine.
This patch moved the ovis_thrstats_init() calls to ovis_scheduler_new() (initialize w/o specific name) and ovis_scheduler_name_set() (re-initialize when the name has set, usually by the main thread before the worker thread started).

Fix ovis_thrstats_init() race bug

---

ldms/src/ldmsd/ldmsd_request.c

This patch fixes a little typo when iterating over storage plugins, the condition of the loop checked on `samp` instead of `store`. The result of the typological error was that store plugin usages were not printed.

Fix empty usage string for store plugin (typo)

---

ldms/src/ldmsd/ldmsd_cfgobj.c

Valgrind complained that cfgobj was unlocking a not-locked mutex on cfgobj. All callers of ldmsd_cfgobj_new_with_auth() do unlock the cfgobj. This patch locks the cfgobj when it is created.

ldmsd_cfgobj_new_with_auth() shall return locked object

---

ldms/src/decomp/as_is/decomp_as_is.c

`as_is` decomposition uses all metrics in the set, plus extra `timestamp` phony metric. Thus, it shall iterate through all metrics in the set when it builds (internal) cfg for the schema.

Fix `as_is` decomposition SIGSEGV

---

ldms/scripts/examples/lustre_client
ldms/scripts/examples/lustre_client.1
ldms/scripts/examples/lustre_client.2
ldms/src/sampler/lustre_client/ldms-sampler_lustre_client.rst
ldms/src/sampler/lustre_client/lustre_client.c
ldms/src/sampler/lustre_client/lustre_client_general.c
ldms/src/sampler/lustre_client/lustre_client_general.h

This adds a test mode option for reading fake sample data without root access and two options to include new/supplementary data in the schema.
Forward port to main of PR #1692.

Fix parsing brittleness in lustre_client

---

ldms/scripts/examples/ls_storm
ldms/scripts/examples/ls_storm.1

this is tunable by 3 items file ls_storm:
- change maxdaemon assignment
- change gmax assignment
- comment/uncomment vgon (if uncommented, samplers are under valgrind which slows)
When run out of the box (valgrind included) it easily shows up races/memory errors if they are present.
If configured with tests enabled, runs with
```
script -c '$prefix/bin/ldms-static-test.sh ls_storm'
```

add ls connection storm reproducer

---

ldms/scripts/examples/flapL0
ldms/scripts/examples/flapL0.1
ldms/scripts/examples/flapL0.2
ldms/scripts/examples/producer
ldms/scripts/examples/prolog.sampler.many
ldms/scripts/ldms-static-test.sh.in

This adds a test of L0 flapping sufficient for demonstrating bugs with/without valgrind memcheck or drd.
If configured as below under toss4, the test can be launched with
```
script -c '$prefix/bin/ldms-static-test.sh flapL0'
```
after it completes:
```
grep RSS typescript
```
and the valgrind output will be in 
```
ldmstest/flapL0/logs/vg.1.* (the L2 valgrind log)
ldmstest/flapL0/logs/vg.2.* (the L1 valgrind log)
```
All the inputs and outputs for the daemons are in the usual locations documented per the ldms-static-test man page.
Most of the sampler related options are optional.
```
configure \
--disable-atasmart \
--disable-gpumetrics \
--disable-perfevent \
--disable-rabbitv3 \
--disable-switchx \
--disable-amqp \
--prefix=$INSTALL_DIR \
--disable-aries_gpcdr \ …
```

add reproducer for sampler flapping test

---

ldms/scripts/examples/dcgm1
ldms/scripts/examples/dcgm1.1
ldms/scripts/examples/dcgm_nobase
ldms/scripts/examples/dcgm_nobase.1
ldms/scripts/examples/dcgm_nobase.2
ldms/src/sampler/dcgm_sampler/dcgm_sampler.c

this also adds the simple integration test case for the no sampler_base configuration of dcgm_sampler.

fix base pointer misuse in dcgm_sampler no use_base configuration

---

ldms/src/sampler/dcgm_sampler/dcgm_sampler.c

also fix ordering in destructor and remove use of SAMP except in usage string.

use sampler instance name where it should be (dcgm)

---

ldms/man/ldmsd_peer_daemon_advertisement.rst
ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldmsd_request.c

Without the change, the UID, GID, and Permission of prdcr_listen configuration objects are always 0. The patch fixes this.

Fix prdcr_listen's acc bit

---

ldms/man/Makefile.am
ldms/man/ldms_msg.rst
ldms/man/ldmsd_stream_ldms_msg_conversion_guide.rst
ldms/src/core/ldms.h
ldms/src/core/ldms_msg.c

- Add `ldmsd_stream_ldms_msg_conversion_guide` man page.
- Fix SIGSEGV when `ldms_msg_client_get_stats()` is called during the `LDMS_MSG_EVENT_CLIENT_CLOSE` callback.
- Add match/is_regex/desc accessors of `ldms_msg_client` for informational purposes.
- Fix `ldms_msg` man page.

Msg conversion guide plus fixes for `ldms_msg`.

---

ldms/src/core/ldms_rail.c

Add NULL parameter checking for the xprt name and auth_name parameters. Presently, the function will crash if either of these parameters is NULL. This patch returns EINVAL instead.

Add parameter checking to ldms_xprt_rail_new

---

ldms/src/core/ldms_xprt.c
lib/src/zap/sock/zap_sock.c

This fixes an issue where the transport has not been connected and a socket error or disconnect occurs. When this happens, the endpoint has not yet been assigned to a zap_io_thread, however, the cleanup logic assumes that it is.
This also fixes a couple of memory leaks that were discovered during the testing of this fix.

Fix socket transport error before connect

---

ldms/src/core/ldms.c

In the future, if new ldms_msg message types and event types are required, they can be added without modifying the check

Iterate using sizeof for LDMS_MSG_TYPE and LDMS_MSG_EVENT_TYPE

---

ldms/src/ldmsd/ldmsctl.c

fix ldmsctl memory leak for every command handled
also fixes uninitialized error code return

     fix ldmsctl memory leak for every command handled 

---

ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd.h

- fix -y identification of file in error reporting and associated memory leak
- fix memory leak in log level change error path
- mark 'cleanup' as noreturn to make gcc analyses smarter and fix file/mem leaks in cleanup.
- make (and future attribute mark) 'ldmsd_str_ent_new' as nonnull to keep -c/-y option processing code simple.

fix -y identification of file in -y error reporting and fix leaks /ldmsd.c

---

ldms/src/ldmsd/ldmsd_cfgobj.c

without this fix, callers of the type_str function can get back invalid pointers.

fix missing values for ldmsd_cfgobj_type_str() of ldmsd_cfgobj

---

lib/src/ovis_log/ovis_log.c

- fix uninit pointer use in ovis_log_register error paths
- fix memory ovis_log_level_to_str leak in ovis_log_list
- fix unclosed files in __log_open error paths.

 fix ovis_log leaks/wild pointers in log_register and open      

---

lib/src/ovis_log/ovis_log.h

document ovis_log.h that the result of ovis_log_level_to_str must be freed.
This lets both the compiler & user can easily see it in ovis_log.h.
ovis_log_level_to_str should not appear directly in a formatting argument list.

 document ovis_log.h that the result of ovis_log_level_to_str must be freed.

---

ldms/src/store/stream/stream_csv_store.c

- _get_header_from_data can leak memory if user stream json data is misformatted.
- open_streamstore can leak file descriptor during plugin config()

    fix stream_csv_store.c potential per-message memory leak

---

lib/src/zap/zap.c

Valid zap events range from 1 to zap_event_last-1.
Changing enum define to use  ZAP_EVENT_LAST=ZAP_EVENT_SEND_COMPLETE
might be a good idea, but may touch other code or tests of inter-version enum compatibility

 minimal fix to zap_event_str in zap.c (change range check)

---

ldms/src/sampler/app_sampler/app_sampler.c

if uid is included in the data to be collected, a buffer write overrun by 1 may occur.

declaration of buffer w in app_sampler.c was insufficient; active if uid captured

---

ldms/src/core/ldms_msg.c

fix potential use-after-free in ldms_msg_subscribe path.
also fixed potential missing va_end in ldsm_msg_publish path

  fix potential use-after-free in ldms_msg_subscribe path

---

ldms/src/core/ldms.c

__record_set leaked zap info if the set was already known.
ldms_metric_type_to_scalar_type did not handle timestamp and structure types. it now maps these to scalar types as:
[LDMS_V_LIST] = LDMS_V_NONE,
[LDMS_V_LIST_ENTRY] = LDMS_V_NONE,
[LDMS_V_RECORD_TYPE] = LDMS_V_NONE,
[LDMS_V_RECORD_INST] = LDMS_V_NONE,
[LDMS_V_RECORD_ARRAY] = LDMS_V_NONE,
[LDMS_V_TIMESTAMP] = LDMS_V_TIMESTAMP

fix missing zap_unmap in __record_set() and fix ldms_metric_type_to_scalar_type()

---

lib/src/ovis_util/dstring.c

in corner case, dstring buffer could get reallocated to 2Gb unnecessarily.

stop dstring from expanding to unnecessary huge size

---

ldms/man/ldmsd_controller.rst
ldms/src/contrib/store/timescale/store_timescale.c
ldms/src/contrib/store/tutorial/store_tutorial.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/store/avro_kafka/ldms-store_avro_kafka.rst
ldms/src/store/influx/store_influx.c
ldms/src/store/kafka/store_kafka.c
ldms/src/store/papi/store_papi.c
ldms/src/store/slurm/store_slurm.c
ldms/src/store/store_amqp.c
ldms/src/store/store_csv.c
ldms/src/store/store_flatfile/store_flatfile.c
ldms/src/store/store_function_csv.c
ldms/src/store/store_rabbitkw.c
ldms/src/store/store_rabbitv3.c
ldms/src/store/store_sos.c

Make the strgp configuration parameter "container" optional so that store_avro_kafka can use its internally configured server information.
Add checks to the rest of the stores to make sure that container is not NULL.

Make the strgp configuration parameter "container" optional

---

ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldmsd_prdcr.c
ldms/src/ldmsd/ldmsd_updtr.c

Without a patch, the aggregator doesn't update a set without hints if auto_interval is enabled. The patch makes it so the aggregator uses the default update interval (given at configuration time) to update sets without hints.

Use default update interval for sets without hints

---

lib/src/ovis_event/ovis_event.c
lib/src/zap/fabric/zap_fabric.c
lib/src/zap/rdma/zap_rdma.c
lib/src/zap/sock/zap_sock.c
lib/src/zap/ugni/zap_ugni.c
lib/src/zap/zap.c
lib/src/zap/zap.h
lib/src/zap/zap_priv.h

The threads managing thread objects in the Zap and
ovis_event libraries need to take the necessary
locks.

Add missing locking around thread stat accesses

---

ldms/src/sampler/slingshot_metrics/ldms-sampler_slingshot_metrics.rst
ldms/src/sampler/slingshot_metrics/slingshot_metrics.c

At least as of Slingshot Host Software release/shs-12.0.0, the API surrounding "groups" has been broken. As a result, we drop support for all groups except for "group:all".
This was cherry-picked from Chris Morrone's commit f4be13e
(At the very least, I want to see if this is the correct way to create a cherry-picked pull-request based on prior feedback -- even if these changes are disregarded again. Thank you for your time!)

slingshot_metrics: drop support for "groups"

---

ldms/scripts/examples/lustre_client
ldms/scripts/examples/lustre_client.1
ldms/scripts/examples/lustre_client.2
ldms/src/sampler/lustre_client/Plugin_lustre_client.man
ldms/src/sampler/lustre_client/lustre_client.c
ldms/src/sampler/lustre_client/lustre_client_general.c
ldms/src/sampler/lustre_client/lustre_client_general.h

This also adds a test mode option for reading fake sample data without root access and two options to include new/supplementary data in the schema.
This patch cures lustre_client data loss for lustre 2.15 client metrics that do not end in .sum but do get collected from lustre metric rows that do contain sum and sumsq columns in the raw.

Fix parsing brittleness in lustre_client for b4.4

---

ldms/scripts/examples/dcgm1.1
ldms/scripts/examples/dcgm1.2
ldms/src/sampler/dcgm_sampler/dcgm_sampler.c

before jobid data didn't get set if use_base was set.

added use of base, when configured, in dcgm sampling.

---

.github/workflows/create-release.yaml

github has changed permissioning. action-gh-release can no longer create a release or attach files to a release without being granted explicit permission. This adds said permission.

Adjust permissions to allow release creation.

---

ldms/scripts/examples/blob_writer
ldms/src/sampler/netlink/netlink-notifier.c

this stops the pid collector from logging enobufs messages that occur because of kernel-side buffer limitations, unless the user specifically enables it during performance testing.

quiet enobufs messages in netlink

---

ldms/src/ldmsd/ldmsd_stream.c

Replace sizeof(b) with max_msg_len-1 in a fgets call. Since b is a malloc'd pointer, sizeof(b) returns the pointer size (8 bytes) rather than the allocated buffer size, severely limiting read capacity.
This ensures fgets() can utilize the full allocated buffer size when reading from the file.

Fix buffer size in ldmsd_stream_publish_file() fgets call

---

ldms/src/ldmsd/ldmsd_prdcr.c

Change the update hint validation from ERROR to DEBUG level when encountering invalid hints like '0:0'. This is expected behavior when sets exist but sampling hasn't started, or for event-driven samplers that don't require starting the sampler plugins.

Change update hint validation log from ERROR to INFO level

---

ldms/python/ldmsd/ldmsd_controller

The data row column widths were smaller than the header row, causing misaligned output. Adjust data row column widths to match header row.

ldmsd_controller: Fix prdcr_set_status column alignment

---

.github/labeler.yml
.github/workflows/labeler.yml

Introduce a new github workflow that adds github labels to PRs. The initial set of patterns just add the labels "main" or "b4.4" to a PR based on whether the PR targets the main or b4.4 branch.
(There are a couple of speculative patterns for b4.5 and b4.6, but it doesn't hurt to have those. We can add/remove patterns in the future as needed.)

Introduce pull request labeler workflow

---

ldms/src/core/ldms_msg.c
ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd_request_util.c

The msg_enable command was previously only supported for network clients such as ldmsd_controller.
This change also changes how messages are disabled in LDMSD. Previously, messages were disabled in the API itself by default. This forces clients external to LDMSD to explicitly call ldms_msg_enable() in order to enable messages. With this change, messages are disabled in the LDMS Daemon by default, but enabled in the API.

Add support for msg_enable in configuration files.

---

ldms/src/ldmsd/ldmsd_cfgobj.c

`ldmsd_cfgobj_del()` is equivalent to remove and free. So, it must put
- ref by tree, and
- ref by init.

ldmsd_cfgobj_del() ref fix

---

ldms/python/ldms.pxd
ldms/python/ldms.pyx
ldms/src/core/ldms.c
ldms/src/ldmsd/ldms_ls.c

TIMESTAMP type was not properly handled in Python, schema add, and `ldms_ls`.

Fix TIMESTAMP type handling.

---

ldms/src/store/influx/store_influx.c

The influxdb store passed an incorrect parameter name to ldmsd_plug_handle_log_get causing a build failure.

Fix call to ldmsd_plug_handle_log_get in influxdb

---

ldms/src/sampler/perfevent/perfevent.c

This fixes warnings that become errors with -Werror.

Fix build warnings in perfevent sampler

---

.github/data/dispatch.yaml
.github/workflows/create-release.yaml
.github/workflows/dispatch-container-bake.yaml

Move `dispatch-container-bake` job into its own workflow and change the event the workflow depends on from `on push tags` to `on release published` so that when a release is created (by any means; not just by matching pushed tag) our workflow will dispatch the container bake workflow in `narategithub/ldms-containers` repository.
Also conditioned this workflow to run only on `ovis-hpc/ldms` or `narategithub/ldms`, and change SOS branch to `b2.6`.
[fixup] dispatch
Backported from 10a9fd52ba9d023ba94e9f0df26593fd2b6ee222 on main.

`dispatch-container-bake` workflow on release event

---

ldms/scripts/examples/app_sampler
ldms/scripts/examples/blob_writer
ldms/scripts/examples/blob_writer_rollover
ldms/scripts/examples/linux_proc_sampler
ldms/scripts/examples/linux_proc_sampler.job
ldms/scripts/examples/proc_stream
ldms/src/sampler/netlink/netlink-notifier.c

this adds the --log-nobufs option; the default is to no longer complain about kernel-side ring buffer inadequacy unless requested.
it also fixes uncaught incorrect replacement of reconnect with reconnect_interval in netlink invocations in test scripts which was already fixed on main.
backport of #1954 to b4.4

quiet enobufs messages and fix reconnect_interval over-sed that broke netlink tests

---

ldms/src/ldmsd/ldmsd.c

LDMS message is disabled by default in ldmsd, but ldmsd was calling ldms_msg_disable() after processing the priority commands, including msg_enable, which incorrectly disabled LDMS message even when msg_enable was specified in configuration files.

Fix msg_enable being overridden by default disable in ldmsd

---

ldms/scripts/ldms-static-test.rst
ldms/scripts/ldms-static-test.sh.in
ldms/scripts/ldms_pll-ldms-static-test.rst
ldms/scripts/pll-ldms-static-test.sh.in

This fixes the expected behavior if only a single argument is given to the DAEMONS function in the static testing scripts.
DAEMONS 7 now is processed as DAEMONS $(seq 1 7).
This changes no  C code.

parse single argument to ldms-static-test DAEMONS calls correctly

---

ldms/src/sampler/json/json_stream_sampler.c

Removes the last vestiges of the cfgobj structs from json_stream_sampler. Also fixes the per-instance context allocation by performing it in constructor().
Remove the global __log, and uses a per-instance log handle, allowing the plugin to be multi-instance capable.
@tom95858 this PR includes your 'Revert "Fix json_stream_sampler"' from PR #2006.

json_stream_sampler cleanup

---

ldms/scripts/examples/app_sampler.1
ldms/scripts/examples/app_sampler.2
ldms/scripts/examples/blob_writer.1
ldms/scripts/examples/blob_writer.2
ldms/scripts/examples/blob_writer_rollover.1
ldms/scripts/examples/blob_writer_rollover.2
ldms/scripts/examples/darshan_stream_store.1
ldms/scripts/examples/linux_proc_sampler.1
ldms/scripts/examples/linux_proc_sampler.2
ldms/scripts/examples/linux_proc_sampler.3
ldms/scripts/examples/linux_proc_sampler.job.1
ldms/scripts/examples/linux_proc_sampler.job.2
ldms/scripts/examples/linux_proc_sampler.job.3
ldms/scripts/examples/proc_stream.1
ldms/scripts/examples/proc_stream.2
ldms/scripts/examples/proc_stream.3
ldms/scripts/examples/stream_store.1
ldms/scripts/examples/stream_store_many
ldms/scripts/examples/stream_store_many.1
ldms/scripts/examples/stream_store_many.2
ldms/scripts/examples/stream_store_many.3
ldms/scripts/ldms-static-test.sh.in

Since the default disable of streams was added, a batch of test script updates is required to enable streams in stream tests.
There are no C changes here.
In addition, the new stream_store_many test provides a brief storm (that may be scaled) of stream publications and
a fix is added to select .conf as the assumed test input format if -y is not seen in the LDMSD macro arguments.

add stream_enable to stream-related tests and default to .conf

---

ldms/python/ldmsd/ldmsd_yaml_parser
ldms/src/ldmsd/ldmsd_config.c

Automated testing and admins of systemd daemons need ldmsd_yaml_parser results that are usable. For example, .conf files fed to -y now yield less-cryptic errors and malformed yaml is now reported via return code.
This patch:
- routes the main error messages of ldmsd_yaml_parser to stderr and sets the return value to an errno value.
- converts an nonzero error on pclose of the ldmsd_yaml_parser subprocess to a NULL return if the output string is also empty.
- traps anything that is not a reasonable yaml result (list or dict)

Add error reporting for malformed YAML input file.
