ovis-hpc/ldms

ldms/swig/ldms.i

the same bug is present in master at line 396 of ldms.i

fix boolean invariant in test (always true)

---

ldms/src/ldmsd/ldmsd_request_util.c

Set appropriate errno in `req_attr_get_by_id()` and
`req_attr_get_by_name()`.

Set errno in req_attr_get functions

---

ldms/configure.ac
ldms/src/ldmsd-samplers/app_sampler/app_sampler.c
ldms/src/ldmsd-samplers/app_sampler/test_app_sampler.py
ldms/src/ldmsd-samplers/app_sampler/test_app_sampler_config.py
ldms/src/ldmsd-stores/Makefile.am
ldms/src/ldmsd-stores/store_app/Makefile.am
ldms/src/ldmsd-stores/store_app/store_app.c

`store_app`: a SOS-backed storage plugin for `app_sampler` data.
The pull request updated `app_sampler` to include `task_rank` metric which is needed for indexing in `store_app`.

`store_app` storage plugin

---

configure.ac
ldms/configure.ac
ldms/man/Makefile.am
ldms/man/Plugin_store_function_csv.man
ldms/scripts/examples/.canned
ldms/scripts/examples/funcstore
ldms/scripts/examples/funcstore.1
ldms/scripts/examples/funcstore.2
ldms/scripts/examples/ncsastore
ldms/scripts/examples/ncsastore.1
ldms/scripts/examples/ncsastore.2
ldms/scripts/examples/prolog.jobidinfo
ldms/scripts/ldms-static-test.sh.in
ldms/scripts/pll-ldms-static-test.sh.in
ldms/src/sampler/Makefile.am
ldms/src/sampler/llnl/Makefile.am
ldms/src/sampler/loadavg/Makefile.am
ldms/src/sampler/loadavg/Plugin_loadavg.man
ldms/src/sampler/loadavg/loadavg.c
ldms/src/store/store_csv.c
ldms/src/store/store_csv_common.c
ldms/src/store/store_function_csv.c
lib/configure.ac
lib/src/mmalloc/mmalloc.c
packaging/make-all-top.sh
util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/ldms-functions.in

This pr has several independent fixes to enable the snl-ncsa ui pipeline. each commit is independent, except the two modifications to the function_csv store.

fixes for ncsa-snl demo

---

configure.ac

fix missing lustre bit for cray-system-sampler

---

Makefile.am

adjusted nola invocation per j. cook suggestion.
will ask @joncooknmsu to test

restrict .la removal search to libdir only

---

Makefile.am
ldms/Makefile.am
m4/options.m4

Remove OVIS_GIT_SHORT macro and TAG.txt. No one is using it.

Remove OVIS_GIT_SHORT macro

---

configure.ac
ldms/ldms.spec.in
ldms/scripts/examples/loadavg
ldms/scripts/examples/loadavg.1
ldms/scripts/examples/loadavg.2
ldms/scripts/examples/loadavg.3
ldms/scripts/examples/loadavg.4
ldms/src/sampler/Makefile.am
ldms/src/sampler/loadavg/Makefile.am
ldms/src/sampler/loadavg/Plugin_loadavg.man
ldms/src/sampler/loadavg/loadavg.c
packaging/make-all-top.sh

porting loadavg sampler to v4 from v3 before I forget.
Is bundled with vmstat in configuration options.

add v4 loadavg sampler and test

---

util/sample_init_scripts/genders/man/ldms-attributes.man
util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/Makefile.am
util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/ldms-functions.in
util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/ldmsd.in

also fixing lack of env expansion in log gender value for better debugging control.

adding munge to genders init scripts

---

ldms/src/sampler/procinterrupts/procinterrupts.c

switch to strtok_r from strtok in procinterrupts sampler

---

ldms/man/Plugin_lnet_stats.man
ldms/man/Plugin_lustre2_client.man
ldms/scripts/examples/lnet_stats
ldms/scripts/examples/lnet_stats.1
ldms/scripts/examples/lnet_stats.2
ldms/scripts/examples/lnet_stats.3
ldms/scripts/examples/lustre2_client
ldms/scripts/examples/lustre2_client.1
ldms/scripts/examples/lustre2_client.2
ldms/src/sampler/lnet_stats.c
ldms/src/sampler/lustre/lustre2_client.c
ldms/src/sampler/lustre/lustre_sampler.c

this combines Omar's updates for lustre2_client and lnet_stats with fixes found during stria testing.

V4 lustre 2.12 fixes

---

configure.ac
lib/src/json/Makefile.am

Change from generic YACC test to specific BISON test
Fixes #280

Change from generic YACC test to specific BISON test

---

ldms/src/ldmsd/ldmsctl.c

this addresses items that can show up at scale or low memory.

trap ooms, fix null ptr use, fix localtime thread safety, realloc idiom

---

util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/ldms-functions.in

thanks to Chris for the catch.

fix auth option checking, issue 274

---

configure.ac
ldms/src/sampler/Makefile.am
ldms/src/sampler/hello_stream/Makefile.am
ldms/src/sampler/hello_stream/Plugin_hello_sampler.man
ldms/src/sampler/hello_stream/hello_cat_publisher.c
ldms/src/sampler/hello_stream/hello_cat_publisher.man
ldms/src/sampler/hello_stream/hello_publisher.c
ldms/src/sampler/hello_stream/hello_publisher.man
ldms/src/sampler/hello_stream/hello_sampler.c
ldms/src/sampler/hello_stream/parser.pl
ldms/src/sampler/hello_stream/stream_configs/Makefile.am
ldms/src/sampler/hello_stream/stream_configs/README
ldms/src/sampler/hello_stream/stream_configs/hello_stream1.conf
ldms/src/sampler/hello_stream/stream_configs/hello_stream_store.conf
ldms/src/store/Makefile.am
ldms/src/store/hello_stream/Makefile.am
ldms/src/store/hello_stream/Plugin_hello_stream_store.man
ldms/src/store/hello_stream/hello_stream_store.c

Hello_streams sampler and store utilities. These are still in development, but we want to get them into the main line. This includes the hello_sampler and hello_publisher by @tom95858.

Hello streams 4

---

ldms/src/store/store_csv.c

thread unsafe localtime usage
mem leak in error path
unused assignment code

V4 store csv bugs fixed

---

ldms/src/store/store_csv_common.c

mem leak in error path
missing null pointer check in validate_env

fix v4 store_csv_common bugs

---

ldms/src/store/store_function_csv.c

unsafe localtime usage
missing oom check
memory leak in err path
int/unsigned mistyping

fix v4 store_function_csv.c bugs

---

ldms/src/sampler/meminfo/meminfo.c
ldms/src/sampler/procnfs.c
ldms/src/sampler/vmstat/vmstat.c

This commit groups 3 files with only magic number induced problem fixes.

v4 eliminate magic number buffer sizing and theoretical buffer overflow

---

ldms/src/sampler/perfevent.c

thread unsafe use-after-free
missing oom check
memory leaks
improperly unset return codes
missing include
missing read error check
remove unused vars

v4 fix bugs in perfevent.c

---

configure.ac
ldms/src/sampler/Makefile.am

add enable option for "variable" sub-directory

Variable subdir v4

---

ldms/src/ldmsd/ldmsd_stream.c

missing double free, missing null ptr chk, and redundant typedef,

fix bugs in ldmsd_stream.c v4

---

ldms/src/ldmsd/ldmsd_config.c

added "libpapi_sampler.so" to blacklist

added libpapi_sampler.so to blacklist

---

ldms/scripts/examples/fail_sampler_procnetdev
ldms/scripts/examples/fail_sampler_procnetdev.1
ldms/scripts/examples/fail_sampler_procnetdev.2

when a sampler fails to sample in v4, it is stopped. this PR provides a test of this failure sequence.

test for sampler fail handling

---

util/sample_init_scripts/genders/src/ldmsctl_args3.cxx

ignore upstream aggrgator specs  for interval, offset in genders surfing

fix interval default lookup for aggregators

---

ldms/src/sampler/ibnet/scripts/ldms-ibnet-sampler-gen

feature added to dump topology tables for use with grafana queries

add topology csv output for ldms-ibnet-sampler-gen

---

ldms/src/contrib/store/tutorial/store_tutorial.c

Initialize rc on line 106. 
All other changes are whitespace.

fix missing rc initialization

---

ldms/src/sampler/hello_stream/parser.pl

flush stdout in hello_streams parser.pl

flush stdout in hello_streams parser.pl

---

lib/src/zap/sock/zap_sock.c

This passed `zap_test` and all test cases in `ldms-test` repository.

zap_sock - only enable EPOLLOUT when necessary

---

ldms/src/sampler/ibnet/ibnet_data.c

block scanning on other subsets of the same port if base or extended subset fails.

improve input error detection and messages on ibnet sampler config

---

ldms/src/ldmsd/ldmsd_config.c

fixes #357  . issue messages only after all checks are complete, except for invalid path type warnings.

add better error messages for plugins usage query

---

ldms/src/sampler/hello_stream/Makefile.am
ldms/src/sampler/hello_stream/stream_configs/Makefile.am

This solves makefile.am bugs found by Sara from hello example files.

fixes distcheck errors from hello_stream

---

ldms/src/ldmsd/ldmsd_config.c

When a line in a configuraton file is longer than the default maximum
message size of the config file cfg_xprt which is 8172 characters.
ldmsd_config.c:__process_config_file() would pass a record of the whole
request to ldmsd_config.c:__req_filter_failover() which assumes that it
always receives a whole request.
Instead of changing __req_filter_failover() , __process_config_file()
will always pass a whole request to __req_filter_failover(). This is to
avoid changing the failover logic and make a minimal change.

Fix a crash when a config file contains a line longer than 8172.

---

ldms/src/ldmsd/ldmsd_config.c

The bug is that the buffer that reads the content from a configuration
file isn't reset if the previous request goes though the deferred
filter.

Fix failover configuration buffer reset issue

---

ldms/man/ldms-static-test.man
ldms/scripts/examples/strict_kill
ldms/scripts/examples/strict_kill.1
ldms/scripts/examples/strict_kill.2
ldms/scripts/ldms-static-test.sh.in

Added variable KILL_LDMSD_STRICT to ldms-static-test.sh

Added variable KILL_LDMSD_STRICT 

---

configure.ac
ldms/man/run-static-tests.man
ldms/scripts/Makefile.am
ldms/scripts/run-static-tests.sh.in
ldms/scripts/static-test-list.in

Invoke ldms-static-test.sh for all enabled plugins during installation. Man Page included

Added test script that executes ldms-static-test.sh for all enabled plugin samplers

---

ldms/src/core/ldms_xprt.c

Discard the use of a fixed list of know ldms_xprt and let `zap_get()`
discover the specified transport library. The `ldms_zap_tbl` replaces
the `ldms_zap_list` to maintain the plugins that have already been
loaded.

Discard the known list of ldms_xprt

---

lib/src/zap/fabric/zap_fabric.c

REMARK: The network addresses discussed in this patch are IPv4 as
current zap applications use only IPv4 addressing. Generic network
address suport (also not limited to sockaddr) for zap shall be handled
separately in the future.
zap_fabric used `fi_info.src_addr` to specify the listening address
for the passive endpoint. The applications use address 0 to specify
*any* addresses to listen to (i.e. only the port is specified). Even
though this worked perfectly on other zap transports, it did not work
on libfabric. For example, on cygnus-08, a machine with a regular
on-board ethernet and a Converged Ethernet card, `ldmsd -x
fabric:10000` reported a successful listen on port 10000 with `verbs`
provider (the best provider on the machine), but `ldms_ls -x fabric
-p 10000 -h cygnus-08-iw` could …

zap_fabric listen without specifying the address

---

ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_updtr.c

The checks are
* the given interval value is not an empty string,
* the given interval value is a number,
* the given interval value is greater than 0,
* the given offset value is not an empty string,
* the given offset value is a number.
`ldmsd_updtr_new_with_auth()` receives the interval and offset values as
char *. The checks are made before the function is called to keep the
patch small, i.e., no changes to the function signature and its
references. If the checks are made in the fucntion, there are no trivial
ways to send informative error messages to remote clients, e.g.,
`ldmsd_controller`.

Verify the given interval and offset values of an updater are valid

---

ldms/python/ldms.pyx

LDMS Cython was using `RuntimeError` to raise an error from within the
module to the Python application. Even with string describing the error,
it lacks useful attribute such as `errno` from the underlying C code.
In this patch, `RuntimeError` usages were replaced with
`ConnectionError` if the error concerned a transport. For other errors
not directly concerning a transport but stemmed from C function calls,
`OSError` (the parent of all exceptions that have `errno` attribute) is
used with the corresponding `errno`. For all other errors not concerning
C function calls, the more appropriate exception classes from the Python
"builtins" were selected.

LDMS Cython with proper exceptions

---

ldms/src/ldmsd/ldmsctl.c

Without the fix, ldmsctl reused a single buffer to receive message
records. It assumed that the buffer would be handled before the next
record arrives. The assumption is not always true if a response message
consists of multiple records. The symptom is as if ldmsctl does not
receive some records, resulting in ldmsctl crashes.

Fix ldmsctl crashes when it receives a multiple-record message

---

ldms/man/ldms-static-test.man
ldms/man/pll-ldms-static-test.man
ldms/scripts/pll-ldms-static-test.sh.in
ldms/scripts/slurm-examples/cluster
ldms/scripts/slurm-examples/cluster.1
ldms/scripts/slurm-examples/cluster.2
ldms/scripts/slurm-examples/cluster.3
ldms/scripts/slurm-examples/sbatch.cluster

this is a test scripts only request and is part of testing 4.3.4/can be merged before GA.

fix most cluster specific and sock assumptions in pll-ldms-static-test

---

ldms/man/pll-ldms-static-test.man
ldms/scripts/pll-ldms-static-test.sh.in
ldms/scripts/slurm-examples/cluster
ldms/scripts/slurm-examples/cluster.1
ldms/scripts/slurm-examples/cluster.2
ldms/scripts/slurm-examples/cluster.3
ldms/scripts/slurm-examples/sbatch.cluster

incorporated file leak checks in cluster test, and other improvements

Add 1 sec sampling, fabric-sock test options, file counting

---

ldms/python/ldmsd/ldmsd_config.py
ldms/python/ldmsd/ldmsd_controller
ldms/python/ldmsd/ldmsd_request.py
ldms/src/core/ldms.c
ldms/src/core/ldms.h
ldms/src/core/ldms_xprt.c
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_prdcr.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_request.h
ldms/src/ldmsd/ldmsd_updtr.c
lib/src/zap/sock/zap_sock.c
lib/src/zap/ugni/zap_ugni.c
lib/src/zap/zap.c
lib/src/zap/zap.h
lib/src/zap/zap_priv.h

These are the transport statistics discussed in the UG meeting, uGNI CQ recreation on resource error and message cleanup.

Cleanup for OVIS-4.3.4 G/A

---

ldms/src/test/ldms-static-test-bypass.in
ldms/src/test/ldms-static-test-list.sh.in

Adding munge to plugin list for ldms-run-static-test.

adding munge to ldms-static-test list

---

ldms/src/ldmsd/ldmsd_request.c

Initialize the buffer length before passing to ldms_xprt_sockaddr

---

ldms/src/ldmsd/ldmsctl.c

A symptom of the bug is that the status commands will not report any
status because the error code value is a non-zero, garbage value. No
error messages are printed because the response is not really an error
response.

Fix a use-after-free in ldmsctl.c

---

.github/workflows/4.3.3-compat-test.yaml

Add ldms_ls(4.3.3) to ldmsd(OVIS-4) compatibility test

---

ldms/src/core/ldms_xprt.c

The zap references taken when LDMS xprt sends a lookup message or a dir
message are put back when the corresponding reply messages have
received. However, the reply messages may never arrive because of the
disconnection and zap endpoints are leaked. These zap references before
send are not necessary and shall be removed.

Fix zap ep leak in ldms xprt

---

configure.ac
ldms/python/ldmsd/ldmsd_controller
ldms/python/ldmsd/ldmsd_request.py
ldms/src/core/ldms_xprt.c
ldms/src/ldmsd/ldmsd_prdcr.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_stream.c
ldms/src/ldmsd/test/ldmsd_stream_publish.c
ldms/src/sampler/papi/papi_sampler.c
ldms/src/sampler/procnetdev.c
lib/src/zap/sock/zap_sock.c
lib/src/zap/ugni/zap_ugni.c
lib/src/zap/ugni/zap_ugni.h
lib/src/zap/zap.c
lib/src/zap/zap_priv.h
m4/lib-ld.m4
m4/lib-link.m4
m4/lib-prefix.m4

These fixes resolve build, transport, sampler and ldmsd issues with the OVIS-4 GA release

Various fixes to the OVIS-4 GA

---

lib/src/zap/sock/zap_sock.c

zap_sock used `write()` to write messages to the socket. It is possible
to write to a disconnected socket, and when it happened SIGPIPE was
sent to the calling process and the process terminated (default SIGPIPE
action).
Instead of `write()`, this patch uses `send()` with `MSG_NOSIGNAL` to
disable the SIGPIPE on disconnected socket.

Prevent SIGPIPE in zap_sock

---

ldms/src/ldmsd/ldmsctl.c
ldms/src/ldmsd/ldmsd_request_util.c

The commands have been added to ldmsd_controller already.

Add subcribe, xprt_stats and thread_stats to the ldmsctl

---

ldms/src/sampler/ldms_jobid.c

replace perm/uid/gid option code with more featureful sampler_base function call.
Fixes #481

fix #481 by applying sampler_base auth parse/set (security)

---

ldms/src/core/ldms_xprt.c
ldms/src/ldmsd/test/ldmsd_stream_subscribe.c
lib/src/zap/ugni/zap_ugni.c

* Fix SEGV on REJECT on Cray uGNI. 
* Fix authentication failure disconnect
* Refactor streams data delivery at exit
* Update README to remove mention of gettext dependency

V4.3.5 final

---

ldms/src/core/ldms_xprt.c

The releasing of rbd in __ldms_xprt_resource_free() could race with
ldms_xprt_set_delete(). In such case, __ldms_xprt_resource_free()
released the xprt lock, and then ldms_xprt_set_delete() took the lock
and call __ldms_rbd_xprt_release() which removed the rbd from the tree
and drop a reference. That reference could be the last reference to
the rbd, and hence once ldms_xprt_set_delete() released the lock and
__ldms_xprt_resource_free() took the lock again, the rbd would already
be freed -- causing a use-after-free issue.
This patch solved the issue by taking the rbd reference while the rbd
is still in the tree and xprt lock is still hold, and drop the
reference after we're done processing it.

Fix rbd use after free

---

lib/src/zap/rdma/zap_rdma.c

zap_rdma ignore TIMEWAIT_EXIT event as the endpoints are destroyed
since DISCONNECTED or ERROR events are handled, and we don't want to
wait around to free resources. Hence, if the event is TIMEWAIT_EXIT,
rep could already be gone and we shall not access it.

Fix rdma zap endpoint use-after-free

---

lib/src/zap/rdma/zap_rdma.c

submit_pendin() took endpoint lock to free the context while holding
credit lock, while the read/write/send took endpoint lock then credit
lock. This created a dead lock. submit_pending() should re-acquire the
credit lock after it is done freeing context and release the endpoint
lock, which is what this patch does.

Fix zap_rdma submit_pending() deadlock

---

ldms/src/sampler/spank/slurm_notifier.c

This reverts commit 4a28e2c73b1409ef8378785729780c88d62d50b0.

Revert "Fix Slurm step handling in Spank plugin"

---

ldms/src/sampler/slurm/slurm_sampler.c
ldms/src/sampler/spank/slurm_notifier.c

The job_user and job_name environment variables are not set in the
job_prolog context.

Move job_user and job_name to step_init

---

ldms/src/sampler/papi/papi_sampler.c

`handle_job_exit()` in `papi_sampler` incorrectly assumed that
`job->set` was always successfully created before the job exit event and
accessed the set. This resulted in segmentation fault. This patch
modifies `papi_sampler` to check the set before accessing it.

Fix papi_sampler segmentation fault on job exit event

---

ldms/src/test/test_ldms_push.c

The patch addresses two issues.
- The range of the update status has been changed, but the test hasn’t
been updated accordingly. Without the changes, some test conditions are
always true, and some are always false.
- As clients, the test program did not use the given host value to connect
to servers. Clients could not connect to a server on a remote machine.

Update the test_ldms_push test program

---

util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/plugins-conf/Makefile.am

fix unaddressed review issue from #600.

V436 genders example update (makefile.am)

---

ldms/src/ldmsd/ldmsd.c

This applies strdup to keep -x and -A options from being edited in place, making ps output more useful. 
It also makes the -A error messages more useful by echoing the offending arg string.

preserve command line format in ldmsd at runtime.

---

configure.ac
ldms/src/ldmsd-samplers/Makefile.am
ldms/src/ldmsd-samplers/rdc_sampler/Makefile.am
ldms/src/ldmsd-samplers/rdc_sampler/rdc.conf
ldms/src/ldmsd-samplers/rdc_sampler/rdc.sh
ldms/src/ldmsd-samplers/rdc_sampler/rdc_sampler.c

Signed-off-by: Mike Li <Tianxinmike.Li@amd.com>

Add rdc plugin to collect AMD GPU metrics

---

ldms/src/core/ldms_xprt.c
ldms/src/core/ldms_xprt.h

This reverts commit d4565971667bea774c515890dfcf84e1ec68fd13.

Revert "Remove set_info from ldms_lookup message"

---

ldms/src/ldmsd/ldmsctl.c

The result of the daemon_status command has included the thread
statistics, but the daemon_status response handler in ldmsctl does not
handle the thread statistics. This change makes the handler print the
thread statistics.

Update the daemon_status response handler in ldmsctl

---

ldms/src/ldmsd/test/ldmsd_stream_subscribe.c

Add `-h <host>` option to `ldmsd_stream_subscribe` so that it can
listen to a specific address. This is useful for fabric transport.

ldmsd_stream_subscribe listen on a specific address

---

configure.ac
ldms/src/sampler/Makefile.am
ldms/src/sampler/dcgm/Makefile.am
ldms/src/sampler/dcgm/Plugin_dcgm.man
ldms/src/sampler/dcgm/dcgm.c
ldms/src/sampler/jobid_helper.c
ldms/src/sampler/jobid_helper.h
ldms/src/sampler/lustre_client/Makefile.am
ldms/src/sampler/lustre_client/Plugin_lustre_client.man
ldms/src/sampler/lustre_client/lustre_client.c
ldms/src/sampler/lustre_client/lustre_client.h
ldms/src/sampler/lustre_client/lustre_client_general.c
ldms/src/sampler/lustre_client/lustre_client_general.h
ldms/src/sampler/lustre_mdt/Makefile.am
ldms/src/sampler/lustre_mdt/Plugin_lustre_mdt.man
ldms/src/sampler/lustre_mdt/lustre_mdt.c
ldms/src/sampler/lustre_mdt/lustre_mdt.h
ldms/src/sampler/lustre_mdt/lustre_mdt_general.c
ldms/src/sampler/lustre_mdt/lustre_mdt_general.h
ldms/src/sampler/lustre_mdt/lustre_mdt_job_stats.c
ldms/src/sampler/lustre_mdt/lustre_mdt_job_stats.h
ldms/src/sampler/lustre_ost/Makefile.am
ldms/src/sampler/lustre_ost/Plugin_lustre_ost.man
ldms/src/sampler/lustre_ost/lustre_ost.c
ldms/src/sampler/lustre_ost/lustre_ost.h
ldms/src/sampler/lustre_ost/lustre_ost_general.c
ldms/src/sampler/lustre_ost/lustre_ost_general.h
ldms/src/sampler/lustre_ost/lustre_ost_job_stats.c
ldms/src/sampler/lustre_ost/lustre_ost_job_stats.h

This is a PR to upstream four plugins from the ldms-plugins-llnl project. They are: dcgm (Nvidia GPU monitoring), lustre_client, lustre_ost, and lustre_mdt.

Upstream sampler plugins from ldms-plugins-llnl

---

ldms/scripts/examples/rdc_sampler
ldms/scripts/examples/rdc_sampler.1
ldms/scripts/examples/rdc_sampler.2
ldms/scripts/examples/rdc_sampler.3
ldms/src/sampler/rdc_sampler/Plugin_rdc_sampler.man
ldms/src/sampler/rdc_sampler/ldms_rdc_schema_name.man
ldms/src/sampler/rdc_sampler/rdcinfo.c
ldms/src/sampler/rdc_sampler/rdcinfo.h

This removes the shape option, fixes a bug in delivery of the device metric, adds a debug option to ldms_rdc_schema_name, and updates manual pages.

rdc devices only version

---

configure.ac
ldms/src/sampler/Makefile.am

Add check for infiniband/iba/ib_types.h header

---

ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_request.h
ldms/src/ldmsd/ldmsd_request_util.c

Validate length of request headers
Validate attr doesn't reference beyond end of request
Check attr string is null terminated

Ldmsd request validation

---

ldms/src/ldmsd/test/ldmsd_stream_publish.c

This allows sending large numbers of messages on a single connection.

Add option to publish one line at a time

---

ldms/python/ldms.pyx

If the connection is terminated while `ldms.dir()` is waiting for the
dir result, it blocking waits indefinitely. This patch remove the
`_dir_sem` semaphore specific for `ldms.dir()` and use `_conn_sem`
instead, so that the `ldms.dir()` unblocks and raise an exception when
the connection terminates.

Fix forever blocked ldms.dir() in Python

---

lib/src/zap/rdma/zap_rdma.c

`ibv_post_send()` can be called from the application thread(s) or from
the cq thread. It should be protected by the same lock to ensure
correct message sequence.

Fix zap_rdma ibv_post_send() race

---

ldms/src/ldmsd/ldmsd_failover.c

The patch fixes two bugs in the failover’s ping logic. First, the ping
response does not include PEERCFG_ACTIVATED in the flag when the peercfg
has been activated. Second, the ping response handler checks whether the
failover buddy has activated the peercfg or not with the wrong logic. It
verifies whether the buddy’s failover has been configured or not instead
of checking if the buddy has started the peercfg. If the buddy has
started the peercfg, it should not start its own cfg yet.

Fix the failover's ping logic

---

lib/src/coll/Makefile.am
lib/src/coll/htbl.c
lib/src/coll/rbt.c
lib/src/ovis_json/ovis_json.c
lib/src/ovis_json/ovis_json.h
lib/src/ovis_json/ovis_json_test.c

json needs an value_str_str function, htbl needs a test like rbt, and rbt needs format string patches to pass -Wall -Werr.

minor patches for json, htbl, and rbt 

---

ldms/src/core/ldms_xprt.c

fixes related error logging in caller also.

fix #773 unreleased lock in __send_lookup_reply

---

ldms/src/core/ldms.c
lib/src/zap/sock/zap_sock.c
lib/src/zap/zap.c

The new process has only one thread after fork (see `fork(2)`), and
hence the need of `pthread_atfork()` in `ldms.c`, `zap.c` and
`zap_sock.c` to re-initialize the set delete thread, zap worker
threads and zap sock io thread respectively. However, the Slurm
job_container feature failed to run a task because it called
`setns()` that did not support multi-threading. Basically, Slurm
job_container feature could not be used with slurm_notifier.
To work around the Slurm job_container `setns()` issue, this patch
modified `ldms.c`, `zap.c` and `zap_sock.c` so that they will not
re-create the threads right away after fork. Instead, they will just
reset the initialization state at fork, and the transport-related
threads will be created at the creation of the first endpoint after
fork (the …

Re-initialize ldms/zap threads at first endpoint creation

---

ldms/man/Plugin_lnet_stats.man
ldms/scripts/examples/lnet_stats
ldms/scripts/examples/lnet_stats.2
ldms/scripts/examples/lnet_stats.3
ldms/src/sampler/lnet_stats.c

fixes #765
includes updated man page and test driver

fix #765 lnet_stats  retry needed

---

ldms/src/auth/ldms_auth_munge.c

auth_munge uses local address obtained from zap as munge data payload.
The peer then unmunge the payload and compare with its remote address
(which is our local address). If the payload matches the expected
address, the connection is authenticated.
zap_rdma had a bug that mixed up remote/local addresses, and the bug
stayed in the tree for quite some time (since v4.3.3). After v4.3.7,
commit 891da2b addressed the local/remote address mixed-up bug, but
this introduced auth_munge compatibility issue over rdma xprt because
v4.3.7 expected the mixed-up remote address, but 891da2b would send
the correct one, causing auth_munge to invalidate the connection.
This patch is a work-around in auth_munge to use the mixed-up
addresses for the rdma transport.

Fix auth_munge compatiblity issue over rdma xprt

---

lib/src/zap/rdma/zap_rdma.c

`__ep_flush()` may be called before cq_channel is created. Hence, it
shall check if `cq_channel` is not NULL before trying to reap the cq
event from the channel in the flush path. In addition, `__ep_flush()`
should reap the event from the channel directly instead of calling
`z_rdma_handle_cq_event()` which will re-arm the channel that we are
flushing.

Fix SIGSEGV in zap_rdma __ep_flush() path

---

lib/src/zap/ugni/zap_ugni.c
lib/src/zap/ugni/zap_ugni.h

This has been manually tested with ldmsd - ldms_ls with munge authentication.

Fix ldms-munge over zap_ugni

---

README.md

Add a weekly test status shield (or badge) to `README.md`. The shield is
an SVG image generated by `https://shields.io` and the JSON data
provided by `https://github.com/ldms-test/weekly-report` weekly report
repository. When the weekly script is run, the new results is published
to the weekly report repository and the shield is automatically updated
(after 5-minute github image cache expiration) without altering the URL
(no changes to README.md).

Add a weekly test status shield/badge to README.md

---

ldms/scripts/examples/dstat.job
ldms/scripts/examples/dstat.job.1
ldms/scripts/examples/dstat.job.2
ldms/scripts/examples/dstat.job.3
ldms/src/sampler/dstat/Plugin_dstat.man
ldms/src/sampler/dstat/dstat.c

fixes #843 
updated man page and test.

add sc_clk_tck optional field to dstat sampler

---

ldms/src/sampler/ibmad_sampler/Makefile.am
ldms/src/sampler/ibmad_sampler/ibmad_sampler.c

this add auth configuration and register/deregister to the ibmad sampler.

add auth support to ibmad_sampler

---

ldms/src/sampler/procnet/procnet.c

fix missing call to update perms on procnet sets

---

ldms/src/store/store_sos.c

This allows for the SOS store to serialize with external
administrative actions such as importing and exporting
partitions.

Add transaction support to store_sos

---

configure.ac
ldms/src/core/ldms.c
ldms/src/core/ldms_xprt.c
ldms/src/ldmsd/ldmsd_prdcr.c
ldms/src/ldmsd/ldmsd_updtr.c
ldms/src/store/Makefile.am
ldms/src/store/kokkos_appmon/Makefile.am
ldms/src/store/kokkos_appmon/kokkos_appmon.c
ldms/src/store/kokkos_appmon/kokkos_appmon.h
ldms/src/store/store_sos.c
lib/src/zap/ugni/zap_ugni.c

Kokkos Application Monitoring store and multiple fixes implemented as part of scalability testing.

Kokkos appmon store

---

ldms/src/contrib/sampler/ipmireader/ipmireader.c
ldms/src/contrib/sampler/ipmireader/ipmisensors.c

-Werr build will fail if ipmi is enabled. this fixes that.

fix build warnings in ipmi sampler

---

ldms/src/store/kokkos_appmon/kokkos_appmon.c
ldms/src/store/store_sos.c

These commits fix resiliency issues found during 4.3.8 testing with
some of the storage plugins.

Store resilience

---

ldms/src/store/darshan/darshan_stream_store.c

Support HDF5 Json messages parsing

Darshan store: support HDF5 Json messages parsing

---

Makefile.am
ldms/Makefile.am
ldms/scripts/Makefile.am
ldms/src/sampler/hello_stream/Makefile.am
ldms/src/sampler/hello_stream/stream_configs/Makefile.am
ldms/src/third-plugins/my_plugin/Makefile.am
lib/Makefile.am
util/relocation/Makefile.am
util/sample_init_scripts/Makefile.am
util/sample_init_scripts/genders/Makefile.am
util/sample_init_scripts/genders/examples/Makefile.am
util/sample_init_scripts/genders/man/Makefile.am
util/sample_init_scripts/genders/systemd/Makefile.am
util/sample_init_scripts/genders/systemd/etc/Makefile.am
util/sample_init_scripts/genders/systemd/etc/sysconfig/Makefile.am
util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/ClusterGenders/Makefile.am
util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/ClusterSecrets/Makefile.am
util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/Makefile.am
util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/debug/Makefile.am
util/sample_init_scripts/genders/systemd/etc/sysconfig/ldms.d/plugins-conf/Makefile.am
util/sample_init_scripts/genders/systemd/services/Makefile.am
util/sample_init_scripts/genders/sysv/etc/Makefile.am
util/sample_init_scripts/genders/sysv/etc/init.d/Makefile.am

This makes our install more standard but most likely will require
minor mods to rpm spec files, as noted in #366.

move files in share/doc/ovis-ldms-$version to share/doc/ovis-ldms

---

ldms/src/store/store_sos.c

The SOS store uses transactions to coordinate with
storage management activities such as roll-over. If
one of these activities fails and leaves the transaction
open, it would hang the SOS store and associated I/O
thread. This changes adds a configurable timeout that
the store will wait to acquire a transaction.

Add transaction timeout in store_sos

---

ldms/src/sampler/app_sampler/linux_proc_sampler.c

The cmdline metric normally is a nul separated/terminated string list in a single char array. The len metric cmdline_len also available.
Currently no text-based store format handles embedded nul correctly. Allowing the user to specify a single char separator allows cmdline to be represented in the way the admin chooses. In the long term, converting cmdline from a string metric to a list of strings metric is the right thing to do. 
This patch also fixes missing \n on several log messages.

add argv_sep option to specify nul replacements in cmdline metric

---

kokkosConnector/kp_kernel_info.h
kokkosConnector/kp_kernel_ldms.cpp
kokkosConnector/kp_kernel_timer.h

Adding files for the Kokkos Connector

Adding Kokkos Connector

---

ldms/src/ldmsd/ldmsd.c

At least one way to invoke double cleanup and assorted memory
errors is to invoke daemon_exit in a script.
This protects cleanup with a mutex and a 'cleaned' flag.

fix double cleanup() of whatever source

---

configure.ac
ldms/src/sampler/Makefile.am
ldms/src/sampler/coretemp/Makefile.am
ldms/src/sampler/coretemp/Plugin_coretemp.man
ldms/src/sampler/coretemp/coretemp.c

This sampler monitors data from the /sys/dev entries
collected by the coretemp module.

Add sampler to collect from the coretemp module

---

ldms/src/sampler/lustre_client/Makefile.am
ldms/src/sampler/lustre_client/Plugin_lustre_client.man
ldms/src/sampler/lustre_client/lustre_client.c
ldms/src/sampler/lustre_client/lustre_client_general.c
ldms/src/sampler/lustre_client/lustre_client_general.h

address #915 for lustre_client and update sample process to retrun failure when out of available set memory. otherwise admin may think ldms monitors less llites than there actually are.

add perm= and oom check to lustre_client

---

ldms/man/Makefile.am
ldms/man/Plugin_store_csv.man
ldms/man/Plugin_store_kafka.man
ldms/man/Plugin_store_sos.man
ldms/man/ldmsd_decomposition.man
ldms/src/store/kafka/store_kafka.c

- Add `ldmsd_decomposition` man page
- Add `Plugin_store_kafka` man page
- Update `Plusing_store_sos`, mentioning decomposition option
- Update `Plusing_store_csv`, mentioning decomposition option

Decomposition documentation & updates

---

ldms/src/core/ldms.c

Functions dir_update under ldms_set_publish and process_dir_request
can both be using __ldms_format_set_meta_as_json at the
same time. In this patch, making the format strings for state, perm stack
instead of static makes this safe and the data output correct.

fix races on static buffers in ldms.c json formatting

---

ldms/src/ldmsd/ldmsd_request.c

LDMSD keeps the storage policy, although it fails to initialize the
decomposition. If users start the storage policy incidentally, it will fall to
the legacy storing method.

Destroy strgp when initializing decomposition fails

---

ldms/src/store/store_sos.c

sos_begin_x_wait replaces sos_begin_x with timeout parameter
sos_begin_x no longer accepts timestamp argument

SOS-6 transaction API changes in store_sos

---

ldms/src/sampler/netlink/netlink-notifier.c

This adds use of reset and removes extra append_attr to improve efficiency.

update jbuf usage in netlink-notifier

---

lib/src/mmalloc/mmalloc.c

- Lock the mmr trees before verifying the trees
- Add a variable to turn on/off the report of the trees' structure
Configure with -DLDMS_MM_DEBUG to verify the mmr's trees and set __mm_debug_verbose to a non-zero value to print the structures

Improve and fix the debugging code in mmalloc.

---

lib/src/zap/sock/zap_sock.c

zap_sock moves the endpoint state to ERROR when it receives the rejected message. However, it does not put back the 'connect/accept' reference in sock_event() if the endpoint state is ZAP_EP_ERROR.
The endpoint state move to ERROR from either CONNECTING or ACCEPTING. zap_sock takes the 'connect/accept' reference when it moves the state to CONNECTING, but it does not take the reference when the state moves to ACCEPTING.
The patch makes sure that zap_sock takes the 'connect/accept' reference when the endpoint state moves to CONNECTING or ACCEPTING. Morevoer, it changes zap_sock to return back the reference in sock_event() if the endpoint state is ERROR.

Fix zap_sock leaking endpoints if servers reject the connect requests

---

ldms/src/ldmsd/ldmsd_request_util.c

ldmsd_parse_config_str() does not add the terminating attribute to the message before converting the message from the host endian to the network endian. LDMSD may crash while processing a long config line.
The change also addresses the logic that chunks the messages into multiple records if the message is larger than the maximum of the transport message size. Before the change, the logic assumes that the message does not contain the terminating attribute.

Fix the broken config line parsing logic in ldmsd_request_util.c

---

ldms/src/sampler/examples/test_sampler/test_sampler.c

* Remove the assumptions that the compnent_id and job_id are uint64.
* Make the metric attribute delimiter configurable by giving the 'delim' attribute at the action=add_schema line.

Improve the test_sampler plugin

---

ldms/src/sampler/dstat/.gitignore
ldms/src/sampler/netlink/.gitignore
lib/src/ovis_json/.gitignore

Ignore more binaries in .gitignore files.

Additional .gitignore entries

---

ldms/python/ldms.pyx

PyEval_InitTheads() is deprecated in Python 3.9 and will be removed in Python 3.11.

Handle PyEval_InitTheads() deprecation

---

ldms/src/sampler/rdc_sampler/Plugin_rdc_sampler.man

remove incorrect producer documentation for rdc plugin

---

ldms/python/ldms.pyx

Adds connection timeout option for ldms transports

optional timeout for ldms transport

---

ldms/python/ldms.pyx

Moves return code comparison outside of nogil

cython backwards compatability

---

ldms/src/sampler/procstat2/procstat2.c

Remove the interrupt and soft interrupt lists from the procstat2 set. The interrupt and soft interrupt lists are collected in separated sets. The plugin creates the interrupt set and the soft interrupt set according to the configuration attribute 'interrupt' and 'soft_interrupt'.

Modify the procstat2 set

---

ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller

Add json formatting for status request responses in ldmsd_controller

Normalize all ldmsd_communicator response messages to strings

---

ldms/python/ldmsd/ldmsd_controller

Check if 'summary' argument is None

Adjust argument checking in ldmsd_controller

---

ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller

update json format for thread_stats, daemon_status, and failover_status

Add parsing for boolean values in LDMSD_Req_Attr class

---

ldms/src/ldmsd/ldmsd_request.c

The handler did not set the errcode when the given type is invalid. It results in a silense error. Also, the handler did not validate whether the given interval string. The patch makes the handler responds with an error if the given interval is not a positive number.

Fix prdcr_add_handler to properly return an error

---

ldms/src/sampler/sampler_base.c
ldms/src/sampler/sampler_base.h
ldms/src/sampler/slurm/slurm_sampler2.c

Changed the name to more accurately represent that the purpose of this function is to register a new subsystem with the logger.

Change ovis_log_create to ovis_log_register

---

ldms/src/sampler/sampler_base.c
ldms/src/sampler/sampler_base.h
ldms/src/sampler/slurm/slurm_sampler2.c

Add support for the slurm2 sampler to sampler_base

Slurm2 sampler base

---

configure.ac
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_decomp.c
ldms/src/store/Makefile.am
ldms/src/store/avro_kafka/Makefile.am
ldms/src/store/avro_kafka/Plugin_avro_kafka_store.man
ldms/src/store/avro_kafka/examples/agg-decomp.conf
ldms/src/store/avro_kafka/examples/flex_decomp.json
ldms/src/store/avro_kafka/examples/kafka.conf
ldms/src/store/avro_kafka/examples/serdes.conf
ldms/src/store/avro_kafka/store_avro_kafka.c

A storage plugin that serializes metric set data using Avro and publishes this data on the Kafka bus.

Avro-Kafka Store

---

configure.ac
ldms/src/ovis-ldms-configvars.sh.in
lib/src/ovis_auth/Makefile.am
lib/src/ovis_auth/ovis-auth.sh.in

this fixes linkage issue with rabbit plugins.

update OVIS_AUTH_LIBS macro in configure.ac

---

ldms/src/store/avro_kafka/Plugin_store_avro_kafka.man
lib/src/zap/zap.c

Update the store_avro_kafka man page with the latest logicalType annotations.

Avro kafka man

---

ldms/src/ldmsd/ldmsd_request.c

Resolve issue #1183 where multiple commas will be inserted into the json response object if a producer is disconnected

Account for unresponsive producers in update_time_stats json formatting

---

ldms/python/ldmsd/ldmsd_communicator.py

The fix makes the handler to handle the decomposition attribute.

Fix the strgp_add handler in ldmsd_communicator.py

---

ldms/src/sampler/blob_stream/Plugin_blob_stream_writer.man
ldms/src/sampler/blob_stream/ldms-csv-from-blobs
ldms/src/sampler/blob_stream/ldms-csv-from-blobs.man

This script handles simple cases only. When a fully flexible stream decomposition store policy is available, we can probably dispense with it.

Add simple blob store to csv transformation script/manual

---

ldms/src/store/darshan/darshan_stream_store.c
ldms/src/store/kokkos_appmon/kokkos_appmon.c

Updating stores with new fields. Also removing len+1 obj_puts for str types that Omar had added which only add a null character. This null character makes filtering on those fields impossible.

Updating Kokkos and Darshan Stores

---

ldms/scripts/examples/edac
ldms/scripts/examples/edac.1
ldms/src/sampler/llnl/Plugin_edac.man
ldms/src/sampler/llnl/edac.c

Fix bug in edac sampler and improve error message and man page and test

---

ldms/src/ldmsd/ldmsd.h

Add documentation for ldmsd set registration API

---

ldms/src/contrib/sampler/gpu_metrics_sampler/gather_gpu_metrics.cpp
ldms/src/contrib/sampler/gpu_metrics_sampler/gmg_ldms_util.c
ldms/src/contrib/sampler/gpu_metrics_sampler/gmg_log.c

Refactor schema and metric names

[FIX] change schema name to aggregate data

---

lib/src/zap/sock/zap_sock.c

zap_sock uses the thread of the listening to initially process new passive endpoints (from connection requests). It correctly removed the new endpoints from the listening thread epoll as the threads assigned to the new endpoints will further process the events. Hoever, zap_sock forgot to stop the processing loop in the listening thread, resulting in wrong endpoint processing. This patch fixes the bug.

Fix accepting endpoint race in zap_sock

---

ldms/src/auth/ldms_auth_ovis.c
ldms/src/core/ldms_xprt.c
ldms/src/sampler/app_sampler/app_sampler.c
ldms/src/sampler/app_sampler/linux_proc_sampler.c
ldms/src/sampler/blob_stream/blob_stream_writer.c
ldms/src/sampler/coretemp/coretemp.c
ldms/src/sampler/examples/synthetic/synthetic.c
ldms/src/sampler/examples/test_sampler/test_sampler.c
ldms/src/sampler/hweventpapi.c
ldms/src/sampler/lustre_mdt/lustre_mdt_job_stats.c
ldms/src/sampler/lustre_ost/lustre_ost_job_stats.c
ldms/src/sampler/papi/papi_config.c
ldms/src/sampler/papi/papi_sampler.c
ldms/src/sampler/procdiskstats/procdiskstats.c
ldms/src/sampler/sampler_base.c
ldms/src/sampler/slurm/slurm_sampler.c
ldms/src/sampler/slurm/slurm_sampler2.c
ldms/src/store/store_csv_common.c
ldms/src/store/store_function_csv.c
ldms/src/store/stream/stream_csv_store.c
ldms/src/store/stream_dump/stream_dump.c
lib/src/ovis_log/ovis_log.h
lib/src/zap/fabric/zap_fabric.c
lib/src/zap/rdma/zap_rdma.c
lib/src/zap/sock/zap_sock.c

This is to help compiler warns about print format error.

Add formatted print attribute to `ovis_log()`

---

ldms/src/core/ldms_stream.c

This patch fixes incorrect locks and entry removal in stream client stats.

Fix `stream_client_stats` bug

---

ldms/src/core/ldms_stream.c

- Do not set 'src' if it is a loopback address since the loopback address is not informative to the aggregators. Keeping the 'src' to 0 in the case of loopback allows the next level of aggregation resolve for the non-loopback src IP address.
- Add the missing network-to-host port conversion in str printing.

Fix LDMS stream src stats bugs

---

lib/src/ovis_log/ovis_log.c

The log handle may be destroyed while ovis_vlog() is accessing it.

Fix a race between ovis_log_destroy() and ovis_vlog()

---

lib/src/ovis_log/ovis_log.c

Without the patch, a log handle may be destroyed while ovis_vlog() is accessing it.

Fix a race between ovis_vlog() and ovis_log_destroy()

---

lib/src/zap/sock/zap_sock.c

The incoming-connection-request endpoint that got rejected by the application did not yet have a thread to process its events. As a result, when the remote peer disconnected after receiving REJECTED message, the passive side would not get EPOLLHUP event (which will drop corresponding references and clean up endpoint resources) because the endpoint was not in any thread's epoll. The rejected endpoint was left dangling, leaking endpoint resources including socket file descriptor.
This patch fixes the issue by dropping the corresponding endpoint references to clean up rejected endpoint resources. The rejected endpoint does not need to get a zap thread assigned to handle this.
NOTE:
This bug is introduced by Rail implementation. The RAIL implementation modified `zap_sock` to use the thread of …

Fix zap_sock rejected endpoint leak

---

ldms/src/sampler/dcgm_sampler/dcgm_sampler.c

Use correct ldms function to add string metrics.
Add error messages.
Fixes #1321

dcgm_sampler: fix handling of DCGM string fields

---

ldms/src/ldmsd/ldmsd_config.c

the avl/kwl structures are now cleaned up on a failed call to get the plugin in ldmsd_config_plugin.

fix memory leak on config call with bad plugin name

---

ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller

Decomposition fixes for OVIS-4.4.3
strgp_add was not properly handling schema and regex when submitted through ldmsd_communicator interface
error handling in ldmsd_controller when schema and regex are submitted simultaneously

Decomposition fixes for OVIS-4.4.3

---

.github/workflows/4.3.3-compat-test.yaml
.github/workflows/build-ddebug-centos7.yaml
.github/workflows/build-test-centos7.yaml
.github/workflows/build-test-ubuntu-22.04.yaml
.github/workflows/build-test-ubuntu.yaml
.github/workflows/create-release.yaml
.github/workflows/ldms-test-build.yaml
.github/workflows/space-check.yaml
.github/workflows/test-make-dist.yaml

Also added support for using main and v* style tags in the future.

Update workflows to support b4.4 (branch OVIS-4 edition)

---

configure.ac
ldms/src/ldmsd/ldmsd_decomp.c
ldms/src/sampler/Makefile.am
ldms/src/sampler/rdc_sampler/Makefile.am
ldms/src/sampler/slingshot_info/slingshot_info.c
ldms/src/sampler/zfs_leafvdevs/Makefile.am
ldms/src/sampler/zfs_leafvdevs/Plugin_zfs_leafvdevs.man
ldms/src/sampler/zfs_leafvdevs/zfs_leafvdevs.c
ldms/src/sampler/zfs_topvdevs/Makefile.am
ldms/src/sampler/zfs_topvdevs/Plugin_zfs_topvdevs.man
ldms/src/sampler/zfs_topvdevs/zfs_topvdevs.c
ldms/src/sampler/zfs_zpool/Makefile.am
ldms/src/sampler/zfs_zpool/Plugin_zfs_zpool.man
ldms/src/sampler/zfs_zpool/zfs_zpool.c
ldms/src/store/avro_kafka/store_avro_kafka.c

These are the patches that we are currently carrying for b4.4 in the TOSS release of ovis-ldms.
If we think some of them shouldn't land yet, I can prune the list. Let me know.

Backports for b4.4

---

.github/workflows/4.3.3-compat-test.yaml
.github/workflows/build-ddebug-centos7.yaml
.github/workflows/build-test-centos7.yaml
.github/workflows/build-test-ubuntu-22.04.yaml
.github/workflows/build-test-ubuntu.yaml
.github/workflows/create-release.yaml
.github/workflows/ldms-test-build.yaml
.github/workflows/space-check.yaml
.github/workflows/test-make-dist.yaml

Also added support for using main and v* style tags in the future.

Update workflows to support b4.4

---

ldms/src/store/darshan/darshan_stream_store.c

The current darshan_stream_store.c file has JSON fields that are out of date and causing DSOS storage issues.
I've updated these fields to reflect the most recent Darshan JSON messages being sent to LDMS streams.

Updated Darshan Store Fields for b4.4 Branch

---

ldms/src/store/darshan/darshan_stream_store.c

The current darshan_stream_store.c file has JSON fields that are out of date and causing DSOS storage issues.
I've updated these fields to reflect the most recent Darshan JSON messages being sent to LDMS streams.

updating darshan store fields

---

configure.ac
ldms/src/sampler/Makefile.am
ldms/src/sampler/json/Makefile.am
ldms/src/sampler/json/Plugin_json_stream_sampler.man
ldms/src/sampler/json/json_stream_sampler.c

This is a port of `json_stream_sampler` from OVIS-4 (reference commit-id: 4c6a0171ba4c9342aff44a4f6610cabaa71078b7).

A port of `json_stream_sampler` from OVIS-4

---

configure.ac
ldms/src/core/ldms.c
ldms/src/core/ldms.h
ldms/src/decomp/as_is/Makefile.am
ldms/src/decomp/as_is/decomp_as_is.c
ldms/src/decomp/flex/Makefile.am
ldms/src/decomp/flex/decomp_flex.c
ldms/src/decomp/static/Makefile.am
ldms/src/decomp/static/decomp_static.c
ldms/src/ldmsd/Makefile.am
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_decomp.c
ldms/src/ldmsd/ldmsd_request.c
ldms/src/ldmsd/ldmsd_row_cache.c
ldms/src/ldmsd/ldmsd_strgp.c

This is a backport of the two operators-in-decomposition commits from OVIS-4.

Support for operators in storage decomposition backport for  4.4

---

ldms/src/core/ldms_stream.c

'::1' is the loopback for IPv6 family. The variable `in6addr_loopback` defined in "netinet/in.h" was set to `::1` value for easy comparison. However, we missed `::ffff:127.0.0.1` which is the IPv4 loopback in the IPv6 format. This patch uses both `::1` and `::ffff:127.0.0.1` to determine if an IPv6 address is a loopback.

Also add '::ffff:127.0.0.1' loopback comparison for IPv6

---

ldms/src/ldmsd/ldmsd_request.c

Add error case when user attempts to create a producer listen that already exists.

Update error handling for prdcr_listen_add

---

ldms/src/decomp/static/decomp_static.c
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_row_cache.c

This is the OVIS-4 branch version of PR #1432 (which is for b4.4).

Fix decomp operations (OVIS-4 branch)

---

ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller
ldms/src/ldmsd/ldms_ls.c

An empty list would cause the -d option to segv.

Fix ldms_ls crash dumping a decomposition

---

ldms/src/ldmsd/ldmsd_request.c

Set errcode properly for `set_sec_mod` error cases.

Fix `set_sec_mod` command error response

---

ldms/src/core/ldms_stream.c

The code in `__remote_client_cb()` mistakenly assumed that `sbuf` is always available. 'sbuf' could be NULL for the stream publishing originating from the local process. In such case, we shall not queue the stream message and return with the error (application back-pressure).

Fix SIGSEGV in ldms_stream due to NULL sbuf

---

README.md

Add a badge for b4.4 test results in README.md.

Add test badge for b4.4 in README.md

---

ldms/src/store/store_csv.c

b4.4 bug: Store csv lents

---

ldms/man/ldmsd_decomposition.man

Update `ldmsd_decomposition.man` to reflect the latest "src", "dst", "type", "fill" and "op".

[b4.4] static decomposition man update

---

ldms/src/decomp/static/decomp_static.c

Update `mean` operation in decomp_static to avoid overflow/underflow issue.

[b4.4] Update `mean` operation in decomp_static

---

ldms/scripts/ldms-static-test.sh.in
ldms/scripts/pll-ldms-static-test.sh.in

Daemonize ldms-static-test.sh

---

ldms/man/ldmsd_decomposition.man

Update `ldmsd_decomposition.man` to reflect the latest "src", "dst", "type", "fill" and "op".
This is the same as #1515, but for `main` branch.

static decomposition man update

---

ldms/src/decomp/static/decomp_static.c

Update `mean` operation in decomp_static to avoid overflow/underflow issue.
This is the same as #1511 , but for `main` branch.

Update `mean` operation in decomp_static

---

ldms/src/decomp/static/decomp_static.c
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_row_cache.c

This is #1525 but for the main branch.

ldmsd row cache cleanup

---

ldms/src/sampler/json/json_stream_sampler.c

This change adds support for multiple schema to the json_stream_sampler.

Add multi-schema support to the json_stream_sampler

---

ldms/man/ldmsd_decomposition.man
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_row_cache.c

- Add a note in rowcache cleanup code.
- Add "timeout" attribute documentation in `ldmsd_decomposition.man`

Add rowcache cleanup note and doc

---

ldms/man/ldmsd_decomposition.man
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_row_cache.c

- Add a note in rowcache cleanup code.
- Add "timeout" attribute documentation in `ldmsd_decomposition.man`

[b4.4] rowcache cleanup note and doc

---

ldms/man/Makefile.am
ldms/man/ldmsd.man
ldms/man/ldmsd_yaml_parser.man
ldms/python/ldmsd/Makefile.am
ldms/python/ldmsd/hostlist.py
ldms/python/ldmsd/ldmsd_controller
ldms/python/ldmsd/ldmsd_yaml_parser
ldms/python/ldmsd/parser_util.py
ldms/src/ldmsd/ldmsd.c
ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_config.c

Adds ldmsd_yaml_parser and ldmsd "-y" option to parse YAML files when starting a LDMSD Support for rails-specific parameters in YAML configuration file Update usage documentation in ldmsd_controller to include "ip" for LdmsdCmdParser class method "do_prdcr_listen_add"

YAML configuration file support for OVIS-4.5

---

ldms/python/ldmsd/parser_util.py

Refactor regular expression matching for YAML configuration

Regex matching for YAML configuration

---

ldms/src/ldmsd/ldmsd_decomp.c

The original code incorrectly used !stat() which would continue the loop when the library was failed to be loaded (stat returns 0). Change to continue searching for the library when stat() returns a non-zero. Otherwise, an error message is reported.

Correct stat() error check in decomposition library loading

---

ldms/src/core/ldms_xprt.c

The deadlock occurred in ldms_xprt when it held xprt_list_lock while calling zap_send(). Upon error, ldms_xprt triggered zap_close() which waited for mutex signal if there were pending sends and the thread wasn't endpoint's thread. The patch modifies ldms_xprt to release xprt_list_lock before calling zap_send().

Prevent deadlock between xprt_list_lock and Zap credit lock

---

ldms/src/ldmsd/ldmsd_request.c

In prdcr_stream_status handling, the patch replaces assert() with log messages when receiving multiple response or invalid response format from a producer. Also, it adds mutex lock when removing producer name from the producer list. This prevents daemon crash when multiple responses are received while making the error handing more robust.
The assert was reported in Github issue 1598 but could not be reproduced in test environment. This change allows gathering more information about the condition while maintaining system stability.
Resolve #1598

Replace assertions with log messages in prdcr_stream_status handling

---

docs/.gitignore
docs/Makefile.am

Add ldms_stream.rst to EXTRA_DIST always.
Add .gitignore of ldms_stream.man (which is autogenerated at build time).

Add ldms_stream.rst to EXTRA_DIST always

---

ldms/scripts/examples/dcgm1.1
ldms/scripts/examples/dcgm1.2
ldms/src/sampler/dcgm_sampler/dcgm_sampler.c

before jobid data didn't get set if use_base was set.

added use of base, when configured, in sampling dcgm

---

ldms/man/ldmsd_yaml_parser.rst
ldms/python/ldmsd/ldmsd_yaml_parser
ldms/python/ldmsd/parser_util.py
ldms/src/ldmsd/ldmsd_config.c

Support for subsets of hostlist expressions
Normalize ldmsd_yaml_parser parameter names
Add error handling if mutually exclusive parameters are provided

Refactor internal dictionaries of YAML cluster configuration

---

ldms/src/core/ldms.c

The patch adds remaining buffer size tracking and assertions to validate string copy operations in __make_mdesc(). While the memory allocation is correct in ldms_set_create() which calculates the total required space, including names and units, the compiler cannot determine this relationship. These explicit checks document the safety of the string operations and prevent the compiler warnings without changing the functionality.
This maintains the existing memory management approach while making the safety guarantees explicit to both the compiler and future code readers.
Resolve #1054

Add buffer length validation in __make_mdesc to silence compiler warnings

---

.github/workflows/build-test-centos7.yaml
.github/workflows/build-test-ubuntu-22.04.yaml
.github/workflows/build-test-ubuntu.yaml
.github/workflows/create-release.yaml
.github/workflows/ldms-test-build.yaml
.github/workflows/space-check.yaml
.github/workflows/test-make-dist.yaml

Also update the github "runner" to 'ubuntu-latest'.

Remove explicit SOS-6 branch checkout in ldms-test-build

---

ldms/src/sampler/json/json_stream_sampler.c

fix free of uninit pointer in json sampler callback

---

ldms/src/store/store_amqp.c

Make the ldmsd_plugin_interface non-static in store_ampq.c.

store_ampq: make ldmsd_plugin_interface non-static

---

ldms/src/sampler/dcgm_sampler/dcgm_sampler.c

In sample(), initialize the dcgm library if it is not currently initailized. When gpu_sample() fails in sample(), shutdown the dcgm library usage.
Fixes #1636

dcgm_sampler: reinitialize the dcgm library when needed

---

ldms/python/ldmsd/ldmsd_communicator.py
ldms/python/ldmsd/ldmsd_controller

The pull request ports commit 'https://github.com/ovis-hpc/ldms/commit/bfd582446449f4b9fab01e3162daea612ab4a9a9' from `b4.4`.

Add test mode support for log_level command in ldmsd_controller

---

ldms/src/ldmsd/ldmsd.rst

This pull request ports commit 6318c9e from `b4.4`.

Document LDMS_DELETE_TIMEOUT environment variable

---

ldms/python/ldmsd/ldmsd_yaml_parser
ldms/python/ldmsd/parser_util.py

Add permission handling for "rw-rw-r--" syntax in YAML plugin configuration

Add permission handling in YAML plugin configuration

---

ldms/src/store/store_sos.c

This pull request ports the commit https://github.com/ovis-hpc/ldms/commit/ffd70a8ec11a7c6e7a913b7a87bfd566542268d0 from the `b4.4` branch.

store_sos: Replace assertion with type mismatch error message

---

ldms/src/sampler/tx2mon/tx2mon.c

Fix the plugin config name lookup in tx2mon.
Fixes #1759

Repair tx2mon name lookup

---

ldms/src/sampler/cxi_sampler/cxi_sampler.c
ldms/src/sampler/cxi_sampler/ldms-sampler_cxi_sampler.rst

Introduce the virtual metric derived:link_restarts.  When specified in tel_counters or tel_counters_file, the cxi_sampler watches the link_restarts timestamp files and keeps a count of the changes in the metric named "derived:link_restarts". This allows us to count up to 10 link restarts per sample interval, which is good enough in practice for relatively quick sampling rates (say 5s or faster) to detect floods of link restart issues.

cxi_sampler: Introduce the virtual metric derived:link_restarts

---

configure.ac
ldms/src/sampler/Makefile.am
ldms/src/sampler/hello_ldms_msg/Makefile.am
ldms/src/sampler/hello_ldms_msg/hello_ldms_msg.c
ldms/src/sampler/hello_ldms_msg/ldms-sampler_hello_ldms_msg.rst

Sampler that duplicates the functionality of the hello_sampler (hello_stream) utilizing the ldms_msg protocol.
Messages are written to a log file or standard out.

hello_ldms_msg

---

ldms/src/ldmsd/ldmsd_prdcr.c

fix leaks and wild pointers in ldmsd_prdcr.c
- make __ldmsd_xprt_ctxt_free not free invalid pointers to substructures when called with null.
- initialize all members of ctxt to NULL to avoid free of wild pointers in error paths;
this affects prdcr_connect_cb ldmsd_prdcr_subscribe_regex ldmsd_prdcr_unsubscribe_regex
- fix leaks in ldmsd_prdcr_unsubscribe_regex error paths.

 fix leaks and wild pointers in ldmsd_prdcr.c

---

ldms/src/ldmsd/test/ldmsd_stream_subscribe.c

noone should be copying ldmsd_stream_subscribe for new development (use ldms_msg instead), but this patch may be useful to anyone that has in the past.

 Fix leaks and use-after-free in example code ldmsd_stream_subscribe.c

---

ldms/src/sampler/netlink/netlink-notifier.c
ldms/src/sampler/netlink/simple_lps.c

leaks, use-after-free, and null dereferences cleaned up.

fix search jobid path and variety of memory bugs in netlink directory

---

ldms/python/ldms.pyx

When `Xprt` operates in blocking mode (no `cb` given), `Xprt.recv()` blocked the caller if `timeout` was not given, as expected. However, if the connection went away while `Xprt.recv()` was blocking, the function blocked indefinitely, "hanging" the application in block-waiting. This patch addressed the issue by posting `None` to the `_recv_queue` so that the blocked `recv()` call got `None` (no data) in the return instead of being blocked indefinitely. The `Xprt.recv()` also returns `None` right away if `Xprt` was not connected.

Fix stalled Xprt.recv() in LDMS Python

---

ldms/src/ldmsd/ldmsd.h
ldms/src/ldmsd/ldmsd_request.c

This provides a batch of separable commits fixing leaks and logic errors for functions in ldmsd_request, with minor documentation additions where appropriate.
If any particular change is incorrect, the branch can be refactored to exclude it.
Each commit has a descriptive title.

numerous fixes to ldmsd_request.c bugs

---

ldms/src/ldmsd/test/ldms_msg_publish.c

Add `-U,--uid`, `-G,--gid`, and `-P,--perm` to `ldms_msg_publish` test program.

Add options to ldms_msg_publish test program

---

ldms/src/core/ldms.c

These are all sites where plugin api misuse can lead to unexplained daemon disappearance.
In most cases, checks are done in similar functions and just overlooked here.

fixed ldms.c missing NULL pointer checks yielding unexplained crashes

---

ldms/src/sampler/json/json_stream_sampler.c

- fix incorrect type casting.
- add multi instance support.
- uid, gid, perm of the sets (the metadata) follow the `config` line.
- `S_uid`, `S_gid`, and `S_perm` follow information in the message.

Fix `json_stream_sampler`

---

lib/src/ovis_event/ovis_event.c

PERIODIC events with negative phase (offset) caused events to fire at unexpected times. The patch handles when calculated next event timing would be in the past or exceed one period (interval), ensuring PERIODIC events never wait more than one period.
Fixes #2002

Make ovis_event's PERIODIC events support negative offsets

---

ldms/src/core/ldms_xprt.c

The list in the set of the receiver side that use update-on-push is always _empty_ because `set->heap` has never been set. This patch set `set->heap` in the update-on-push path.

Fix list always empty in update-on-push mode
